### ISSUE TITLE
Exception thrown in markdown parsing causes main project page not to load

### ISSUE THREAD

**Issue by raymanoz** [gitbucket/gitbucket#1058]
I recently imported a new project into our gitbucket. When I tried to view the project via the browser, all I got was a blank page. I restarted the gitbucket server on the command line to see if there was any errors being thrown, and found the stacktrace below.

It seems that if the gitbucket markdown parser fails when loading the `readme.md` to show on the main page, it stops the page loading.

Here's the stacktrace:
```
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at io.github.gitbucket.markedj.Parser.tok(Parser.java:77)
	at io.github.gitbucket.markedj.Parser.parse(Parser.java:35)
	at io.github.gitbucket.markedj.Marked.marked(Marked.java:18)
	at gitbucket.core.view.Markdown$.toHtml(Markdown.scala:50)
	at gitbucket.core.plugin.MarkdownRenderer$.render(Renderer.scala:30)
	at gitbucket.core.view.helpers$.renderMarkup(helpers.scala:118)
	at gitbucket.core.repo.html.files$$anonfun$apply$7.apply(files.template.scala:138)
	at gitbucket.core.repo.html.files$$anonfun$apply$7.apply(files.template.scala:135)
	at scala.Option.map(Option.scala:146)
	at gitbucket.core.repo.html.files$.apply(files.template.scala:135)
	at gitbucket.core.controller.RepositoryViewerControllerBase$$anonfun$gitbucket$core$controller$RepositoryViewerControllerBase$$fileList$1$$anonfun$apply$90$$anonfun$apply$91.apply(RepositoryViewerController.scala:639)
	at gitbucket.core.controller.RepositoryViewerControllerBase$$anonfun$gitbucket$core$controller$RepositoryViewerControllerBase$$fileList$1$$anonfun$apply$90$$anonfun$apply$91.apply(RepositoryViewerController.scala:625)
	at gitbucket.core.util.ControlUtil$.defining(ControlUtil.scala:14)
	at gitbucket.core.controller.RepositoryViewerControllerBase$$anonfun$gitbucket$core$controller$RepositoryViewerControllerBase$$fileList$1$$anonfun$apply$90.apply(RepositoryViewerController.scala:625)
	at gitbucket.core.controller.RepositoryViewerControllerBase$$anonfun$gitbucket$core$controller$RepositoryViewerControllerBase$$fileList$1$$anonfun$apply$90.apply(RepositoryViewerController.scala:624)
	at scala.Option.map(Option.scala:146)
	at gitbucket.core.controller.RepositoryViewerControllerBase$$anonfun$gitbucket$core$controller$RepositoryViewerControllerBase$$fileList$1.apply(RepositoryViewerController.scala:624)
	at gitbucket.core.controller.RepositoryViewerControllerBase$$anonfun$gitbucket$core$controller$RepositoryViewerControllerBase$$fileList$1.apply(RepositoryViewerController.scala:622)
	at gitbucket.core.util.ControlUtil$.using(ControlUtil.scala:26)
	at gitbucket.core.controller.RepositoryViewerControllerBase$class.gitbucket$core$controller$RepositoryViewerControllerBase$$fileList(RepositoryViewerController.scala:622)
	at gitbucket.core.controller.RepositoryViewerControllerBase$$anonfun$7$$anonfun$apply$4.apply(RepositoryViewerController.scala:122)
	at gitbucket.core.controller.RepositoryViewerControllerBase$$anonfun$7$$anonfun$apply$4.apply(RepositoryViewerController.scala:122)
	at gitbucket.core.util.ReferrerAuthenticator$$anonfun$gitbucket$core$util$ReferrerAuthenticator$$authenticate$1$$anonfun$apply$12.apply(Authenticator.scala:123)
	at gitbucket.core.util.ReferrerAuthenticator$$anonfun$gitbucket$core$util$ReferrerAuthenticator$$authenticate$1$$anonfun$apply$12.apply(Authenticator.scala:121)
	at scala.Option.map(Option.scala:146)
	at gitbucket.core.util.ReferrerAuthenticator$$anonfun$gitbucket$core$util$ReferrerAuthenticator$$authenticate$1.apply(Authenticator.scala:121)
	at gitbucket.core.util.ReferrerAuthenticator$$anonfun$gitbucket$core$util$ReferrerAuthenticator$$authenticate$1.apply(Authenticator.scala:120)
	at gitbucket.core.util.ControlUtil$.defining(ControlUtil.scala:14)
	at gitbucket.core.util.ReferrerAuthenticator$class.gitbucket$core$util$ReferrerAuthenticator$$authenticate(Authenticator.scala:120)
	at gitbucket.core.util.ReferrerAuthenticator$class.referrersOnly(Authenticator.scala:115)
	at gitbucket.core.controller.RepositoryViewerController.referrersOnly(RepositoryViewerController.scala:34)
	at gitbucket.core.controller.RepositoryViewerControllerBase$$anonfun$7.apply(RepositoryViewerController.scala:121)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$liftAction(ScalatraBase.scala:270)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265)
	at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:182)
	at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.invoke(ScalatraBase.scala:264)
	at gitbucket.core.controller.ControllerBase.org$scalatra$json$JsonSupport$$super$invoke(ControllerBase.scala:27)
	at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:88)
	at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:82)
	at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:182)
	at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:27)
	at org.scalatra.json.JsonSupport$class.invoke(JsonSupport.scala:82)
	at gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:240)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:238)
	at scala.Option.flatMap(Option.scala:171)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:238)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:237)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:493)
	at org.scalatra.ScalatraBase$class.runRoutes(ScalatraBase.scala:237)
	at gitbucket.core.controller.ControllerBase.runRoutes(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:163)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:193)
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:27)
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply$mcV$sp(flashMap.scala:162)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$class.handle(flashMap.scala:136)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:27)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:33)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:32)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:64)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply$mcV$sp(ScalatraFilter.scala:71)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:71)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:71)
	at org.scalatra.ScalatraBase$$anonfun$2$$anonfun$apply$4.apply(ScalatraBase.scala:166)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$$anonfun$2.apply(ScalatraBase.scala:166)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:165)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:193)
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:27)
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply$mcV$sp(flashMap.scala:162)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$class.handle(flashMap.scala:136)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:27)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:33)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:32)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:64)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply$mcV$sp(ScalatraFilter.scala:71)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:71)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:71)
	at org.scalatra.ScalatraBase$$anonfun$2$$anonfun$apply$4.apply(ScalatraBase.scala:166)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$$anonfun$2.apply(ScalatraBase.scala:166)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:165)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:193)
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:27)
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply$mcV$sp(flashMap.scala:162)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$class.handle(flashMap.scala:136)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:27)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:33)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:32)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:64)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply$mcV$sp(ScalatraFilter.scala:71)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:71)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:71)
	at org.scalatra.ScalatraBase$$anonfun$2$$anonfun$apply$4.apply(ScalatraBase.scala:166)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$$anonfun$2.apply(ScalatraBase.scala:166)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:165)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:193)
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:27)
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply$mcV$sp(flashMap.scala:162)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$class.handle(flashMap.scala:136)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:27)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:33)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:32)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:64)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply$mcV$sp(ScalatraFilter.scala:71)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:71)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:71)
	at org.scalatra.ScalatraBase$$anonfun$2$$anonfun$apply$4.apply(ScalatraBase.scala:166)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$$anonfun$2.apply(ScalatraBase.scala:166)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:165)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:193)
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:27)
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply$mcV$sp(flashMap.scala:162)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$class.handle(flashMap.scala:136)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:27)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:33)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:32)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:64)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply$mcV$sp(ScalatraFilter.scala:71)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:71)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:71)
	at org.scalatra.ScalatraBase$$anonfun$2$$anonfun$apply$4.apply(ScalatraBase.scala:166)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$$anonfun$2.apply(ScalatraBase.scala:166)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:165)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:193)
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:27)
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply$mcV$sp(flashMap.scala:162)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.F...
```

**Comment by tanacasino** [comment]
I could reproduce this bug. 
TableToken header size and align size mismatch.

https://github.com/gitbucket/markedj issue.

test case

```markdown
| Tables   |      Are      |  Cool |
|:----------|:-------------:|
| col 1 is   |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |
```

GitHub shows text.

| Tables   |      Are      |  Cool |
|:----------|:-------------:|
| col 1 is   |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |
