### ISSUE TITLE
NullPointerException when sending notification

### ISSUE THREAD

**Issue by jvamvas** [gitbucket/gitbucket#1060]
Once in a while, sending notifications throws a `java.lang.NullPointerException`. As far as I can tell, there are no identifiable patterns. The error seems to occur at random.

```
Jan 15 05:07:44 gitbucket su[4410]: Jan 15, 2016 5:07:44 AM gitbucket.core.util.Mailer$$anonfun$toNotify$2 applyOrElse
Jan 15 05:07:44 gitbucket su[4410]: SEVERE: Notifications Failed.
Jan 15 05:07:44 gitbucket su[4410]: java.lang.NullPointerException
Jan 15 05:07:45 gitbucket su[4410]: Jan 15, 2016 5:07:45 AM org.apache.sshd.server.session.ServerSession <init>
Jan 15 05:07:45 gitbucket su[4410]: INFO: Server session created from /5.148.180.6:51043
```

**Comment by takezoe** [comment]
@jvamvas Can you find stacktrace which point a line number of the place where `NullPointerException` is caused in your GitBucket log?

**Comment by jvamvas** [comment]
@takezoe Unfortunately, I do not have a more detailed stacktrace. I am aware that this makes it rather difficult to resolve this bug.

**Comment by mitsuba-clover** [comment]
I'm suffering the same issue. Fortunately I found its stacktrace in `/var/log/gitbucket/run.log`. Hope this helps.

```
5 16, 2016 12:48:03 午後 gitbucket.core.util.Mailer$$anonfun$toNotify$2 applyOrElse
重大: Notifications Failed.
java.sql.SQLException: You can't operate on a closed Connection!!!
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:394)
	at scala.slick.jdbc.JdbcBackend$SessionDef$class.prepareStatement(JdbcBackend.scala:152)
	at scala.slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:389)
	at scala.slick.jdbc.StatementInvoker.results(StatementInvoker.scala:32)
	at scala.slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
	at scala.slick.jdbc.Invoker$class.foreach(Invoker.scala:64)
	at scala.slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
	at scala.slick.jdbc.Invoker$class.firstOption(Invoker.scala:29)
	at scala.slick.jdbc.StatementInvoker.firstOption(StatementInvoker.scala:16)
	at gitbucket.core.service.IssuesService$class.getIssue(IssuesService.scala:22)
	at gitbucket.core.view.Markdown$GitBucketMarkedRenderer.gitbucket$core$service$RequestCache$$super$getIssue(Markdown.scala:53)
	at gitbucket.core.service.RequestCache$class.gitbucket$core$service$RequestCache$class$$$anonfun$1(RequestCache.scala:21)
	at gitbucket.core.service.RequestCache$class$$Lambda$541/2005795451.apply(Unknown Source)
	at gitbucket.core.controller.Context.gitbucket$core$controller$Context$$$anonfun$15(ControllerBase.scala:204)
	at gitbucket.core.controller.Context$$Lambda$307/592007298.apply(Unknown Source)
	at scala.Option.getOrElse(Option.scala:121)
	at gitbucket.core.controller.Context.gitbucket$core$controller$Context$$$anonfun$14(ControllerBase.scala:203)
	at gitbucket.core.controller.Context$$Lambda$306/2041946220.apply(Unknown Source)
	at gitbucket.core.util.ControlUtil$.defining(ControlUtil.scala:12)
	at gitbucket.core.controller.Context.cache(ControllerBase.scala:202)
	at gitbucket.core.service.RequestCache$class.getIssue(RequestCache.scala:21)
	at gitbucket.core.view.Markdown$GitBucketMarkedRenderer.getIssue(Markdown.scala:53)
	at gitbucket.core.view.LinkConverter$class.gitbucket$core$view$LinkConverter$class$$$anonfun$7(LinkConverter.scala:78)
	at gitbucket.core.view.LinkConverter$class$$Lambda$540/580567125.apply(Unknown Source)
	at gitbucket.core.util.Implicits$RichString.gitbucket$core$util$Implicits$RichString$$$anonfun$2(Implicits.scala:48)
	at gitbucket.core.util.Implicits$RichString$$Lambda$536/808609181.apply(Unknown Source)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at gitbucket.core.util.Implicits$RichString.replaceBy(Implicits.scala:45)
	at gitbucket.core.view.LinkConverter$class.convertRefsLinks(LinkConverter.scala:76)
	at gitbucket.core.view.Markdown$GitBucketMarkedRenderer.convertRefsLinks(Markdown.scala:53)
	at gitbucket.core.view.Markdown$GitBucketMarkedRenderer.text(Markdown.scala:111)
	at io.github.gitbucket.markedj.InlineLexer.output(InlineLexer.java:190)
	at io.github.gitbucket.markedj.Parser.tok(Parser.java:158)
	at io.github.gitbucket.markedj.Parser.tok(Parser.java:106)
	at io.github.gitbucket.markedj.Parser.parse(Parser.java:35)
	at io.github.gitbucket.markedj.Marked.marked(Marked.java:18)
	at gitbucket.core.view.Markdown$.toHtml(Markdown.scala:47)
	at gitbucket.core.util.Mailer.gitbucket$core$util$Mailer$$$anonfun$12(Notifier.scala:78)
	at gitbucket.core.util.Mailer.gitbucket$core$util$Mailer$$$anonfun$12$adapted(Notifier.scala:75)
	at gitbucket.core.util.Mailer$$Lambda$626/247113493.apply(Unknown Source)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
	at gitbucket.core.util.Mailer.gitbucket$core$util$Mailer$$$anonfun$11(Notifier.scala:75)
	at gitbucket.core.util.Mailer$$Lambda$625/377007252.apply(Unknown Source)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException
```

**Comment by swaldman** [comment]
The "caused by" Exception in this stack trace is misleading. The top-line message explains the problem. The application is trying to use a Connection (that is really a `c3p0` proxy of a Connection) that has already been closed (so the inner physical Connection is now null). I'm sorry I don't understand the database access path here well enough to help track this down, but basically it's a matter of figuring out how the Connection you are working with might sometimes have already has `close()` called on it.

**Comment by m-shibata** [comment]
I can reproduce the issue.

* Deploy GitBucket 4.4
* Start with logback-settings.xml of [Tracing & logging](https://github.com/gitbucket/gitbucket/wiki/Tracing-%26-logging)
* Settings SMTP and enable notification from system settings
* Create two accounts with mail address (ex. foo and bar)
* Create new repository by foo and Add bar to collaborator
* Create new issue by foo
* foo comment the issue: "@bar test"
* Occur "Notifications Failed."

It seems that Slick 2.1.0 in build.sbt doesn't support async interface. It's supported from 3.0.0.

https://github.com/slick/slick/issues/44

However src/main/scala/gitbucket/core/util/Notifier.scala uses "Future". I'm sorry I don't understand about scala and the "Future" trait, but using Future could be problem?

https://github.com/gitbucket/gitbucket/blob/master/src/main/scala/gitbucket/core/util/Notifier.scala#L74

```
    val f = Future {
      database withSession { implicit session =>
        defining(
          s"[${r.name}] ${issue.title} (#${issue.issueId})" ->
            msg(Markdown.toHtml(
              markdown         = content,
              repository       = r,
              enableWikiLink   = false,
              enableRefsLink   = true,
              enableAnchor     = false,
              enableLineBreaks = false
            ))) { case (subject, msg) =>
            recipients(issue) { to =>
              send(to, subject, msg)
            }
        }
      }
      "Notifications Successful."
    }
    f onSuccess {
      case s => logger.debug(s)
    }
    f onFailure {
      case t => logger.error("Notifications Failed.", t)
    }
```

With some test, session will be closed before Markdown.toHtml is finished. Timing of close depends machine spec. If enable debug mode, toHtml() is more time-consuming, therefore this issue more reproducible.
