### ISSUE TITLE
could not start version 3.11

### ISSUE THREAD

**Issue by qingliangcn** [gitbucket/gitbucket#1094]
error msg:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/eclipse/jetty/server/Handler : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2442)
        at java.lang.Class.getMethod0(Class.java:2685)
        at java.lang.Class.getMethod(Class.java:1620)
        at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:488)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:480)
```
java: 1.7.0_03
system: centos 6.5

**Comment by McFoggy** [comment]
Please follow project rules as defined on the [main page](https://github.com/gitbucket/gitbucket), support questions have to go to [gitter](https://gitter.im/gitbucket/gitbucket?utm_source=share-link&utm_medium=link&utm_campaign=share-link) and you could have also used search capability to discover that others already asked the exact same question.

Gitbucket 3.11 requires Java 8 to work.

**Comment by qingliangcn** [comment]
sorry for my action. by the way, i think the release note should mention that.  :)
