### ISSUE TITLE
cannot disable the user

### ISSUE THREAD

**Issue by c-yan** [gitbucket/gitbucket#1129]
## Issue
**Impacted version**: 3.12

**Deployment mode**: Windows Server 2012 R2 + Apache 2.4.16 + JDK 8u60 + Tomcat 8.0.32

**Problem description**:

To disable the user, i get a exception, such as the following

org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: "IDX_ISSUE_ID_FK1: PUBLIC.ISSUE_ID FOREIGN KEY(USER_NAME, REPOSITORY_NAME) REFERENCES PUBLIC.REPOSITORY(USER_NAME, REPOSITORY_NAME) ('UserName', 'ProjectName')"; SQL statement:
delete from "REPOSITORY" where "REPOSITORY"."USER_NAME" = ? [23503-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:426)
	at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:443)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:318)
	at org.h2.table.Table.fireConstraints(Table.java:932)
	at org.h2.table.Table.fireAfterRow(Table.java:950)
	at org.h2.command.dml.Delete.update(Delete.java:100)
	at org.h2.command.CommandContainer.update(CommandContainer.java:78)
	at org.h2.command.Command.executeUpdate(Command.java:253)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:157)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:143)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:384)
	at scala.slick.driver.JdbcInvokerComponent$DeleteInvoker$$anonfun$delete$1.apply(JdbcInvokerComponent.scala:67)
	at scala.slick.driver.JdbcInvokerComponent$DeleteInvoker$$anonfun$delete$1.apply(JdbcInvokerComponent.scala:65)
	at scala.slick.jdbc.JdbcBackend$SessionDef$class.withPreparedStatement(JdbcBackend.scala:191)
	at scala.slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:389)
	at scala.slick.driver.JdbcInvokerComponent$DeleteInvoker.delete(JdbcInvokerComponent.scala:65)
	at gitbucket.core.service.AccountService$class.removeUserRelatedData(AccountService.scala:178)
	at gitbucket.core.controller.UserManagementController.removeUserRelatedData(UserManagementController.scala:14)
	at gitbucket.core.controller.UserManagementControllerBase$$anonfun$12$$anonfun$apply$4.apply(UserManagementController.scala:110)
	at gitbucket.core.controller.UserManagementControllerBase$$anonfun$12$$anonfun$apply$4.apply(UserManagementController.scala:99)
	at scala.Option.map(Option.scala:146)
	at gitbucket.core.controller.UserManagementControllerBase$$anonfun$12.apply(UserManagementController.scala:99)
	at gitbucket.core.controller.UserManagementControllerBase$$anonfun$12.apply(UserManagementController.scala:97)
	at gitbucket.core.util.AdminAuthenticator$$anonfun$adminOnly$1$$anonfun$apply$7.apply(Authenticator.scala:76)
	at gitbucket.core.util.AdminAuthenticator$class.gitbucket$core$util$AdminAuthenticator$$authenticate(Authenticator.scala:81)
	at gitbucket.core.util.AdminAuthenticator$$anonfun$adminOnly$1.apply(Authenticator.scala:76)
	at io.github.gitbucket.scalatra.forms.ClientSideValidationFormSupport$$anonfun$post$1$$anonfun$apply$2.apply(ClientSideValidationFormSupport.scala:26)
	at io.github.gitbucket.scalatra.forms.package$.withValidation(package.scala:21)
	at io.github.gitbucket.scalatra.forms.ClientSideValidationFormSupport$$anonfun$post$1.apply(ClientSideValidationFormSupport.scala:25)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$liftAction(ScalatraBase.scala:285)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:279)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:279)
	at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:189)
	at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.invoke(ScalatraBase.scala:278)
	at gitbucket.core.controller.ControllerBase.org$scalatra$json$JsonSupport$$super$invoke(ControllerBase.scala:27)
	at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:88)
	at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:82)
	at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:189)
	at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:27)
	at org.scalatra.json.JsonSupport$class.invoke(JsonSupport.scala:82)
	at gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:253)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:251)
	at scala.Option.flatMap(Option.scala:171)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:251)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:250)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:493)
	at org.scalatra.ScalatraBase$class.runRoutes(ScalatraBase.scala:250)
	at gitbucket.core.controller.ControllerBase.runRoutes(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:205)
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:187)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:78)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:58)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:57)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:125)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:27)
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:53)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply$mcV$sp(flashMap.scala:170)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:145)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:145)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$class.handle(flashMap.scala:145)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:27)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:37)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:37)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:37)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:36)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply$mcV$sp(ScalatraFilter.scala:74)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:74)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:74)
	at org.scalatra.ScalatraBase$$anonfun$2$$anonfun$apply$4.apply(ScalatraBase.scala:178)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$$anonfun$2.apply(ScalatraBase.scala:178)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:177)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:205)
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:187)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:78)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:58)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:57)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:125)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:27)
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:53)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply$mcV$sp(flashMap.scala:170)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:145)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:145)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$class.handle(flashMap.scala:145)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:27)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:37)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:37)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:37)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:36)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply$mcV$sp(ScalatraFilter.scala:74)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:74)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:74)
	at org.scalatra.ScalatraBase$$anonfun$2$$anonfun$apply$4.apply(ScalatraBase.scala:178)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$$anonfun$2.apply(ScalatraBase.scala:178)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:177)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:205)
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:187)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:78)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:58)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:57)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:125)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:27)
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:53)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply$mcV$sp(flashMap.scala:170)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:145)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:145)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$class.handle(flashMap.scala:145)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:27)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:37)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:37)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:37)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:36)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply$mcV$sp(ScalatraFilter.scala:74)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:74)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:74)
	at org.scalatra.ScalatraBase$$anonfun$2$$anonfun$apply$4.apply(ScalatraBase.scala:178)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$$anonfun$2.apply(ScalatraBase.scala:178)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:177)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:205)
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:187)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:78)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:58)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:57)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:27)
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:125)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:27)
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:53)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply$mcV$sp(flashMap.scala:170)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:145)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:145)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
	at org.scalatra.FlashMapSupport$class.handle(flashMap.scala:145)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:27)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:37)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:37)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:37)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:36)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at gitbucket.core.servlet.TransactionFilter$$anonfun$doFilter$1.apply(TransactionFilter.scala:37)
	at gitbucket.core.servlet.TransactionFilter$$anonfun$doFilter$1.apply(TransactionFilter.scala:28)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withTransaction(JdbcBackend.scala:46)
	at gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:28)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:868)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by bsv798** [comment]
Exactly the same issue at version 4.3.0.
When you try to disable the user that have some repos in his folder (own or forked) you got the above exception. When you delete (transfer ownership) all user's repos then disabling goes fine.
