### ISSUE TITLE
404 after update from 3.10 to newer

### ISSUE THREAD

**Issue by extreme-dh** [gitbucket/gitbucket#1155]
Got 404 error after unpacking of war file on Windows IIS & HeliconZoo (jetty)
Anyone knows why or how to fix?

**Comment by jgetrost** [comment]
I am also having an issue updating on my Ubuntu LTS/Tomcat. Previous updates were very simple. I would just replace the .war and restart if needed. This may be a tomcat error, but nothing has changed with my environment since first using gitbucket at version 3.7.

Here is some information from the logs:

```
22-Mar-2016 22:18:25.658 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener $
 java.lang.UnsupportedClassVersionError: com/typesafe/config/Config : Unsupported major.minor version 52.0 (unable to load class com.typesafe.config.Config)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2500)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:860)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1302)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:191)
        at com.mchange.v2.cfg.BasicMultiPropertiesConfig.configSource(BasicMultiPropertiesConfig.java:77)
        at com.mchange.v2.cfg.BasicMultiPropertiesConfig.firstInit(BasicMultiPropertiesConfig.java:184)
        at com.mchange.v2.cfg.BasicMultiPropertiesConfig.<init>(BasicMultiPropertiesConfig.java:110)
        at com.mchange.v2.cfg.ConfigUtils.read(ConfigUtils.java:63)
        at com.mchange.v2.cfg.ConfigUtils.readVmConfig(ConfigUtils.java:115)
        at com.mchange.v2.cfg.MLogConfigSource.readVmConfig(MLogConfigSource.java:46)
        at com.mchange.v2.log.MLogConfig.refresh(MLogConfig.java:59)
        at com.mchange.v2.log.MLog.refreshConfig(MLog.java:59)
        at com.mchange.v2.log.MLog.<clinit>(MLog.java:51)
        at com.mchange.v2.naming.JavaBeanReferenceMaker.<clinit>(JavaBeanReferenceMaker.java:51)
        at com.mchange.v2.c3p0.impl.PoolBackedDataSourceBase.<clinit>(PoolBackedDataSourceBase.java:263)
        at gitbucket.core.servlet.Database$.<init>(TransactionFilter.scala:50)
        at gitbucket.core.servlet.Database$.<clinit>(TransactionFilter.scala)
        at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:30)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4738)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5181)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1798)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

22-Mar-2016 22:18:26.648 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStop Exception sending context destroyed event to listener ins$
 java.lang.NoClassDefFoundError: Could not initialize class gitbucket.core.servlet.Database$
        at ScalatraBootstrap.destroy(ScalatraBootstrap.scala:51)
        at org.scalatra.servlet.ScalatraListener.contextDestroyed(ScalatraListener.scala:33)
        at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4785)
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5404)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:160)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1798)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
22-Mar-2016 22:18:26.650 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStop Exception sending context destroyed event to listener ins$
 java.lang.NoClassDefFoundError: Could not initialize class gitbucket.core.servlet.Database$
        at gitbucket.core.servlet.InitializeListener.contextDestroyed(InitializeListener.scala:67)
        at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4785)
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5404)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:160)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1798)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

22-Mar-2016 22:18:27.562 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
22-Mar-2016 22:18:27.564 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()


```

**Comment by McFoggy** [comment]
@jgetrost are you sure that you are using Java 8?

**Comment by jgetrost** [comment]
I updated to Java 8. Catalina was not picking it up. I had to manually set the JRE_HOME and JAVA_HOME using a setenv.sh in the tomcat/bin folder.
