### ISSUE TITLE
Unable to close a database, get Illegal State Exception  Version 1.4.191

### ISSUE THREAD

**Issue by bmason42** [gitbucket/gitbucket#1165]
I havea DB file , that I open in embedded mode, do a select and close the connection.
The results all look good, but when I close the connection I get an error:
Caused by: java.lang.IllegalStateException: Reading from cache:nio:maindb.mv.db failed; file length 46546944 read length 1024 at 46638417 [1.4.191/1]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:443)
	at org.h2.mvstore.FileStore.readFully(FileStore.java:98)
	at org.h2.mvstore.Page.read(Page.java:190)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:1939)
	at org.h2.mvstore.MVMap.readPage(MVMap.java:736)
	at org.h2.mvstore.Page.getChildPage(Page.java:217)
	at org.h2.mvstore.MVMap.binarySearch(MVMap.java:468)
	at org.h2.mvstore.MVMap.binarySearch(MVMap.java:469)
	at org.h2.mvstore.MVMap.get(MVMap.java:450)
	at org.h2.mvstore.MVMap.remove(MVMap.java:538)
	at org.h2.store.LobStorageMap.removeLob(LobStorageMap.java:355)
	at org.h2.store.LobStorageMap.removeAllForTable(LobStorageMap.java:328)
	at org.h2.store.LobStorageMap.removeAllForTable(LobStorageMap.java:332)
	at org.h2.engine.Database.removeOrphanedLobs(Database.java:1329)
	at org.h2.engine.Database.close(Database.java:1250)
	at org.h2.engine.Database.removeSession(Database.java:1170)
	at org.h2.engine.Session.close(Session.java:815)
	at org.h2.jdbc.JdbcConnection.close(JdbcConnection.java:383)
	... 30 more
Caused by: java.io.EOFException
	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:431)
	... 47 more
### Before submitting an issue to Gitbucket I have first:

-

## Issue
**Impacted version**: 1.4.191"

**Deployment mode**: *embedded in my own application, using embedded URL

**Comment by McFoggy** [comment]
What are you doing in gitbucket to make that happen?

**Comment by bmason42** [comment]
McFoggy, your comment makes me think I filed this in a wrong forum.  I am looking for support on H2

**Comment by McFoggy** [comment]
@bmason42 closing issue as unrelated to gitbucket project
