### ISSUE TITLE
failure with webhook without security token

### ISSUE THREAD

**Issue by McFoggy** [gitbucket/gitbucket#1168]
## Issue
**Impacted version**: 3.13

**Deployment mode**: not relevant

**Problem description**:
Setting a webhook without security token, make the webhook not testable directly in the UI.
The webhook works for normal events (like push) but cannot be tested via the test button.

In app we received the following error
![image](https://cloud.githubusercontent.com/assets/1119660/14389381/b3693ed0-fdb2-11e5-8dd1-f0cd4362b360.png)

and in traces we see
```
17:48:16.696 [ForkJoinPool-2-worker-3] ERROR g.core.service.WebHookService - Failed: web hook request to http://docker:8090
java.lang.IllegalArgumentException: Empty key
        at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:96) ~[na:1.8.0_71]
        at fr.brouillard.oss.security.xhub.XHub.generateXHubToken(XHub.java:83) ~[xhub4j-core-1.0.0.jar:1.0.0]
        at fr.brouillard.oss.security.xhub.XHub.generateHeaderXHubToken(XHub.java:76) ~[xhub4j-core-1.0.0.jar:1.0.0]
        at gitbucket.core.service.WebHookService$class.gitbucket$core$service$WebHookService$class$$$anonfun$26(WebHookService.scala:115) ~[gitbucket_                                             2.11-3.13.0.jar:3.13.0]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.8.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.8.jar:na]
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) ~[scala-library-2.11.8.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.8.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.8.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.8.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.8.jar:na]
```

**Comment by McFoggy** [comment]
filling the security token make the webhook testable again

**Comment by McFoggy** [comment]
issue still exist in master 437f944 and is reproducable with JSON webhooks.

The above fix was done only for FORM, not for JSON.

```
10:37:17.950 [ForkJoinPool-2-worker-3] ERROR g.core.service.WebHookService - Failed: web hook request to http://requestb.in/rs5tdxrs
java.lang.IllegalArgumentException: Empty key
        at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:96)
        at fr.brouillard.oss.security.xhub.XHub.generateXHubToken(XHub.java:83)
        at fr.brouillard.oss.security.xhub.XHub.generateHeaderXHubToken(XHub.java:76)
        at gitbucket.core.service.WebHookService$class.gitbucket$core$service$WebHookService$class$$$anonfun$26(WebHookService.scala:123)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info] Compiling 1 Scala source to D:\dev\projects\oss\gitbucket\gitbucket-app\target\scala-2.11\classes...
[info] Packaging D:\dev\projects\oss\gitbucket\gitbucket-app\target\scala-2.11\gitbucket_2.11-4.1.0.jar ...
```
