### ISSUE TITLE
Cannot start GitBucket in Tomcat7

### ISSUE THREAD

**Issue by thomas2d19** [gitbucket/gitbucket#1184]
## Issue
**Impacted version**: 4.0

**Deployment mode**: Tomcat7 on Synology NAS (armv7l), Java 8 update 77

**Problem description**:  
GitBucket deploys normally but then prompt a message saying that GitBucket could not be started. Here is the error log from Tomcat7:  
```
May 04, 2016 7:04:59 PM org.apache.catalina.core.StandardContext listenerStop
SEVERE: Exception sending context destroyed event to listener instance of class gitbucket.core.servlet.InitializeListener
java.lang.NoClassDefFoundError: Could not initialize class gitbucket.core.servlet.Database$
	at gitbucket.core.servlet.InitializeListener.contextDestroyed(InitializeListener.scala:108)
	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:5063)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5723)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:160)
	at org.apache.catalina.manager.ManagerServlet.start(ManagerServlet.java:1322)
	at org.apache.catalina.manager.HTMLManagerServlet.start(HTMLManagerServlet.java:694)
	at org.apache.catalina.manager.HTMLManagerServlet.doPost(HTMLManagerServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:213)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by takezoe** [comment]
@thomas2d19 Was this exception caused in the clean installation? or updated?

**Comment by thomas2d19** [comment]
@takezoe Clean installation.

**Comment by takezoe** [comment]
@thomas2d19 OK, I expect that you had got another exception before this exception because this exception is caused in shutting down by the original exception. I have to confirm the original exception which made startup failed. Could you check again?

**Comment by thomas2d19** [comment]
Yes before it there is another exception.
```
May 07, 2016 8:47:37 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class gitbucket.core.servlet.InitializeListener
java.lang.ExceptionInInitializerError
        at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:36)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5528)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.manager.ManagerServlet.start(ManagerServlet.java:1322)
        at org.apache.catalina.manager.HTMLManagerServlet.start(HTMLManagerServlet.java:694)
        at org.apache.catalina.manager.HTMLManagerServlet.doPost(HTMLManagerServlet.java:217)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:213)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'db'
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
        at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:145)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:172)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
        at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:246)
        at gitbucket.core.util.DatabaseConfig$.dbUrl$lzycompute(DatabaseConfig.scala:26)
        at gitbucket.core.util.DatabaseConfig$.dbUrl(DatabaseConfig.scala:26)
        at gitbucket.core.util.DatabaseConfig$.url(DatabaseConfig.scala:29)
        at gitbucket.core.util.DatabaseConfig$.url$lzycompute(DatabaseConfig.scala:31)
        at gitbucket.core.util.DatabaseConfig$.url(DatabaseConfig.scala:31)
        at gitbucket.core.util.DatabaseConfig$.jdbcDriver$lzycompute(DatabaseConfig.scala:34)
        at gitbucket.core.util.DatabaseConfig$.jdbcDriver(DatabaseConfig.scala:34)
        at gitbucket.core.servlet.Database$.<init>(TransactionFilter.scala:51)
        at gitbucket.core.servlet.Database$.<clinit>(TransactionFilter.scala)
        ... 35 more

May 07, 2016 8:47:41 PM org.apache.catalina.core.StandardContext listenerStop
SEVERE: Exception sending context destroyed event to listener instance of class org.scalatra.servlet.ScalatraListener
java.lang.NoClassDefFoundError: Could not initialize class gitbucket.core.servlet.Database$
        at ScalatraBootstrap.destroy(ScalatraBootstrap.scala:51)
        at org.scalatra.servlet.ScalatraListener.contextDestroyed(ScalatraListener.scala:33)
        at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:5063)
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5723)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:160)
        at org.apache.catalina.manager.ManagerServlet.start(ManagerServlet.java:1322)
        at org.apache.catalina.manager.HTMLManagerServlet.start(HTMLManagerServlet.java:694)
        at org.apache.catalina.manager.HTMLManagerServlet.doPost(HTMLManagerServlet.java:217)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:213)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by thomas2d19** [comment]
Yes, there are two more errors before this error occurs.  
I post the complete log here.
[localhost.txt](https://github.com/gitbucket/gitbucket/files/253421/localhost.txt)

**Comment by takezoe** [comment]
@thomas2d19 Thanks. Check `GITBUCKET_HOME/database.conf` please. It should have been created with following content by GitBucket automatically:
 ```
db {
  url = "jdbc:h2:${DatabaseHome};MVCC=true"
  user = "sa"
  password = "sa"
}
```
If you can not find this file, try to create it by your hand.

**Comment by thomas2d19** [comment]
@takezoe This time one more error is thrown by Tomcat after adding `database.conf` file.
```
May 08, 2016 11:33:21 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class gitbucket.core.servlet.InitializeListener
java.lang.ExceptionInInitializerError
	at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:36)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5528)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.startup.HostConfig.reload(HostConfig.java:1533)
	at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1497)
	at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1695)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:333)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1374)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1546)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1556)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1524)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'db.url'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:246)
	at gitbucket.core.util.DatabaseConfig$.dbUrl$lzycompute(DatabaseConfig.scala:26)
	at gitbucket.core.util.DatabaseConfig$.dbUrl(DatabaseConfig.scala:26)
	at gitbucket.core.util.DatabaseConfig$.url(DatabaseConfig.scala:29)
	at gitbucket.core.util.DatabaseConfig$.url$lzycompute(DatabaseConfig.scala:31)
	at gitbucket.core.util.DatabaseConfig$.url(DatabaseConfig.scala:31)
	at gitbucket.core.util.DatabaseConfig$.jdbcDriver$lzycompute(DatabaseConfig.scala:34)
	at gitbucket.core.util.DatabaseConfig$.jdbcDriver(DatabaseConfig.scala:34)
	at gitbucket.core.servlet.Database$.<init>(TransactionFilter.scala:51)
	at gitbucket.core.servlet.Database$.<clinit>(TransactionFilter.scala)
	... 15 more
```
However, `java.lang.NoClassDefFoundError` still occurs,
```
May 08, 2016 11:33:25 AM org.apache.catalina.core.StandardContext listenerStop
SEVERE: Exception sending context destroyed event to listener instance of class org.scalatra.servlet.ScalatraListener
java.lang.NoClassDefFoundError: Could not initialize class gitbucket.core.servlet.Database$
	at ScalatraBootstrap.destroy(ScalatraBootstrap.scala:51)
	at org.scalatra.servlet.ScalatraListener.contextDestroyed(ScalatraListener.scala:33)
	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:5063)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5723)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:160)
	at org.apache.catalina.startup.HostConfig.reload(HostConfig.java:1533)
	at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1497)
	at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1695)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:333)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1374)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1546)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1556)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1524)
	at java.lang.Thread.run(Thread.java:745)

May 08, 2016 11:33:25 AM org.apache.catalina.core.StandardContext listenerStop
SEVERE: Exception sending context destroyed event to listener instance of class gitbucket.core.servlet.InitializeListener
java.lang.NoClassDefFoundError: Could not initialize class gitbucket.core.servlet.Database$
	at gitbucket.core.servlet.InitializeListener.contextDestroyed(InitializeListener.scala:108)
	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:5063)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5723)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:160)
	at org.apache.catalina.startup.HostConfig.reload(HostConfig.java:1533)
	at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1497)
	at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1695)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:333)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1374)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1546)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1556)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1524)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by takezoe** [comment]
@thomas2d19 What user are you using to run Tomcat? Is that user can read and write `GITBUCKET_HOME`? If you are using the OS provided package for Tomcat, maybe you should confirm the permission of the directory.

**Comment by thomas2d19** [comment]
@takezoe I really make sure the Tomcat user can write the folders and files. GitBucket works fine for version 3.14.
