### ISSUE TITLE
problem starting 4.0 pointing to a galera mysql cluster

### ISSUE THREAD

**Issue by dariko** [gitbucket/gitbucket#1187]
## Issue
**Impacted version**: 4.0

**Deployment mode**: docker container

**Problem description**: 

#### short version

trying to access a gitbucket 4.0 instance pointing to a galera mysql cluster returns `503`

#### long version

I tried to migrate my gitbucket 4.0 installation to a mysql galera database.
- exported everything in settings/export to `${FILE}`
- created a database:
```
CREATE DATABASE IF NOT EXISTS gitbucket CHARACTER SET = 'utf8';
GRANT ALL ON gitbucket.* TO 'gitbucket'@'%' IDENTIFIED BY 'secret'
```
- stopped gitbucket
- modified `${GITBUCKET_HOME}/database.conf`
```
db {
  url = "jdbc:mysql://rr.dari.co:3306/gitbucket"
  user = "gitbucket"
  password = "secret"
}
```
- restart gitbucket

In the logs I got a warning about a subquery contained in a from clause:
```
2016-05-06 09:29:14.632:INFO::main: Logging initialized @1041ms
2016-05-06 09:29:22.230:INFO:oejs.Server:main: jetty-9.3.z-SNAPSHOT
2016-05-06 09:30:22.322:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/gitbucket/tmp/webapp/WEB-INF/lib/logback-classic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/gitbucket/tmp/webapp/WEB-INF/lib/slf4j-jdk14-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
09:30:25.424 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
09:30:26.456 [main] INFO  g.core.servlet.InitializeListener - Start schema update
2016-05-06 09:30:39.518:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@4a951911{/,file:///gitbucket/tmp/webapp/,STARTING}{file:/opt/gitbucket.war}
java.sql.SQLException: View's SELECT contains a subquery in the FROM clause
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at io.github.gitbucket.solidbase.migration.MigrationUtils.updateDatabase(MigrationUtils.java:20)
	at io.github.gitbucket.solidbase.migration.SqlMigration.migrate(SqlMigration.java:70)
	at io.github.gitbucket.solidbase.migration.SqlMigration.migrate(SqlMigration.java:42)
	at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:45)
	at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:29)
	at gitbucket.core.servlet.InitializeListener.gitbucket$core$servlet$InitializeListener$$$anonfun$1(InitializeListener.scala:78)
	at gitbucket.core.servlet.InitializeListener.gitbucket$core$servlet$InitializeListener$$$anonfun$1$adapted(InitializeListener.scala:36)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withTransaction(JdbcBackend.scala:46)
	at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:36)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:835)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:530)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:808)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:342)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1379)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1341)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:259)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:517)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:405)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at JettyLauncher.main(JettyLauncher.java:64)
2016-05-06 09:30:39.614:INFO:oejs.ServerConnector:main: Started ServerConnector@590f4833{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2016-05-06 09:30:39.615:INFO:oejs.Server:main: Started @86067ms
```

but accessing the interface give me a `503`:
```
# curl 172.17.0.10:8080
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 503 </title>
</head>
<body>
<h2>HTTP ERROR: 503</h2>
<p>Problem accessing /. Reason:
<pre>    Service Unavailable</pre></p>
<hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.z-SNAPSHOT</a><hr/>
</body>
</html>
```

**Comment by dariko** [comment]
Ok, now I have some more informations:
As per [mysql docs](http://dev.mysql.com/doc/refman/5.7/en/create-view.html):
> Before MySQL 5.7.7, the SELECT statement cannot contain a subquery in the FROM clause.`

And I am using a cluster of mariadb 10.1 which [still has not implemented this feature](https://mariadb.atlassian.net/browse/MDEV-3944).

I'm changing this issue title accordingly

**Comment by dariko** [comment]
I managed to get it working:
after the failed start I manually created 3 views splitting the ISSUE_OUTLINE_VIEW subqueries in separate views:
```
CREATE OR REPLACE VIEW ISSUE_OUTLINE_VIEW_SUB1 AS
 SELECT
  USER_NAME,
  REPOSITORY_NAME,
  ISSUE_ID,
  COUNT(COMMENT_ID) AS COMMENT_COUNT
 FROM
  ISSUE_COMMENT
 WHERE
  ACTION IN ('comment', 'close_comment', 'reopen_comment')
 GROUP BY
  USER_NAME,
  REPOSITORY_NAME,
  ISSUE_ID;

CREATE OR REPLACE VIEW ISSUE_OUTLINE_VIEW_SUB2 AS
 SELECT
  USER_NAME,
  REPOSITORY_NAME,
  ISSUE_ID,
  COUNT(COMMENT_ID) AS COMMENT_COUNT
 FROM
  COMMIT_COMMENT
 GROUP BY
  USER_NAME,
  REPOSITORY_NAME,
  ISSUE_ID;

CREATE OR REPLACE VIEW ISSUE_OUTLINE_VIEW AS
 SELECT
   A.USER_NAME,
   A.REPOSITORY_NAME,
   A.ISSUE_ID,
   COALESCE(B.COMMENT_COUNT, 0) + COALESCE(C.COMMENT_COUNT, 0) AS COMMENT_COUNT
 FROM ISSUE A
 LEFT OUTER JOIN ISSUE_OUTLINE_VIEW_SUB1 B
 ON (A.USER_NAME = B.USER_NAME AND A.REPOSITORY_NAME = B.REPOSITORY_NAME AND A.ISSUE_ID = B.ISSUE_ID)
 LEFT OUTER JOIN ISSUE_OUTLINE_VIEW_SUB2 C
 ON (A.USER_NAME = C.USER_NAME AND A.REPOSITORY_NAME = C.REPOSITORY_NAME AND A.ISSUE_ID = C.ISSUE_ID);
```
and then copied the lone `gitbucket.version` record from a working install (mysql 5.7.12)
```
insert into VERSIONS(MODULE_ID,VERSION) VALUES ('gitbucket-core','4.0.0');
```

gitbucket now starts and is accessible as default user.

**Comment by msigley** [comment]
Updated link to MariaDB feature request:
https://jira.mariadb.org/browse/MDEV-3944

**Comment by gabrielrota** [comment]
-- java.sql.SQLSyntaxErrorException: (conn=52468) Unknown column 's47.PRIORITY' in 'field list'
-- Workaround for old MariaDB < 10.2.1 and gitbucket-core 4.20.0

CREATE OR REPLACE VIEW ISSUE_OUTLINE_VIEW AS
 SELECT
   A.USER_NAME,
   A.REPOSITORY_NAME,
   A.ISSUE_ID,
   COALESCE(B.COMMENT_COUNT, 0) + COALESCE(C.COMMENT_COUNT, 0) AS COMMENT_COUNT,
   COALESCE(D.ORDERING, 9999) AS PRIORITY
 FROM ISSUE A
 LEFT OUTER JOIN ISSUE_OUTLINE_VIEW_SUB1 B
 ON (A.USER_NAME = B.USER_NAME AND A.REPOSITORY_NAME = B.REPOSITORY_NAME AND A.ISSUE_ID = B.ISSUE_ID)
 LEFT OUTER JOIN ISSUE_OUTLINE_VIEW_SUB2 C
 ON (A.USER_NAME = C.USER_NAME AND A.REPOSITORY_NAME = C.REPOSITORY_NAME AND A.ISSUE_ID = C.ISSUE_ID)
 LEFT OUTER JOIN PRIORITY D
 ON (A.PRIORITY_ID = D.PRIORITY_ID) ;
