### ISSUE TITLE
specify port for a standalone app

### ISSUE THREAD

**Issue by HongxuChen** [gitbucket/gitbucket#1193]
**Impacted version**: 4.0

**Deployment mode**: as a standalone app with `java -jar gitbucket.war`, it emits the following error message:

```java
11:55:22.286 [main] INFO  o.quartz.impl.DirectSchedulerFactory - Quartz scheduler 'QuartzScheduler~job
11:55:22.286 [main] INFO  o.quartz.impl.DirectSchedulerFactory - Quartz scheduler version: 2.2.1
11:55:22.287 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler QuartzScheduler~job_$_job started.
[INFO] [05/16/2016 11:55:22.291] [main] [[QuartzScheduler~job]] Setting up scheduled job 'Daily', with 'com.typesafe.akka.extension.quartz.QuartzCronSchedule@79a1728c'
11:55:22.301 [main] INFO  o.scalatra.servlet.ScalatraListener - The cycle class name from the config: ScalatraBootstrap
11:55:22.304 [main] INFO  o.scalatra.servlet.ScalatraListener - Initializing life cycle class: ScalatraBootstrap
2016-05-16 11:55:22.769:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@a0db585{/,file:///home/guest/.gitbucket/tmp/webapp/,AVAILABLE}{file:/home/guest/gitbucket/gitbucket.war}
Exception in thread "main" java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:326)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:244)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:384)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at JettyLauncher.main(JettyLauncher.java:64)
```

Specifying `-Djetty.port=xxx` doesn't work. Alas, I don't know whether configuring gitbucket.conf works.
As of `netstat -tlnp`, I see port 8080 has been used  by another Tomcat app. How can I specify the port?

**Comment by HongxuChen** [comment]
sorry didn't read carefully, solved by specifying "--port=xxx".
