### ISSUE TITLE
http://localhost:8080/gitbucket -> HTTP ERROR: 503 just after fresh install

### ISSUE THREAD

**Issue by aa3Eethi** [gitbucket/gitbucket#1231]
## Issue
**Impacted version**: 4.2.1

**Deployment mode**: standalone app

**Problem description**:
- installation, then opening http://localhost:8080/gitbucket shows error "HTTP ERROR: 503

Problem accessing /gitbucket. Reason:

    Service Unavailable
Powered by Jetty:// 9.3.z-SNAPSHOT"

- to reproduce install debian8, openjdk-8-jre, download gitbucket.war v4.2.1, run java -jar gitbucket.war, then open browser http://localhost:8080/gitbucket
- run log:
$ java -jar gitbucket.war 
2016-07-04 12:57:18.660:INFO::main: Logging initialized @117ms
2016-07-04 12:57:18.769:INFO:oejs.Server:main: jetty-9.3.z-SNAPSHOT
2016-07-04 12:57:19.545:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/user/.gitbucket/tmp/webapp/WEB-INF/lib/slf4j-jdk14-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/user/.gitbucket/tmp/webapp/WEB-INF/lib/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
июл 04, 2016 12:57:19 PM com.zaxxer.hikari.HikariDataSource <init>
INFO: HikariPool-1 - Started.
2016-07-04 12:57:19.926:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@14f232c4{/,file:///home/user/.gitbucket/tmp/webapp/,UNAVAILABLE}{file:/home/user/%d0%97%d0%b0%d0%b3%d1%80%d1%83%d0%b7%d0%ba%d0%b8/gb/gitbucket.war}
org.h2.jdbc.JdbcSQLException: Таблица "VERSIONS" не найдена|Table "VERSIONS" not found; SQL statement:|SELECT VERSION FROM VERSIONS WHERE MODULE_ID = ? [42102-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.readTableOrView(Parser.java:5388)
	at org.h2.command.Parser.readTableFilter(Parser.java:1257)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1896)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2044)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1890)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1711)
	at org.h2.command.Parser.parseSelect(Parser.java:1699)
	at org.h2.command.Parser.parsePrepared(Parser.java:445)
	at org.h2.command.Parser.parse(Parser.java:317)
	at org.h2.command.Parser.parse(Parser.java:289)
	at org.h2.command.Parser.prepareCommand(Parser.java:254)
	at org.h2.engine.Session.prepareLocal(Session.java:560)
	at org.h2.engine.Session.prepareCommand(Session.java:501)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1202)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:290)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:309)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at io.github.gitbucket.solidbase.migration.MigrationUtils.selectStringFromDatabase(MigrationUtils.java:52)
	at io.github.gitbucket.solidbase.manager.JDBCVersionManager.getCurrentVersion(JDBCVersionManager.java:38)
	at gitbucket.core.servlet.InitializeListener.gitbucket$core$servlet$InitializeListener$$$anonfun$1(InitializeListener.scala:77)
	at gitbucket.core.servlet.InitializeListener.gitbucket$core$servlet$InitializeListener$$$anonfun$1$adapted(InitializeListener.scala:36)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withTransaction(JdbcBackend.scala:46)
	at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:36)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:837)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:533)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:810)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:345)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1404)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1366)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:411)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:378)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at JettyLauncher.main(JettyLauncher.java:63)
2016-07-04 12:57:19.936:INFO:oejs.AbstractConnector:main: Started ServerConnector@72ade7e3{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2016-07-04 12:57:19.936:INFO:oejs.Server:main: Started @1397ms

**Comment by takezoe** [comment]
Use 4.2, not 4.2.1 for clean installation.

**Comment by aa3Eethi** [comment]
4.2 looks like at least started...
I have to update installation instructions then, to clarify not to get latest build, but 4.2 for new installations only.

**Comment by VitaliyAT** [comment]
4.14.1 - the same error - 503
