### ISSUE TITLE
timeout on pull request API call

### ISSUE THREAD

**Issue by McFoggy** [gitbucket/gitbucket#1244]
## Issue
**Impacted version**: 3.11

**Deployment mode**: standalone app

**Problem description**:
While trying to use the [github pull request builder](https://github.com/gitbucket/gitbucket/wiki/Setup-Jenkins-GitHub-pull-request-builder-plugin), my jenkins started to show errors 

```
org.jenkinsci.plugins.ghprb.GhprbTrigger.run() failed for hudson.model.FreeStyleProject@5e3bef60[ARCHITECTURE/test-gitbucket-jenkins-jira]
java.lang.Error: org.kohsuke.github.HttpException: Server returned HTTP response code: -1, message: 'null' for URL: http://XXXXXXXXXXXXXXXXXXXXX/api/v3/repos/awxgx/jira-git-demo-01/pulls?state=open
	at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:425)
	at org.kohsuke.github.Requester$PagingIterator.hasNext(Requester.java:392)
	at org.kohsuke.github.PagedIterator.fetch(PagedIterator.java:44)
	at org.kohsuke.github.PagedIterator.hasNext(PagedIterator.java:32)
	at org.kohsuke.github.PagedIterable.asList(PagedIterable.java:42)
	at org.kohsuke.github.GHRepository.getPullRequests(GHRepository.java:627)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:138)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:291)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:273)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:222)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.kohsuke.github.HttpException: Server returned HTTP response code: -1, message: 'null' for URL: http://XXXXXXXXXXXXXXXXXXXXX/api/v3/repos/awxgx/jira-git-demo-01/pulls?state=open
	at org.kohsuke.github.Requester.parse(Requester.java:508)
	at org.kohsuke.github.Requester.access$200(Requester.java:69)
	at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:416)
	... 17 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.kohsuke.github.Requester.parse(Requester.java:486)
	... 19 more
```

I manually tried to call the API with curl without any further success while the API is answering well for example for the `user` endpoint

![image](https://cloud.githubusercontent.com/assets/1119660/16915113/427b2c0e-4cf6-11e6-95bc-bac2a7a5ba4b.png)

**Comment by McFoggy** [comment]
@nazoking same issue with `http://XXXXXXXXXXXXXXXXXXXXX/api/v3/users/Architecture/repos?per_page=0` which is fired by jenkins multibranch pipeline & jenkins github source branch plugin  to fetch repositories from the organization "Architecture" in this example.

```
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Error: org.kohsuke.github.HttpException: Server returned HTTP response code: -1, message: 'null' for URL: http://XXXXXXXXXXXXXXX/api/v3/users/Architecture/repos?per_page=0
	at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:425)
	at org.kohsuke.github.Requester$PagingIterator.hasNext(Requester.java:392)
	at org.kohsuke.github.PagedIterator.fetch(PagedIterator.java:44)
	at org.kohsuke.github.PagedIterator.hasNext(PagedIterator.java:32)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource$DescriptorImpl.doFillRepositoryItems(GitHubSCMSource.java:903)
	... 89 more
Caused by: org.kohsuke.github.HttpException: Server returned HTTP response code: -1, message: 'null' for URL: http://XXXXXXXXXXXXXXX/api/v3/users/Architecture/repos?per_page=0
	at org.kohsuke.github.Requester.parse(Requester.java:508)
	at org.kohsuke.github.Requester.access$200(Requester.java:69)
	at org.kohsuke.github.Requester$PagingIterator.fetch(Requester.java:416)
	... 93 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
	at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:906)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:782)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:444)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:389)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:502)
	at org.kohsuke.github.Requester.parse(Requester.java:486)```

**Comment by kounoike** [comment]
@McFoggy I tried to use GitHub Organization Folder with GitBucket. I found three problems.

1. GHOF requires some (not implemented) APIs.
2. GHOF use Basic authentication for API calls.
3. GHOF assume git repository as http://server/user/repo.git. But GitBucket provides as http://server:port/git/user/repo.git

I send 2 PR to GitBucket (#1247, #1248) and 1 PR to Jenkins GitHub jenkinsci/github-branch-source-plugin#63.

But I think should be return 404 for undefined API calls rathar than timeout.

**Comment by McFoggy** [comment]
@kounoike I have seen your PRs with a lot of interest :smirk:

**Comment by nazoking** [comment]
it is too complex...

https://github.com/gitbucket/gitbucket/blob/a1307b74648b607bfaa5755e25350311a8452d6e/src/main/scala/gitbucket/core/service/IssuesService.scala#L195-L269

slick sql statement is 

```sql
select x2.x3, x2.x4, x2.x5, x2.x6, x2.x7, x2.x8, x2.x9, x2.x10, x2.x11, x2.x12, x2.x13, x2.x14, x2.x15, x2.x16, x2.x17, x2.x18, x2.x19, x2.x20, x2.x21, x2.x22, x2.x23, x2.x24, x2.x25, x2.x26, x2.x27, x2.x28, x2.x29, x2.x30, x2.x31, x2.x32, x2.x33, x2.x34, x2.x35, x2.x36, x2.x37, x2.x38, x2.x39, x2.x40, x2.x41, x2.x42, x2.x43, x2.x44, x2.x45, x2.x46, x2.x47, x2.x48, x2.x49, x2.x50, x2.x51, x2.x52, x2.x53, x54.x55, x54.x56, x54.x57, x54.x58, x54.x59, x54.x60, x54.x61, x54.x62, x54.x63, x54.x64, x54.x65, x54.x66
from (
  select x67.x68 as x13, x67.x69 as x7, x67.x70 as x8, x67.x71 as x9, x67.x72 as x4, x67.x73 as x6, x67.x74 as x5, x67.x75 as x14, x67.x76 as x3, x67.x77 as x11, x67.x78 as x10, x67.x79 as x12, x67.x80 as x27, x67.x81 as x32, x67.x82 as x34, x67.x83 as x33, x67.x84 as x36, x67.x85 as x29, x67.x86 as x31, x67.x87 as x30, x67.x88 as x28, x67.x89 as x35, x67.x90 as x43, x67.x91 as x52, x67.x92 as x50, x67.x93 as x48, x67.x94 as x53, x67.x95 as x41, x67.x96 as x40, x67.x97 as x46, x67.x98 as x45, x67.x99 as x47, x67.x100 as x39, x67.x101 as x38, x67.x102 as x37, x67.x103 as x51, x67.x104 as x49, x67.x105 as x42, x67.x106 as x44, x107.x108 as x17, x107.x109 as x22, x107.x110 as x24, x107.x111 as x19, x107.x112 as x16, x107.x113 as x26, x107.x114 as x23, x107.x115 as x18, x107.x116 as x25, x107.x117 as x15, x107.x118 as x20, x107.x119 as x21
  from (
    select x120.x121 as x68, x120.x122 as x69, x120.x123 as x70, x120.x124 as x71, x120.x125 as x72, x120.x126 as x73, x120.x127 as x74, x120.x128 as x75, x120.x129 as x76, x120.x130 as x77, x120.x131 as x78, x120.x132 as x79, x120.x133 as x134, x120.x135 as x136, x120.x137 as x138, x120.x139 as x80, x120.x140 as x81, x120.x141 as x82, x120.x142 as x83, x120.x143 as x84, x120.x144 as x85, x120.x145 as x86, x120.x146 as x87, x120.x147 as x88, x120.x148 as x89, x149.x150 as x90, x149.x151 as x91, x149.x152 as x92, x149.x153 as x93, x149.x154 as x94, x149.x155 as x95, x149.x156 as x96, x149.x157 as x97, x149.x158 as x98, x149.x159 as x99, x149.x160 as x100, x149.x161 as x101, x149.x162 as x102, x149.x163 as x103, x149.x164 as x104, x149.x165 as x105, x149.x166 as x106
    from (
      select x167.x168 as x121, x167.x169 as x122, x167.x170 as x123, x167.x171 as x124, x167.x172 as x125, x167.x173 as x126, x167.x174 as x127, x167.x175 as x128, x167.x176 as x129, x167.x177 as x130, x167.x178 as x131, x167.x179 as x132, x167.x180 as x133, x167.x181 as x135, x167.x182 as x137, x167.x183 as x139, x184.x185 as x140, x184.x186 as x141, x184.x187 as x142, x184.x188 as x143, x184.x189 as x144, x184.x190 as x145, x184.x191 as x146, x184.x192 as x147, x184.x193 as x148
      from (
        select x194.x195 as x168, x194.x196 as x169, x194.x197 as x170, x194.x198 as x171, x194.x199 as x172, x194.x200 as x173, x194.x201 as x174, x194.x202 as x175, x194.x203 as x176, x194.x204 as x177, x194.x205 as x178, x194.x206 as x179, x194.x207 as x180, x194.x208 as x181, x194.x209 as x182, x194.x210 as x183
        from (
          select x211.x212 as x195, x211.x213 as x196, x211.x214 as x197, x211.x215 as x198, x211.x216 as x199, x211.x217 as x200, x211.x218 as x201, x211.x219 as x202, x211.x220 as x203, x211.x221 as x204, x211.x222 as x205, x211.x223 as x206, x224.x225 as x207, x224.x226 as x208, x224.x227 as x209, x224.x228 as x210
          from (
            select x229."UPDATED_DATE" as x212, x229."MILESTONE_ID" as x213, x229."ASSIGNED_USER_NAME" as x214, x229."TITLE" as x215, x229."REPOSITORY_NAME" as x216, x229."OPENED_USER_NAME" as x217, x229."ISSUE_ID" as x218, x229."PULL_REQUEST" as x219, x229."USER_NAME" as x220, x229."CLOSED" as x221, x229."CONTENT" as x222, x229."REGISTERED_DATE" as x223
            from "ISSUE" x229
            where
              ((false or ((x229."USER_NAME" = ?) and (x229."REPOSITORY_NAME" = ?))) and (x229."CLOSED" = ?))
              and (x229."PULL_REQUEST" = ?)
          ) x211
          inner join (
            select x230."USER_NAME" as x225, x230."REPOSITORY_NAME" as x226, x230."ISSUE_ID" as x227, x230."COMMENT_COUNT" as x228
            from "ISSUE_OUTLINE_VIEW" x230) x224
          on ((x211.x220 = x224.x225) and (x211.x216 = x224.x226)) and (x211.x218 = x224.x227)
          order by x211.x223 desc
          limit 25
        ) x194
      ) x167
      inner join (
        select x231."REQUEST_USER_NAME" as x185, x231."REQUEST_BRANCH" as x186, x231."REQUEST_REPOSITORY_NAME" as x187, x231."COMMIT_ID_TO" as x188, x231."REPOSITORY_NAME" as x189, x231."BRANCH" as x190, x231."ISSUE_ID" as x191, x231."USER_NAME" as x192, x231."COMMIT_ID_FROM" as x193
        from "PULL_REQUEST" x231
      ) x184
      on ((x184.x192 = x167.x176) and (x184.x189 = x167.x172)) and (x184.x191 = x167.x174)
    ) x120
    inner join (
      select x232."UPDATED_DATE" as x150, x232."ALLOW_WIKI_EDITING" as x151, x232."EXTERNAL_ISSUES_URL" as x152, x232."PARENT_REPOSITORY_NAME" as x153, x232."EXTERNAL_WIKI_URL" as x154, x232."DEFAULT_BRANCH" as x155, x232."DESCRIPTION" as x156, x232."ORIGIN_REPOSITORY_NAME" as x157, x232."ORIGIN_USER_NAME" as x158, x232."PARENT_USER_NAME" as x159, x232."PRIVATE" as x160, x232."REPOSITORY_NAME" as x161, x232."USER_NAME" as x162, x232."ENABLE_WIKI" as x163, x232."ENABLE_ISSUES" as x164, x232."REGISTERED_DATE" as x165, x232."LAST_ACTIVITY_DATE" as x166
      from "REPOSITORY" x232
    ) x149
    on (x149.x162 = x120.x129) and (x149.x161 = x120.x125)
  ) x67
  inner join (
    select x233."MAIL_ADDRESS" as x108, x233."UPDATED_DATE" as x109, x233."IMAGE" as x110, x233."ADMINISTRATOR" as x111, x233."FULL_NAME" as x112, x233."REMOVED" as x113, x233."LAST_LOGIN_DATE" as x114, x233."PASSWORD" as x115, x233."GROUP_ACCOUNT" as x116, x233."USER_NAME" as x117, x233."URL" as x118, x233."REGISTERED_DATE" as x119
    from "ACCOUNT" x233
  ) x107
  on x107.x117 = x67.x73
) x2
inner join (
  select x234."MAIL_ADDRESS" as x57, x234."UPDATED_DATE" as x62, x234."IMAGE" as x64, x234."ADMINISTRATOR" as x59, x234."FULL_NAME" as x56, x234."REMOVED" as x66, x234."LAST_LOGIN_DATE" as x63, x234."PASSWORD" as x58, x234."GROUP_ACCOUNT" as x65, x234."USER_NAME" as x55, x234."URL" as x60, x234."REGISTERED_DATE" as x61
  from "ACCOUNT" x234
) x54
on x54.x55 = x2.x37
```

**Comment by takezoe** [comment]
@nazoking Maybe we should rewrite this query with native SQL, or it might be solved in Slick3. Query compiler has been improved in Slick3.

Moving Slick3 is too hard because it forces monadic API, but we might be possible to move to Slick3 easily using [blocking-slick](https://github.com/takezoe/blocking-slick).
