### ISSUE TITLE
test user still required for MySQL database after changing DB user

### ISSUE THREAD

**Issue by PaulAdams-Conti** [gitbucket/gitbucket#1257]
## Issue
**Impacted version**: 4.2.1

**Deployment mode**: Apache Tomcat 7 server

**Problem description**:
I managed to get GitBucket working with MySQL 5.7 and migrated the H2 database. I then decided I would not use the default "test" user but created my own user and password to access the gitbucket schema in the MySQL DB.

This seemed to work fine so I then deleted the "test" user and restarted GitBucket. Everything again seemed to be fine until I clicked on "Issues" where I instantly received a java exception:

***
java.sql.SQLException: View 'gitbucket.issue_outline_view' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:963)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)....
***

Now I have to recreate this "test" user and again give it privileges to access the gitbucket schema. Once this is done, everything works again.

The same occurs if I select "Pull Requests".

Any ideas how to really get rid of the need for this "test" user?

**Comment by PaulAdams-Conti** [comment]
Found the problem and fixed it.

For the "issue_outline_view" View in the DB, the "DEFINER" was set to 'test'@'%'. Just changed this to my new user and could then delete the 'test' user.
