### ISSUE TITLE
when upgrade from 3.11->3.14->4.0->4.1 sql error

### ISSUE THREAD

**Issue by heran** [gitbucket/gitbucket#1330]
I upgrade from 3.11->3.14->4.0 successfully.
But when from 4.0->4.1 get the error as fllow

```
Oct 20, 2016 9:45:16 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class gitbucket.core.servlet.InitializeListener
org.h2.jdbc.JdbcSQLException: Table "ACCOUNT" already exists; SQL statement:
CREATE TABLE PUBLIC.ACCOUNT (USER_NAME VARCHAR(100) NOT NULL, MAIL_ADDRESS VARCHAR(100) NOT NULL, PASSWORD VARCHAR(40) NOT NULL, ADMINISTRATOR BOOLEAN NOT NULL, URL VARCHAR(200), REGISTERED_DATE TIMESTAMP NOT NULL, UPDATED_DATE TIMESTAMP NOT NULL, LAST_LOGIN_DATE TIMESTAMP, IMAGE VARCHAR(100), GROUP_ACCOUNT BOOLEAN NOT NULL, FULL_NAME VARCHAR(100) NOT NULL, REMOVED BOOLEAN) [42101-190]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.command.ddl.CreateTable.update(CreateTable.java:115)
        at org.h2.command.CommandContainer.update(CommandContainer.java:78)
        at org.h2.command.Command.executeUpdate(Command.java:253)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:157)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:143)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at io.github.gitbucket.solidbase.migration.MigrationUtils.updateDatabase(MigrationUtils.java:20)
        at io.github.gitbucket.solidbase.migration.LiquibaseMigration.migrate(LiquibaseMigration.java:80)
        at io.github.gitbucket.solidbase.migration.LiquibaseMigration.migrate(LiquibaseMigration.java:54)
        at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:45)
        at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:29)
        at gitbucket.core.servlet.InitializeListener.gitbucket$core$servlet$InitializeListener$$$anonfun$1(InitializeListener.scala:78)
        at gitbucket.core.servlet.InitializeListener.gitbucket$core$servlet$InitializeListener$$$anonfun$1$adapted(InitializeListener.scala:36)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:54)
        at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
        at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54)
        at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withTransaction(JdbcBackend.scala:46)
        at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:36)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1083)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1880)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
```

**Comment by heran** [comment]
@takezoe 
First upgraded from 3.11 to 4.5, and got version error.
Then upgraded from 3.11->3.14->4.0
Now the versions table data as follow
```
SELECT * FROM VERSIONS;
MODULE_ID | VERSION  
gitbucket-core| 4.1.0
```
What should I do now?
Thanks

**Comment by takezoe** [comment]
@heran Sorry for my slow reply. Can I still help you?
If you had already gave up, I would like to close this issue.

**Comment by takezoe** [comment]
Close outdated questions.
