### ISSUE TITLE
An error occurred when trying to edit a snippet

### ISSUE THREAD

**Issue by bauzer** [gitbucket/gitbucket#1442]
## Issue
**Impacted version**: 4.9.0

**Deployment mode**: standalone app

**Problem description**:

StackTrace

```java
java.lang.NoSuchMethodError: gitbucket.core.util.Implicits$.RichRequest(Ljavax/servlet/http/HttpServletRequest;)Lgitbucket/core/util/Implicits$RichRequest;
	at gitbucket.gist.util.GistEditorAuthenticator$class.authenticate(GistAuthenticator.scala:16)
	at gitbucket.gist.util.GistEditorAuthenticator$class.editorOnly(GistAuthenticator.scala:11)
	at gitbucket.gist.controller.GistController.editorOnly(GistController.scala:29)
	at gitbucket.gist.controller.GistControllerBase$class.gitbucket$gist$controller$GistControllerBase$class$$$anonfun$6(GistController.scala:75)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$liftAction(ScalatraBase.scala:285)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:279)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:279)
	at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:189)
	at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:28)
	at org.scalatra.ScalatraBase$class.invoke(ScalatraBase.scala:278)
	at gitbucket.core.controller.ControllerBase.org$scalatra$json$JsonSupport$$super$invoke(ControllerBase.scala:28)
	at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:88)
	at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:82)
	at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:189)
	at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:28)
	at org.scalatra.json.JsonSupport$class.invoke(JsonSupport.scala:82)
	at gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:28)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:253)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:251)
	at scala.Option.flatMap(Option.scala:171)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:251)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:250)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:493)
	at org.scalatra.ScalatraBase$class.runRoutes(ScalatraBase.scala:250)
	at gitbucket.core.controller.ControllerBase.runRoutes(ControllerBase.scala:28)
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:205)
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:187)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:28)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:78)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:28)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:58)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:28)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:57)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:28)
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:125)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:28)
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:53)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:28)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply$mcV$sp(flashMap.scala:170)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:145)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:145)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:28)
	at org.scalatra.FlashMapSupport$class.handle(flashMap.scala:145)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:28)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:37)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:37)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:37)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:36)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:69)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply$mcV$sp(ScalatraFilter.scala:74)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:74)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:74)
	at org.scalatra.ScalatraBase$$anonfun$2$$anonfun$apply$4.apply(ScalatraBase.scala:178)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$$anonfun$2.apply(ScalatraBase.scala:178)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:177)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:205)
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:187)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:28)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:78)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:28)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:58)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:28)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:57)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:28)
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:125)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:28)
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:53)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:28)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply$mcV$sp(flashMap.scala:170)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:145)
	at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:145)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:28)
	at org.scalatra.FlashMapSupport$class.handle(flashMap.scala:145)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:28)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:37)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:37)
	at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:37)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:36)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:69)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at gitbucket.core.servlet.GHCompatRepositoryAccessFilter.doFilter(GHCompatRepositoryAccessFilter.scala:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at gitbucket.core.servlet.TransactionFilter.gitbucket$core$servlet$TransactionFilter$$$anonfun$1(TransactionFilter.scala:38)
	at gitbucket.core.servlet.TransactionFilter.gitbucket$core$servlet$TransactionFilter$$$anonfun$1$adapted(TransactionFilter.scala:29)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withTransaction(JdbcBackend.scala:46)
	at gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:29)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ritschwumm** [comment]
is that a plugin? could it be it's compiled against a different version of gitbucket?

**Comment by bauzer** [comment]
That's right!

Thanks

**Comment by takezoe** [comment]
Sorry, new version of gitbucket-gist-plugin will be released soon.

**Comment by takezoe** [comment]
Released: https://github.com/gitbucket/gitbucket-gist-plugin/releases/tag/4.5.0
