### ISSUE TITLE
LDAP Login issue - for some

### ISSUE THREAD

**Issue by mkrischer** [gitbucket/gitbucket#1524]
I have a working gitbucket and ldap system, but some users (esp. new) cannot login to gitbucket with the same password they use everwhere else

I had done some testing on this, but even pretty plain ascii [A-z0-9] passwords do not work. 

Users that have logged in earlier are not bugged?!

I noticed, that there are different messages on the console, but i don't know scala to look through any code myself:

user with right password cannot login:

 09:41:38.661 [qtp21338231-5855] INFO  g.core.service.AccountService - Failed to authenticate: ldaptest

user with wrong password cannot login (as expected)

09:42:31.862 [qtp21338231-5312] INFO  gitbucket.core.util.LDAPUtil$ - LDAPException: Invalid Credentials (49) Invalid Credentials
LDAPException: Matched DN: 
09:42:31.863 [qtp21338231-5312] INFO  g.core.service.AccountService - LDAP error: User LDAP Authentication Failed.
09:42:31.864 [qtp21338231-5312] INFO  g.core.service.AccountService - Failed to authenticate: ldaptest

NOTE: when I extend the right password with some crappy more signs behind, the FIRST message stay, only if i messed the password completely, SECOND notice is send.

 I tried every combination of SSL/TLS setting, also with registration free but it doesn't change. Any Idea?

**Comment by mkrischer** [comment]
After some deeper research I found the source of the problem; too me it's a bug:

You cannot (internal) register a new user with ldap-auth who has the same mail adress as some existing user. I was testing with different accounts (uid in ldap) but all had the same "mail" attribute. this check MAKE sense, if you let users register themself in gitbucket, but with an ldap only check it doesn't make sense; ldap should take care of identifying attributes or at least the "User name attribute" in gitbucket is the only identifying

**Comment by gaetanquentin** [comment]
gitbucket is embeded in wildfly 10.1.0, with jenkins.
If i activate ldap, and then try to log in with ldap account, i have this message:
09:40:51,936 SEVERE [hudson.init.impl.InstallUncaughtExceptionHandler] (Thread-140) A thread (Thread-140/1502) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.: java.lang.IndexOutOfBoundsException: ASN1Structured: set: index 1, size 0
	at com.novell.ldap.asn1.ASN1Structured.get(ASN1Structured.java:171)
	at com.novell.ldap.rfc2251.RfcLDAPMessage.<init>(RfcLDAPMessage.java:187)
	at com.novell.ldap.Connection$ReaderThread.run(Connection.java:1282)
	at java.lang.Thread.run(Thread.java:745)

gitbucket can hangs jenkins in an application server??
