### ISSUE TITLE
[hotdeploy branch] Can't copy jar to .installed on Windows

### ISSUE THREAD

**Issue by kounoike** [gitbucket/gitbucket#1529]
I'm writing ipynb rendering plugin with hotdeploy branch.
It is very useful for writing plugins, but sometimes unstable.
I found one reason described below.

### Before submitting an issue to Gitbucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki) 

## Issue
**Impacted version**: master + plugin-hotfix branch merged

**Deployment mode**: standalone

**Problem description**:
- PluginRegistory copies jar to .installed step and other program(I'm using BAT file, maybe explorer) copy process are simultaneously write and reading.
- It shows error message:
<details>
```
Exception in thread "Thread-11" java.io.FileNotFoundException: C:\Users\kounoike
\Documents\gitbucket\gitbucket-home-4.11\plugins\gitbucket-ipynb-plugin_2.12-1.0
.0.jar (プロセスはファイルにアクセスできません。別のプロセスが使用中です。)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1138)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1091)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
        at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$2(PluginReg
istory.scala:219)
        at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$2$adapted(P
luginRegistory.scala:216)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scal
a:32)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.sca
la:29)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:193)
        at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistory.scal
a:216)
        at gitbucket.core.plugin.PluginRegistry$.reload(PluginRegistory.scala:17
6)
        at gitbucket.core.plugin.PluginWatchThread.$anonfun$run$3(PluginRegistor
y.scala:325)
        at gitbucket.core.plugin.PluginWatchThread.$anonfun$run$3$adapted(Plugin
Registory.scala:323)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$Blo
ckingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:190)
        at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(Tran
sactionalJdbcBackend.scala:26)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$Blo
ckingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:190)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$Blo
ckingDatabase.withSession(BlockingProfile.scala:183)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$Blo
ckingDatabase.withTransaction(BlockingProfile.scala:190)
        at gitbucket.core.plugin.PluginWatchThread.run(PluginRegistory.scala:323
)
```
</details>

**Comment by takezoe** [comment]
Pull request has been raised in #1487. Could you discuss there?

**Comment by kounoike** [comment]
sorry.
