### ISSUE TITLE
 Column "TOKEN" not found; SQL statement:

### ISSUE THREAD

**Issue by ubertooth** [gitbucket/gitbucket#1622]
I have upgraded versions from 3.11 to 3.14 to 4.0 to 4.2.1 to 4.13.

I could clone, created branches on latest version, but I couldn't push the code and getting below error.

```
2017-06-24 04:57:29.473:WARN:root:qtp358699161-19: Internal error during receive-pack to /opt/gitbucket/.gitbucket/repositories/bipin/ZanDataGateway.git
org.h2.jdbc.JdbcSQLException: Column "X7.CTYPE" not found; SQL statement:|select x2."USER_NAME", x2."REPOSITORY_NAME", x2."ISSUE_ID", x2."OPENED_USER_NAME", x2."MILESTONE_ID", x2."ASSIGNED_USER_NAME", x2."TITLE", x2."CONTENT", x2."CLOSED", x2."REGISTERED_DATE", x2."UPDATED_DATE", x2."PULL_REQUEST", x3."USER_NAME", x3."FULL_NAME", x3."MAIL_ADDRESS", x3."PASSWORD", x3."ADMINISTRATOR", x3."URL", x3."REGISTERED_DATE", x3."UPDATED_DATE", x3."LAST_LOGIN_DATE", x3."IMAGE", x3."GROUP_ACCOUNT", x3."REMOVED", x3."DESCRIPTION", x4."USER_NAME", x4."REPOSITORY_NAME", x4."ISSUE_ID", x4."BRANCH", x4."REQUEST_USER_NAME", x4."REQUEST_REPOSITORY_NAME", x4."REQUEST_BRANCH", x4."COMMIT_ID_FROM", x4."COMMIT_ID_TO", x5."USER_NAME", x5."FULL_NAME", x5."MAIL_ADDRESS", x5."PASSWORD", x5."ADMINISTRATOR", x5."URL", x5."REGISTERED_DATE", x5."UPDATED_DATE", x5."LAST_LOGIN_DATE", x5."IMAGE", x5."GROUP_ACCOUNT", x5."REMOVED", x5."DESCRIPTION", x6."USER_NAME", x6."FULL_NAME", x6."MAIL_ADDRESS", x6."PASSWORD", x6."ADMINISTRATOR", x6."URL", x6."REGISTERED_DATE", x6."UPDATED_DATE", x6."LAST_LOGIN_DATE", x6."IMAGE", x6."GROUP_ACCOUNT", x6."REMOVED", x6."DESCRIPTION", x7."USER_NAME", x7."REPOSITORY_NAME", x7."URL", x7."CTYPE", x7."TOKEN" from "ISSUE" x2, "PULL_REQUEST" x4, "ACCOUNT" x5, "ACCOUNT" x6, "ACCOUNT" x3, "WEB_HOOK" x7, "WEB_HOOK_EVENT" x8 where (((((x8."EVENT" = ?) and (x8."USER_NAME" = x7."USER_NAME")) and (x8."REPOSITORY_NAME" = x7."REPOSITORY_NAME")) and (x8."URL" = x7."URL")) and (((((x4."REQUEST_USER_NAME" = ?) and (x4."REQUEST_REPOSITORY_NAME" = ?)) and (x4."REQUEST_BRANCH" = ?)) and (x5."USER_NAME" = x4."USER_NAME")) and (x6."USER_NAME" = x4."REQUEST_USER_NAME"))) and (((((((x2."CLOSED" = ?) and (x4."USER_NAME" = x2."USER_NAME")) and (x4."REPOSITORY_NAME" = x2."REPOSITORY_NAME")) and (x4."ISSUE_ID" = x2."ISSUE_ID")) and (x3."USER_NAME" = x2."OPENED_USER_NAME")) and (x7."USER_NAME" = x2."USER_NAME")) and (x7."REPOSITORY_NAME" = x2."REPOSITORY_NAME")) [42122-195]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:179)
```

And also in service hook 

```
org.h2.jdbc.JdbcSQLException: Column "TOKEN" not found; SQL statement:
CREATE FORCE VIEW PUBLIC._0 AS
SELECT
    USER_NAME AS X3,
    REPOSITORY_NAME AS X4,
    TOKEN AS X7,
    CTYPE AS X6,
    URL AS X5
FROM PUBLIC.WEB_HOOK
WHERE (USER_NAME = ?1)
    AND (REPOSITORY_NAME = ?2) [42122-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
```

**Comment by takezoe** [comment]
@ubertooth Check WEB_HOOK table schema on the H2 console.

**Comment by ubertooth** [comment]
Token and ctype fields are not there

SELECT * FROM WEB_HOOK;
USER_NAME  	REPOSITORY_NAME  	URL  
(no rows, 0 ms)

Shall we create the fields? how to create them

**Comment by ubertooth** [comment]
Still issue is not resolved. Please help

**Comment by takezoe** [comment]
It seems to failed to migrate to 3.14. You can add unexisting columns of WEB_HOOK table as:

```sql
ALTER TABLE WEB_HOOK ADD COLUMN TOKEN VARCHAR(100);
ALTER TABLE WEB_HOOK ADD COLUMN CTYPE VARCHAR(10);
UPDATE WEB_HOOK SET CTYPE = 'form';
```

P.S. We are using GitHub Issues for task management. If you have a question. Ask it in [gitter room](https://gitter.im/gitbucket/gitbucket) at first instead of creating an issue according to the contribution guide line.
https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md
