### ISSUE TITLE
Cannot fork a repository

### ISSUE THREAD

**Issue by dlorych** [gitbucket/gitbucket#1631]
**Impacted version**: 4.14.0

**Deployment mode**: *standalone app*

**Problem description**:
*Cannot fork a repository. I get following error:

```
java.io.FileNotFoundException: Source '/root/.gitbucket/repositories/test/test-repo' does not exist
	at org.apache.commons.io.FileUtils.checkFileRequirements(FileUtils.java:1405)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1368)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1268)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1237)
	at gitbucket.core.controller.AccountControllerBase.$anonfun$$init$$96(AccountController.scala:611)
	at gitbucket.core.util.LockUtil$.$anonfun$lock$1(LockUtil.scala:30)
	at gitbucket.core.util.SyntaxSugars$.defining(SyntaxSugars.scala:12)
	at gitbucket.core.util.LockUtil$.lock(LockUtil.scala:27)
	at gitbucket.core.controller.AccountControllerBase.$anonfun$$init$$95(AccountController.scala:565)
	at gitbucket.core.util.ReadableUsersAuthenticator.$anonfun$readableUsersOnly$2(Authenticator.scala:122)
	at gitbucket.core.util.ReadableUsersAuthenticator.$anonfun$authenticate$11(Authenticator.scala:129)
	at scala.Option.map(Option.scala:146)
```

To reproduce a problem create a new repository and try to fork with another user/group.

I expect this is caused by a commit related to 7761946ec09c764779cfb2cee07e4996f9e942b3 - AccountController.scala line 609.

**Comment by takezoe** [comment]
@dlorych Thanks for reporting. The fixed version 4.14.1 is available.
https://github.com/gitbucket/gitbucket/releases/tag/4.14.1
