### ISSUE TITLE
"NoSuchMethodException: java.lang.Process.getPid()" in JDK9 test

### ISSUE THREAD

**Issue by xuwei-k** [gitbucket/gitbucket#1640]
depends on https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/issues/57

https://travis-ci.org/gitbucket/gitbucket/jobs/252648985#L888

```
java.lang.NoSuchMethodException: java.lang.Process.getPid()
	at java.base/java.lang.Class.getMethod(Class.java:2065)
	at de.flapdoodle.embed.process.runtime.Processes$PidHelper$1.getPid(Processes.java:195)
	at de.flapdoodle.embed.process.runtime.Processes.processId(Processes.java:72)
	at de.flapdoodle.embed.process.runtime.ProcessControl.<init>(ProcessControl.java:64)
	at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:205)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:98)
```

**Comment by voplex95** [comment]
Hi, having the same problem. Any progress on that?
