### ISSUE TITLE
Gitbucket 4.14 with MySQL: Cannot add foreign key constraint

### ISSUE THREAD

**Issue by haarp** [gitbucket/gitbucket#1646]
An upgrade from 4.13 to 4.14 is impossible with my MySQL db.

It creates the PRIORITY table, but then fails to add foreign key cosntraints.

```
2017-07-14 15:56:20.063:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@5dbf5634{/,file:///home/gitbucket/.gitbucket/tmp/webapp/,UNAVAILABLE}{file:/home/gitbucket/gitbucket-4.14.war}
java.sql.SQLException: Cannot add foreign key constraint
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:545)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
	at com.mysql.cj.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1826)
	at com.mysql.cj.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2034)
	at com.mysql.cj.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:1970)
	at com.mysql.cj.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5001)
	at com.mysql.cj.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1955)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at io.github.gitbucket.solidbase.migration.MigrationUtils.updateDatabase(MigrationUtils.java:20)
	at io.github.gitbucket.solidbase.migration.LiquibaseMigration.migrate(LiquibaseMigration.java:93)
	at io.github.gitbucket.solidbase.migration.LiquibaseMigration.migrate(LiquibaseMigration.java:54)
	at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:45)
	at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:29)
	at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1(InitializeListener.scala:94)
	at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1$adapted(InitializeListener.scala:52)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:190)
	at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:190)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:183)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:190)
	at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:52)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:843)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:533)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:816)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:345)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1406)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1368)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:522)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:252)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:422)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:389)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at JettyLauncher.main(JettyLauncher.java:121)
```

Deployment is standalone mode.

**Comment by takezoe** [comment]
What's your MySQL version?

**Comment by takezoe** [comment]
Thanks. In addition, could you check following points?

- Does `PRIORITY_ID` column exist in `ISSUE` table?
- Does `ACCOUNT_WEB_HOOK` table exist?
- Does `ACCOUNT_WEB_HOOK_EVENT` table exist?

**Comment by haarp** [comment]
Thanks.

'no' to all three questions

**Comment by takezoe** [comment]
Hm, are there any errors in MySQL log?

**Comment by haarp** [comment]
> Hm, are there any errors in MySQL log?

Nope, no errors.

**Comment by takezoe** [comment]
To find reason of error, try to run following SQL directly:

```sql
ALTER TABLE PRIORITY ADD CONSTRAINT 
  FOREIGN KEY IDX_PRIORITY_FK0 (USER_NAME, REPOSITORY_NAME) 
  REFERENCES REPOSITORY (USER_NAME, REPOSITORY_NAME);
```

This SQL is same as run in auto migration to GitBucket 4.14. So if this SQL succeed, I can't infer why your migration was failed. Try to drop `PRIORITY` and restart GitBucket to re-run migration to 4.14.

If this SQL fails, report an error message on MySQL.

**Comment by haarp** [comment]
I now managed to make it work. The newly-created PRIORITY table had a different data layout than the rest.

Then I ran into an "View's SELECT contains a subquery in the FROM clause" error. This I solved by upgrading MySQL. From the [docs](https://dev.mysql.com/doc/refman/5.7/en/create-view.html): " Before MySQL 5.7.7, the SELECT statement cannot contain a subquery in the FROM clause."

Lastly I had to undo the partial migration by hand and run Gitbucket again. It upgraded my db and seems to be working now.

Thanks takezoe!

I think it would be good if Gitbucket didn't leave the db in a partial migration state when something goes wrong.

**Comment by aadrian** [comment]
> I think it would be good if Gitbucket didn't leave the db in a partial migration state when something goes wrong.

IMHO Liquibase (Solidbase) migrations should all run in a single transaction, and if they don't succeed, the webapp should display an error page that the DB update wasn't successful.

**Comment by takezoe** [comment]
DDL can't be run in a transaction. In particular, it commits current transaction implicitly in MySQL.
