### ISSUE TITLE
git fetch error on ver 4.14.1

### ISSUE THREAD

**Issue by raindylong** [gitbucket/gitbucket#1650]
Ver: 4.14.1
Java: 1.8
OS: Ubuntu 14.04 LTS

## Issue

**Problem description**:
$ git fetch
remote: internal server error
fatal: protocal error: bad pack header

error information in access log:
`13:18:32.951 [Thread-65] ERROR gitbucket.core.ssh.GitCommand - null
org.eclipse.jgit.transport.UploadPackInternalServerErrorException: null
        at org.eclipse.jgit.transport.UploadPack.sendPack(UploadPack.java:1402)
        at org.eclipse.jgit.transport.UploadPack.service(UploadPack.java:775)
        at org.eclipse.jgit.transport.UploadPack.upload(UploadPack.java:668)
        at gitbucket.core.ssh.DefaultGitUploadPack.$anonfun$runTask$4(GitCommand.scala:151)
        at gitbucket.core.ssh.DefaultGitUploadPack.$anonfun$runTask$4$adapted(GitCommand.scala:148)
        at gitbucket.core.util.SyntaxSugars$.using(SyntaxSugars.scala:38)
        at gitbucket.core.ssh.DefaultGitUploadPack.runTask(GitCommand.scala:148)
        at gitbucket.core.ssh.GitCommand.$anonfun$newTask$1(GitCommand.scala:42)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing commit 43996944dba626dea6e76733e386181cefc11efe
        at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:164)
        at org.eclipse.jgit.revwalk.RevWalk.getCachedBytes(RevWalk.java:903)
        at org.eclipse.jgit.revwalk.RevCommit.parseHeaders(RevCommit.java:155)
        at org.eclipse.jgit.revwalk.PendingGenerator.next(PendingGenerator.java:147)
        at org.eclipse.jgit.revwalk.StartGenerator.next(StartGenerator.java:184)
        at org.eclipse.jgit.revwalk.RevWalk.next(RevWalk.java:435)
        at org.eclipse.jgit.revwalk.ObjectWalk.next(ObjectWalk.java:294)
        at org.eclipse.jgit.internal.storage.pack.PackWriterBitmapWalker.findObjects(PackWriterBitmapWalker.java:120)
        at org.eclipse.jgit.internal.storage.pack.PackWriter.findObjectsToPackUsingBitmaps(PackWriter.java:1876)
        at org.eclipse.jgit.internal.storage.pack.PackWriter.findObjectsToPack(PackWriter.java:1671)
        at org.eclipse.jgit.internal.storage.pack.PackWriter.preparePack(PackWriter.java:800)
        at org.eclipse.jgit.transport.UploadPack.sendPack(UploadPack.java:1516)
        at org.eclipse.jgit.transport.UploadPack.sendPack(UploadPack.java:1396)
        ... 8 common frames omitted`

**Comment by nbkhope** [comment]
That happens because the ssh encryption changed? Try removing gitbucket from your known hosts in `~/.ssh/known_hosts` and adding it again after doing` git fetch`. If you defined `HostKeyAlgorithms` in `~/.ssh/config`, make sure to remove that as well before trying.

**Comment by aadrian** [comment]
@raindylong did the solution provided by @nbkhope work ?
