### ISSUE TITLE
503 again in 4.14.1

### ISSUE THREAD

**Issue by VitaliyAT** [gitbucket/gitbucket#1658]
Get 503 error when trying open gitbucket. The same result through: localhost, 127.0.0.1, ...keendns.net (through internet) and 8080 port. Vertion of GB is 4.14.1. Windows 10.

```
D:\[SERVER]\gitBucket>java -jar D:\[SERVER]\gitBucket\gitbucket.war --gitbucket.home=D:\[SERVER]\gitBucket
2017-07-29 18:42:56.955:INFO::main: Logging initialized @161ms
2017-07-29 18:42:57.099:INFO:oejs.Server:main: jetty-9.3.z-SNAPSHOT
2017-07-29 18:42:59.040:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@6956de9{/,null,null}{file:/D:/%5bSERVER%5d/gitBucket/gitbucket.war}
java.lang.IllegalStateException: Failed to delete temp dir D:\[SERVER]\gitBucket\tmp
        at org.eclipse.jetty.webapp.WebInfConfiguration.configureTempDirectory(WebInfConfiguration.java:376)
        at org.eclipse.jetty.webapp.WebInfConfiguration.resolveTempDirectory(WebInfConfiguration.java:264)
        at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:69)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:485)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:521)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:252)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.server.Server.start(Server.java:422)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:389)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at JettyLauncher.main(JettyLauncher.java:121)
2017-07-29 18:42:59.130:INFO:oejs.AbstractConnector:main: Started ServerConnector@7cdbc5d3{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2017-07-29 18:42:59.131:INFO:oejs.Server:main: Started @2340ms
```

**Comment by aadrian** [comment]
@VitaliyAT does this still happen with the latest GitBucket version?

**Comment by torant1** [comment]
> Get 503 error when trying open gitbucket. The same result through: localhost, 127.0.0.1, ...keendns.net (through internet) and 8080 port. Vertion of GB is 4.14.1. Windows 10.
> 
> ```
> D:\[SERVER]\gitBucket>java -jar D:\[SERVER]\gitBucket\gitbucket.war --gitbucket.home=D:\[SERVER]\gitBucket
> 2017-07-29 18:42:56.955:INFO::main: Logging initialized @161ms
> 2017-07-29 18:42:57.099:INFO:oejs.Server:main: jetty-9.3.z-SNAPSHOT
> 2017-07-29 18:42:59.040:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@6956de9{/,null,null}{file:/D:/%5bSERVER%5d/gitBucket/gitbucket.war}
> java.lang.IllegalStateException: Failed to delete temp dir D:\[SERVER]\gitBucket\tmp
>         at org.eclipse.jetty.webapp.WebInfConfiguration.configureTempDirectory(WebInfConfiguration.java:376)
>         at org.eclipse.jetty.webapp.WebInfConfiguration.resolveTempDirectory(WebInfConfiguration.java:264)
>         at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:69)
>         at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:485)
>         at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:521)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
>         at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
>         at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:252)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
>         at org.eclipse.jetty.server.Server.start(Server.java:422)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
>         at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
>         at org.eclipse.jetty.server.Server.doStart(Server.java:389)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
>         at JettyLauncher.main(JettyLauncher.java:121)
> 2017-07-29 18:42:59.130:INFO:oejs.AbstractConnector:main: Started ServerConnector@7cdbc5d3{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
> 2017-07-29 18:42:59.131:INFO:oejs.Server:main: Started @2340ms
> ```

i have the same problem right now !

**Comment by aadrian** [comment]
@torant1 do you have this problem with GitBucket 4.32.0 (the latest stable version)  ?
Also, what JDK are you using for this GitBucket instance?

**Comment by skullwritter** [comment]
@aadrian and @torant1 
- it could be due a permission error, since the files are not being deleted
- java version
- platform wrong version
#### what can be done?
- check the folder permissions, delete tmp and try to run it again
- check if your version of java is at least 1.8
- check if you are using the latest version of gitbucket
