### ISSUE TITLE
Mysql connection pool error

### ISSUE THREAD

**Issue by karthikbalu** [gitbucket/gitbucket#1737]
[+ [ jdbc:mysql://127.0.0.1/gitbucket?useUnicode=true&characterEncoding=utf8 -a username -a password ]
+ cat
+ exec java -jar /opt/gitbucket.war

2017-10-12 14:28:52.311:INFO::main: Logging initialized @17800ms
2017-10-12 14:29:00.012:INFO:oejs.Server:main: jetty-9.3.z-SNAPSHOT
2017-10-12 14:30:07.022:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
14:31:06.757 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
14:31:09.519 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
14:31:10.339 [main] INFO  g.core.servlet.InitializeListener - Check version
14:31:10.394 [main] INFO  g.core.servlet.InitializeListener - Start schema update
14:31:27.839 [main] WARN  c.zaxxer.hikari.pool.ProxyConnection - HikariPool-1 - Connection org.mariadb.jdbc.MariaDbConnection@1358b28e marked as broken because of SQLSTATE(08000), ErrorCode(1220)
java.sql.SQLNonTransientConnectionException: (conn:118632) Connection is close
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:156)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:245)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:153)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeUpdate(MariaDbPreparedStatementClient.java:186)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at io.github.gitbucket.solidbase.migration.MigrationUtils.updateDatabase(MigrationUtils.java:20)
	at io.github.gitbucket.solidbase.manager.JDBCVersionManager.initialize(JDBCVersionManager.java:24)
	at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:33)
	at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:29)
	at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1(InitializeListener.scala:66)
	at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1$adapted(InitializeListener.scala:57)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
	at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
	at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:57)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:843)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:533)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:816)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:345)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1406)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1368)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:522)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:252)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:422)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:389)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at JettyLauncher.main(JettyLauncher.java:127)
Caused by: java.sql.SQLException: Connection is close
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1393)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:206)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:212)
	... 38 common frames omitted
2017-10-12 14:31:27.926:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@78b236a0{/,file:///gitbucket/tmp/webapp/,UNAVAILABLE}{file:/opt/gitbucket.war}
java.sql.SQLException: Connection is closed
	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:466)
	at com.sun.proxy.$Proxy2.setAutoCommit(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:380)
	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java)
	at slick.jdbc.JdbcBackend$BaseSession.endInTransaction(JdbcBackend.scala:461)
	at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:30)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
	at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:57)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:843)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:533)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:816)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:345)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1406)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1368)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:522)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:252)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:422)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:389)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at JettyLauncher.main(JettyLauncher.java:127)
2017-10-12 14:31:28.496:INFO:oejs.AbstractConnector:main: Started ServerConnector@df1cff6{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2017-10-12 14:31:28.507:INFO:oejs.Server:main: Started @174259ms
](url)

Please help
Thanks

**Comment by karthikbalu** [comment]
I was able to connect to mysql instance using JDBC separately but for some reason its not working with gitbucket

**Comment by uli-heller** [comment]
I'm using mariadb-10.2.8 and gitbucket-4.17.0 without any issues. Can you provide more details?

**Comment by karthikbalu** [comment]
The log is not showing any specific details about the error other than above.. could be because gitbucket using mariadb jdbc connector instead of mysql jdbc connector

**Comment by uli-heller** [comment]
Which version of mysql are you using? Which version of gitbucket?

**Comment by karthikbalu** [comment]
Mysql 5.7.17
Gitbucket tried 4.16.0,  4.17.0 and 4.18.0 also today but same error

**Comment by karthikbalu** [comment]
This is my configuration
Cmd i run : 
`java -jar gitbucket.war --gitbucket.home=/opt/gitbucket/gitbucket-data`

Gitbucket Home path:
` /opt/gitbucket/gitbucket-data`

database.conf
`db {
  url = "jdbc:mysql://localhost/gitbucket?useUnicode=true&characterEncoding=utf8"
  user = "testuser"
  password = "testpassword"
  connectionTimeout = 30000
  idleTimeout = 600000
  maxLifetime = 1800000
  minimumIdle = 10
  maximumPoolSize = 10
}`

**Comment by karthikbalu** [comment]
The strange thing i noticed, i tried connecting from my gitbucket installed locally on mac to the same remote mysql server and it worked but its not working on the above server

local gitbucket to remote mysql - works
remote gitbucket to remote mysql (both installed on same server) - does'nt work

Could be because of my JDK version?
local java version : Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
remote java version : OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)

**Comment by uli-heller** [comment]
I'm using this:

```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

Am 2017-10-14 07:46, schrieb Karthik Balu:

**Comment by karthikbalu** [comment]
hmm.. i tried even changing the java version to 
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)


still no luck connecting mysql

**Comment by uli-heller** [comment]
Maybe there is an incompatibility between the versions of mysql server and mariadb client?
gitbucket uses mariadb-java-client-2.0.3.jar. I'd try to use a tool like http://sqlline.sourceforge.net
to do further debugging.

* Install the tool
* Install mariadb-java-client-2.0.3.jar within the tool
* Try to access the database using sqlline and mariadb-java-client

Good luck, Uli
