### ISSUE TITLE
Some repos don't clone properly through the web

### ISSUE THREAD

**Issue by lavvy** [gitbucket/gitbucket#1874]
If you try to create a new repo with a url from the gui. You will notice that some repos are cloned properly but some don't .

For example try to create a rethinkdb repo with this url https://github.com/rethinkdb/rethinkdb on the 4.21.2 demo install .

It creates but not properly.

**Comment by bviktor** [comment]
And what do the logs say?

**Comment by madper** [comment]
Hey, I tried to reproduce the issue locally and hit following:

> 21:28:04.760 [qtp250421012-13] ERROR g.c.controller.PreProcessController - Catch unhandled error in request: Request(GET //localhost:8080/assets/common/css/gitbucket.css?20180217204457)@2708d6fa
> org.eclipse.jetty.io.EofException: null
>         at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:292)
>         at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:429)
>         at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:322)
>         at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:372)
>         at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:742)
>         at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
>         at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
>         at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:522)
>         at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:730)
>         at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:786)
>         at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:234)
>         at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:771)
>         at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:870)
>         at org.eclipse.jetty.server.HttpOutput.sendContent(HttpOutput.java:747)
>         at org.eclipse.jetty.server.ResourceService.sendData(ResourceService.java:729)
>         at org.eclipse.jetty.server.ResourceService.doGet(ResourceService.java:294)
>         at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:458)
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
>         at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
>         at gitbucket.core.servlet.CompositeScalatraFilter.doFilter(CompositeScalatraFilter.scala:56)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
>         at gitbucket.core.servlet.PluginControllerFilter.doFilter(PluginControllerFilter.scala:44)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
>         at org.scalatra.ScalatraFilter.$anonfun$doNotFound$1(ScalatraFilter.scala:79)
>         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)

The reproducer is fairly simple:
download the latest 4.21.2 war file. Run it with `java -jar ./gitbucket.war`.
Create a new repo with exist rethinkdb.git and waiting.

I am able to reproduce it 100%. Please do let me know if you can't reproduce it in your environment. I may able to provide a docker image for reproducing it.

**Comment by takezoe** [comment]
> For example try to create a rethinkdb repo with this url https://github.com/rethinkdb/rethinkdb on the 4.21.2 demo install .

Specify a git repository url instead as: https://github.com/rethinkdb/rethinkdb.git

**Comment by gemmaro** [comment]
I've seen similar behavior, even when the URL of the Git repository has `.git` at the end.

On the other hand, this problem may be workarounded by: **going to "Settings" > "Branches" > "Default Branches"**, make sure the correct branch is selected, and **press "Update"**. And now you should be able to view the files correctly and open issue pages and so on as usual.

I'm not yet sure about the cause of the problem though...
