### ISSUE TITLE
Gitbucket crash after update from 4.20 to higher version

### ISSUE THREAD

**Issue by DevilCoreBlack** [gitbucket/gitbucket#1915]
Cannot update from 4.20 version.
In log I getting this error:
```
2018-03-17 18:54:08.704:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@7a24eb3{/,file:///C:/Data/Gitbucket/tmp/webapp/,UNAVAILABLE}{file:/C:/Data/Gitbucket/ServerApp/gitbucket.war}
java.sql.SQLException: (conn=19) Cannot add foreign key constraint
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:198)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:110)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:228)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:216)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:150)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeUpdate(MariaDbPreparedStatementClient.java:183)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at io.github.gitbucket.solidbase.migration.MigrationUtils.updateDatabase(MigrationUtils.java:20)
	at io.github.gitbucket.solidbase.migration.LiquibaseMigration.migrate(LiquibaseMigration.java:93)
	at io.github.gitbucket.solidbase.migration.LiquibaseMigration.migrate(LiquibaseMigration.java:54)
	at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:45)
	at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:29)
	at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1(InitializeListener.scala:66)
	at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1$adapted(InitializeListener.scala:57)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
	at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
	at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:57)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:890)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:853)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1514)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1476)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:252)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:449)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:416)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at JettyLauncher.main(JettyLauncher.java:127)
Caused by: 
java.sql.SQLException: Cannot add foreign key constraint|Query is: ALTER TABLE repository_gitbucket_git.`RELEASE` ADD CONSTRAINT IDX_RELEASE_FK0 FOREIGN KEY (USER_NAME, REPOSITORY_NAME) REFERENCES repository_gitbucket_git.REPOSITORY (USER_NAME, REPOSITORY_NAME)
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:153)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:253)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:209)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:150)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeUpdate(MariaDbPreparedStatementClient.java:183)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at io.github.gitbucket.solidbase.migration.MigrationUtils.updateDatabase(MigrationUtils.java:20)
	at io.github.gitbucket.solidbase.migration.LiquibaseMigration.migrate(LiquibaseMigration.java:93)
	at io.github.gitbucket.solidbase.migration.LiquibaseMigration.migrate(LiquibaseMigration.java:54)
	at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:45)
	at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:29)
	at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1(InitializeListener.scala:66)
	at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1$adapted(InitializeListener.scala:57)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
	at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
	at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:57)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:890)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:853)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1514)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1476)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:252)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:449)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:416)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at JettyLauncher.main(JettyLauncher.java:127)
```
I use MySQL 5.7.21
How i can update Gitbucket?

**Comment by takezoe** [comment]
This is a known issue with MySQL (RELEASE is a reserved keyword in MySQL). We are now considering how to fix it. Could you wait for the next release?

**Comment by Sherpard** [comment]
@takezoe just a suggestion, what about adding a prefix to each table? 
It could imply a lot of rewriting, but will get rid of reserved words in table names (fields are another history)

**Comment by takezoe** [comment]
@DevilCoreBlack I tested and succeeded to migrate on MySQL 5.7.21. `RELEASE` is a reserved word so we should avoid to use it as a table name, but migration should success because it's run with backquoted in migration.

Can you find a `RELEASE` table in your database? Then could you try to add a failed foreign key by hand with following SQL?

```sql
`RELEASE` ADD CONSTRAINT IDX_RELEASE_FK0 FOREIGN KEY (USER_NAME, REPOSITORY_NAME) REFERENCES repository_gitbucket_git.REPOSITORY (USER_NAME, REPOSITORY_NAME)
```

If above SQL fails, I guess maybe there is an another cause other than `RELEASE` is reserved word in MySQL.

**Comment by DevilCoreBlack** [comment]
Thx for quick reply

I can wait for the next release.

Yes, table RELEASE is present, but this SQL query not work - Error Code: 1064. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax....

This query
`ALTER TABLE `RELEASE` ADD CONSTRAINT IDX_RELEASE_FK0 FOREIGN KEY (USER_NAME, REPOSITORY_NAME) REFERENCES repository_gitbucket_git.REPOSITORY (USER_NAME, REPOSITORY_NAME);` 
gives an error message:
Error Code: 1215. Cannot add foreign key constraint

**Comment by takezoe** [comment]
Oh, sorry. my correct intended SQL is below:

```sql
ALTER TABLE `RELEASE` ADD CONSTRAINT IDX_RELEASE_FK0 FOREIGN KEY (USER_NAME, REPOSITORY_NAME) REFERENCES REPOSITORY (USER_NAME, REPOSITORY_NAME)
```

I don't know where `repository_gitbucket_git` comes from. Do you know something about it?

**Comment by takezoe** [comment]
I understood that `repository_gitbucket_git` is your database name. It's not problem. Hmm...

**Comment by takezoe** [comment]
@DevilCoreBlack Could you show results of following SQL?

```sql
SHOW CREATE TABLE REPOSITORY;
SHOW CREATE TABLE RELEASE;
```

and check the existence of RELEASE_ASSET table.

**Comment by DevilCoreBlack** [comment]
Table `RELEASE` is created only when i replace war file to new version, and run it. And i cant run this query:
```
SHOW CREATE TABLE RELEASE;

Error Code: 1064. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'RELEASE' at line 1
```

`RELEASE_ASSET` - absent

`REPOSITORY` : 
```
Table	Create Table
REPOSITORY	CREATE TABLE `repository` (
  `USER_NAME` varchar(100) NOT NULL,
  `REPOSITORY_NAME` varchar(100) NOT NULL,
  `PRIVATE` bit(1) NOT NULL,
  `DESCRIPTION` text,
  `DEFAULT_BRANCH` varchar(100) DEFAULT NULL,
  `REGISTERED_DATE` datetime NOT NULL,
  `UPDATED_DATE` datetime NOT NULL,
  `LAST_ACTIVITY_DATE` datetime NOT NULL,
  `ORIGIN_USER_NAME` varchar(100) DEFAULT NULL,
  `ORIGIN_REPOSITORY_NAME` varchar(100) DEFAULT NULL,
  `PARENT_USER_NAME` varchar(100) DEFAULT NULL,
  `PARENT_REPOSITORY_NAME` varchar(100) DEFAULT NULL,
  `EXTERNAL_ISSUES_URL` varchar(200) DEFAULT NULL,
  `EXTERNAL_WIKI_URL` varchar(200) DEFAULT NULL,
  `ALLOW_FORK` bit(1) NOT NULL DEFAULT b'1',
  `WIKI_OPTION` varchar(10) NOT NULL DEFAULT 'DISABLE',
  `ISSUES_OPTION` varchar(10) NOT NULL DEFAULT 'DISABLE',
  PRIMARY KEY (`USER_NAME`,`REPOSITORY_NAME`),
  CONSTRAINT `IDX_REPOSITORY_FK0` FOREIGN KEY (`USER_NAME`) REFERENCES `account` (`USER_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AVG_ROW_LENGTH=8192 ROW_FORMAT=DYNAMIC
```

**Comment by DevilCoreBlack** [comment]
@takezoe You right, in any actions with word `RELEASE`  i get `Error Code: 1064. You have an error in your SQL syntax`
I wait for your new build 4.23. Or maybe you would like to compile for me new *war with #1916 changes so i could test it.

**Comment by takezoe** [comment]
@DevilCoreBlack Oops. Sorry, I made a mistake. Run below instead (quote `RELEASE` with backquote):

```sql
SHOW CREATE TABLE `RELEASE`;
```

**Comment by DevilCoreBlack** [comment]
```
Table	Create Table
RELEASE	CREATE TABLE `release` (
  `USER_NAME` varchar(100) COLLATE utf8_bin NOT NULL,
  `REPOSITORY_NAME` varchar(100) COLLATE utf8_bin NOT NULL,
  `TAG` varchar(100) COLLATE utf8_bin NOT NULL,
  `NAME` varchar(100) COLLATE utf8_bin NOT NULL,
  `AUTHOR` varchar(100) COLLATE utf8_bin NOT NULL,
  `CONTENT` text COLLATE utf8_bin,
  `REGISTERED_DATE` datetime NOT NULL,
  `UPDATED_DATE` datetime NOT NULL,
  PRIMARY KEY (`USER_NAME`,`REPOSITORY_NAME`,`TAG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
```

**Comment by takezoe** [comment]
I guess adding foreign key constraint failed because column encoding is different between `RELEASE` and `REPOSITORY`. Have you changed a default encoding of the database after creating this database?

This inconsistency can't be fixed by just upgrading to 4.23. You have to fix this inconsistency somehow before upgrading to newer version.

**Comment by DevilCoreBlack** [comment]
Can you tell me what default charset and collate  are set on your testing database?
The previous installed version of gitbucket was 4.19.3 and i updated it to 4.20 (everything was fine). But I cannot update to higher versions.
I recreated the database when restoring it many times and I always used the default charset - uft8, collate - utf8_bin

**Comment by DevilCoreBlack** [comment]
Yes, problem was in default-collate of my database - utf8_bin
For your soft it must be utf8_general_ci for correct work of the database.

I create dump of my database, then drop this database and create new database with  default-collate - utf8_general_ci. Then i import data from the dump, and launch gitbacket update again. Update was complete successful.

Thank you for your help!

**Comment by takezoe** [comment]
That's good! Can I close this issue?

**Comment by DevilCoreBlack** [comment]
Yes.
Yhx
