### ISSUE TITLE
Upgrade from MySQL to MariaDB causes HTTP error 503

### ISSUE THREAD

**Issue by kurdtpage** [gitbucket/gitbucket#2020]
### Before submitting an issue to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki) 

*(if you have performed all the above, remove the paragraph and continue describing the issue with template below)*

## Issue
**Impacted version**: 4.24? (gitbucket.war filesize: 54353523 bytes)

**Deployment mode**: Using apache2, command line: nohup java -jar gitbucket.war &

**Problem description**:
I have just migrated from MySQL 5.7 to MariaDB 10.1.30 and installed phpmyadmin (not sure if this is relevant or not) and now when I go to http://localhost:8080 (my usual way of accessing gitbucket), I get http error 503 (service unavailable).

The output of the console is how below. **Seems like testuser@localhost has been removed?**

I created the user again using phpmyadmin, but I don't know what password is (I tried what I thought it was and kept getting access denied)

````
2018-05-20 23:34:57.513:INFO::main: Logging initialized @123ms to org.eclipse.jetty.util.log.StdErrLog
2018-05-20 23:34:57.714:INFO:oejs.Server:main: jetty-9.4.z-SNAPSHOT
2018-05-20 23:34:59.239:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2018-05-20 23:35:01.224:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2018-05-20 23:35:01.224:INFO:oejs.session:main: No SessionScavenger set, using defaults
2018-05-20 23:35:01.226:INFO:oejs.session:main: Scavenging every 600000ms
23:35:01.551 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
23:35:02.641 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'testuser'@'localhost' (using password: YES)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:173)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:110)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1093)
        at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:494)
        at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)
        at org.mariadb.jdbc.Driver.connect(Driver.java:86)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:533)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:114)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72)
        at gitbucket.core.servlet.Database$.<init>(TransactionFilter.scala:65)
        at gitbucket.core.servlet.Database$.<clinit>(TransactionFilter.scala)
        at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:60)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:890)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:853)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1514)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1476)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
````

**Comment by kurdtpage** [comment]
Actually, looking closer at the output, I think this may be due to the MariaDB java connector

**Comment by kurdtpage** [comment]
The file at ~/.gitbucket/tmp/webapp/WEB-INF/lib/mariadb-java-client-2.2.3.jar is automatically generated, renaming/removing has no effect

**Comment by kurdtpage** [comment]
Just tried a fresh install of gitbucket onto a new server that does not have MariaDB (it has MySQL 5.7) and got the same error:
```
me@server-old:~ $ zip gitbucket.zip .gitbucket/*
me@server-old:~ $ cp gitbucket.zip /var/www/html/
```
then
```
me@server-new:~ $ wget https://server-old/gitbucket.zip
me@server-new:~ $ wget https://github.com/gitbucket/gitbucket/releases/download/4.24.1/gitbucket.war
me@server-new:~ $ sudo apt-get update
me@server-new:~ $ sudo apt-get install default-jre
me@server-new:~ $ sudo rm -R .gitbucket/tmp
me@server-new:~ $ java -jar gitbucket.war &
```

**Comment by kurdtpage** [comment]
Heres the full output:
```
2018-05-21 22:41:57.835:INFO::main: Logging initialized @923ms to org.eclipse.jetty.util.log.StdErrLog
2018-05-21 22:41:58.236:INFO:oejs.Server:main: jetty-9.4.z-SNAPSHOT
2018-05-21 22:42:00.269:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2018-05-21 22:42:02.399:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2018-05-21 22:42:02.399:INFO:oejs.session:main: No SessionScavenger set, using defaults
2018-05-21 22:42:02.404:INFO:oejs.session:main: Scavenging every 660000ms
22:42:02.836 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
22:42:03.909 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=localhost)(port=3306)(type=master) : Connection refused (Connection refused)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:175)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:83)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1097)
        at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:494)
        at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)
        at org.mariadb.jdbc.Driver.connect(Driver.java:86)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:533)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:114)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72)
        at gitbucket.core.servlet.Database$.<init>(TransactionFilter.scala:65)
        at gitbucket.core.servlet.Database$.<clinit>(TransactionFilter.scala)
        at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:60)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:890)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:853)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1514)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1476)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:252)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.server.Server.start(Server.java:449)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:416)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at JettyLauncher.main(JettyLauncher.java:127)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:448)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1089)
        ... 36 common frames omitted
2018-05-21 22:42:03.946:INFO:oejs.AbstractConnector:main: Started ServerConnector@f2cb5a1{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
Exception in thread "main" java.lang.ExceptionInInitializerError
        at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:60)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:890)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:853)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1514)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1476)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:252)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.server.Server.start(Server.java:449)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:416)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at JettyLauncher.main(JettyLauncher.java:127)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not connect to address=(host=localhost)(port=3306)(type=master) : Connection refused (Connection refused)
        at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:568)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:114)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72)
        at gitbucket.core.servlet.Database$.<init>(TransactionFilter.scala:65)
        at gitbucket.core.servlet.Database$.<clinit>(TransactionFilter.scala)
        ... 23 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=localhost)(port=3306)(type=master) : Connection refused (Connection refused)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:175)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:83)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1097)
        at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:494)
        at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)
        at org.mariadb.jdbc.Driver.connect(Driver.java:86)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:533)
        ... 27 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:448)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1089)
        ... 36 more
```

**Comment by kurdtpage** [comment]
Found password under `.gitbucket/database.conf`

**Comment by kurdtpage** [comment]
Restored defaults in this file:
```
db {
  url = "jdbc:h2:${DatabaseHome};MVCC=true"
  #url = "jdbc:mysql://localhost/gitbucket?useUnicode=true&characerEncoding=utf8"
  user = "sa"
  #user = "testuser"
  password = "sa"
  #password = "testpassword"
  connectionTimeout = 30000
  idleTimeout = 600000
  maxLifetime = 1800000
  minimumIdle = 10
  maximumPoolSize = 10
}
```
