### ISSUE TITLE
I can not run any verbs above 2.6.

### ISSUE THREAD

**Issue by sametersoy** [gitbucket/gitbucket#2046]
I can not run any verbs above 2.6.

I'm getting the following error in 424 version. HTTP does not answer https gives illagal character error.

C:\WINDOWS\system32>java -jar  C:\Users\SamgazVs\Desktop\git\gitbucket425.war --port=8080 --gitbucket.home=C:\Users\SamgazVs\Desktop\git\home --temp_dir=C:\Users\SamgazVs\Desktop\git\temp
2018-06-02 15:52:32.481:INFO::main: Logging initialized @219ms to org.eclipse.jetty.util.log.StdErrLog
2018-06-02 15:52:32.637:INFO:oejs.Server:main: jetty-9.4.z-SNAPSHOT
2018-06-02 15:52:53.971:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2018-06-02 15:52:55.518:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2018-06-02 15:52:55.518:INFO:oejs.session:main: No SessionScavenger set, using defaults
2018-06-02 15:52:55.518:INFO:oejs.session:main: Scavenging every 660000ms
15:52:55.799 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
15:52:56.033 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
15:52:56.049 [main] INFO  g.core.servlet.InitializeListener - Check version
15:52:56.049 [main] INFO  g.core.servlet.InitializeListener - Start schema update
2018-06-02 15:52:58.002:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@421a4ee1{/,file:///C:/Users/SamgazVs/Desktop/git/temp/webapp/,UNAVAILABLE}{file:/C:/Users/SamgazVs/Desktop/git/gitbucket425.war}
org.h2.jdbc.JdbcSQLException: Table "ACCOUNT" already exists; SQL statement:|CREATE TABLE PUBLIC.ACCOUNT (USER_NAME VARCHAR(100) NOT NULL, MAIL_ADDRESS VARCHAR(100) NOT NULL, PASSWORD VARCHAR(40) NOT NULL, ADMINISTRATOR BOOLEAN NOT NULL, URL VARCHAR(200), REGISTERED_DATE TIMESTAMP NOT NULL, UPDATED_DATE TIMESTAMP NOT NULL, LAST_LOGIN_DATE TIMESTAMP, IMAGE VARCHAR(100), GROUP_ACCOUNT BOOLEAN NOT NULL, FULL_NAME VARCHAR(100) NOT NULL, REMOVED BOOLEAN) [42101-196]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.command.ddl.CreateTable.update(CreateTable.java:117)
        at org.h2.command.CommandContainer.update(CommandContainer.java:101)
        at org.h2.command.Command.executeUpdate(Command.java:260)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:164)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:150)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at io.github.gitbucket.solidbase.migration.MigrationUtils.updateDatabase(MigrationUtils.java:20)
        at io.github.gitbucket.solidbase.migration.LiquibaseMigration.migrate(LiquibaseMigration.java:93)
        at io.github.gitbucket.solidbase.migration.LiquibaseMigration.migrate(LiquibaseMigration.java:54)
        at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:45)
        at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:29)
        at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1(InitializeListener.scala:70)
        at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1$adapted(InitializeListener.scala:60)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
        at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
        at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:60)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:890)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:853)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1514)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1476)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:252)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.server.Server.start(Server.java:449)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:416)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at JettyLauncher.main(JettyLauncher.java:127)
2018-06-02 15:52:58.080:INFO:oejs.AbstractConnector:main: Started ServerConnector@655523dd{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2018-06-02 15:52:58.080:INFO:oejs.Server:main: Started @25829ms
2018-06-02 15:53:14.793:WARN:oejh.HttpParser:qtp1747585824-17: Illegal character 0x16 in state=START for buffer HeapByteBuffer@b236e4e[p=1,l=517,c=8192,r=516]={\x16<<<\x03\x01\x02\x00\x01\x00\x01\xFc\x03\x03q\x85\xFb\x10\xA5\xEbO...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-06-02 15:53:14.793:WARN:oejh.HttpParser:qtp1747585824-18: Illegal character 0x16 in state=START for buffer HeapByteBuffer@757f4169[p=1,l=517,c=8192,r=516]={\x16<<<\x03\x01\x02\x00\x01\x00\x01\xFc\x03\x03_Oo\xB3\x1c\xEe\xAe...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-06-02 15:53:14.799:WARN:oejh.HttpParser:qtp1747585824-11: Illegal character 0x16 in state=START for buffer HeapByteBuffer@b236e4e[p=1,l=209,c=8192,r=208]={\x16<<<\x03\x01\x00\xCc\x01\x00\x00\xC8\x03\x03\xD7Y\x04/\xE0LF...\x00\x08\xEa\xEa\x00\x1d\x00\x17\x00\x18\xAa\xAa\x00\x01\x00>>>\x08http/1.1uP\x00\x00\x00\x0b\x00\x02...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-06-02 15:53:14.801:WARN:oejh.HttpParser:qtp1747585824-12: Illegal character 0x16 in state=START for buffer HeapByteBuffer@2f87cba0[p=1,l=209,c=8192,r=208]={\x16<<<\x03\x01\x00\xCc\x01\x00\x00\xC8\x03\x03$\xA2i\xB0A\x05\xD4...\x00\x08\x1a\x1a\x00\x1d\x00\x17\x00\x18\xBa\xBa\x00\x01\x00>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-06-02 15:54:21.271:WARN:oejh.HttpParser:qtp1747585824-18: Illegal character 0x16 in state=START for buffer HeapByteBuffer@b236e4e[p=1,l=517,c=8192,r=516]={\x16<<<\x03\x01\x02\x00\x01\x00\x01\xFc\x03\x03m\x88\xE3Pk\xD0\xE4...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-06-02 15:54:21.271:WARN:oejh.HttpParser:qtp1747585824-17: Illegal character 0x16 in state=START for buffer HeapByteBuffer@2f87cba0[p=1,l=517,c=8192,r=516]={\x16<<<\x03\x01\x02\x00\x01\x00\x01\xFc\x03\x03\x1d?\xF6\x8e\xB2\xD9\x19...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-06-02 15:54:21.278:WARN:oejh.HttpParser:qtp1747585824-11: Illegal character 0x16 in state=START for buffer HeapByteBuffer@2f87cba0[p=1,l=209,c=8192,r=208]={\x16<<<\x03\x01\x00\xCc\x01\x00\x00\xC8\x03\x03\xE7-D\x1a\x96\x00\x8b...\x00\x08zz\x00\x1d\x00\x17\x00\x18\xDa\xDa\x00\x01\x00>>>\x08http/1.1uP\x00\x00\x00\x0b\x00\x02...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-06-02 15:54:21.278:WARN:oejh.HttpParser:qtp1747585824-12: Illegal character 0x16 in state=START for buffer HeapByteBuffer@b236e4e[p=1,l=209,c=8192,r=208]={\x16<<<\x03\x01\x00\xCc\x01\x00\x00\xC8\x03\x03-\x04|n\xD8K\x96...\x00\x08\xCa\xCa\x00\x1d\x00\x17\x00\x18ZZ\x00\x01\x00>>>\x08http/1.1uP\x00\x00\x00\x0b\x00\x02...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-06-02 15:54:57.469:WARN:oejh.HttpParser:qtp1747585824-18: Illegal character 0x16 in state=START for buffer HeapByteBuffer@b236e4e[p=1,l=517,c=8192,r=516]={\x16<<<\x03\x01\x02\x00\x01\x00\x01\xFc\x03\x03p\x9c,q\xD63\x98...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-06-02 15:54:57.469:WARN:oejh.HttpParser:qtp1747585824-17: Illegal character 0x16 in state=START for buffer HeapByteBuffer@2f87cba0[p=1,l=517,c=8192,r=516]={\x16<<<\x03\x01\x02\x00\x01\x00\x01\xFc\x03\x03\x07\x81\xE0 \xB7\x18\xB4...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-06-02 15:54:57.473:WARN:oejh.HttpParser:qtp1747585824-11: Illegal character 0x16 in state=START for buffer HeapByteBuffer@757f4169[p=1,l=209,c=8192,r=208]={\x16<<<\x03\x01\x00\xCc\x01\x00\x00\xC8\x03\x03l\x05\x95\xB0\xCeC\xA1...\x00\x08\xDa\xDa\x00\x1d\x00\x17\x00\x18zz\x00\x01\x00>>>\x08http/1.1uP\x00\x00\x00\x0b\x00\x02...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-06-02 15:54:57.474:WARN:oejh.HttpParser:qtp1747585824-12: Illegal character 0x16 in state=START for buffer HeapByteBuffer@2f87cba0[p=1,l=209,c=8192,r=208]={\x16<<<\x03\x01\x00\xCc\x01\x00\x00\xC8\x03\x03\x90\x04\xF4+\xA7\xE94...\x00\x08ZZ\x00\x1d\x00\x17\x00\x18JJ\x00\x01\x00>>>\x08http/1.1uP\x00\x00\x00\x0b\x00\x02...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}

**Comment by dkowis** [comment]
This looks like a character set problem. Is there some way you're running in non utf-8 or something?

**Comment by takezoe** [comment]
Closing old questions.
