### ISSUE TITLE
Broken archive download

### ISSUE THREAD

**Issue by t3rkwd** [gitbucket/gitbucket#2048]
## Issue
**Impacted version**: 4.25.0

**Deployment mode**: standalone app

**Problem description**:
- Can not download the tar.gz file

```
12:39:45.645 [qtp522764626-16] ERROR g.c.c.RepositoryViewerController - Catch unhandled error in request: Request(GET //localhost:8080/root/gitbucket/archive/4.25.0.tar.gz)@589c541f
java.lang.NullPointerException: null
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:138)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:887)
	at gitbucket.core.util.JGitUtil$.getRevCommitFromId(JGitUtil.scala:219)
	at gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$archiveRepository$1(RepositoryViewerController.scala:1148)
	at gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$archiveRepository$1$adapted(RepositoryViewerController.scala:1146)
	at gitbucket.core.util.SyntaxSugars$.using(SyntaxSugars.scala:40)
	at gitbucket.core.controller.RepositoryViewerControllerBase.archive$1(RepositoryViewerController.scala:1146)
	at gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$archiveRepository$9(RepositoryViewerController.scala:1216)
	at gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$archiveRepository$9$adapted(RepositoryViewerController.scala:1212)
	at gitbucket.core.util.SyntaxSugars$.using(SyntaxSugars.scala:15)
	at gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$archiveRepository$8(RepositoryViewerController.scala:1212)
	at gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$archiveRepository$8$adapted(RepositoryViewerController.scala:1211)
	at gitbucket.core.util.SyntaxSugars$.using(SyntaxSugars.scala:15)
	at gitbucket.core.controller.RepositoryViewerControllerBase.archiveRepository(RepositoryViewerController.scala:1211)
	at gitbucket.core.controller.RepositoryViewerControllerBase.archiveRepository$(RepositoryViewerController.scala:1137)
	at gitbucket.core.controller.RepositoryViewerController.archiveRepository(RepositoryViewerController.scala:41)
	at gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$$init$$108(RepositoryViewerController.scala:830)
	at gitbucket.core.util.ReferrerAuthenticator.$anonfun$authenticate$4(Authenticator.scala:95)
	at scala.Option.map(Option.scala:146)

```

- Can not download tag and branch that include "/"
```
12:53:57.767 [qtp522764626-17] ERROR g.c.c.RepositoryViewerController - Catch unhandled error in request: Request(GET //localhost:8080/root/gitbucket/archive/maintenance/4.19/maintenance/4.19.zip)@5fdbef5f
java.lang.NullPointerException: null
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:138)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:887)
	at gitbucket.core.util.JGitUtil$.getRevCommitFromId(JGitUtil.scala:219)
	at gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$archiveRepository$1(RepositoryViewerController.scala:1148)
	at gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$archiveRepository$1$adapted(RepositoryViewerController.scala:1146)
	at gitbucket.core.util.SyntaxSugars$.using(SyntaxSugars.scala:40)
	at gitbucket.core.controller.RepositoryViewerControllerBase.archive$1(RepositoryViewerController.scala:1146)
	at gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$archiveRepository$6(RepositoryViewerController.scala:1192)
	at gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$archiveRepository$6$adapted(RepositoryViewerController.scala:1191)
	at gitbucket.core.util.SyntaxSugars$.using(SyntaxSugars.scala:15)
	at gitbucket.core.controller.RepositoryViewerControllerBase.archiveRepository(RepositoryViewerController.scala:1191)
	at gitbucket.core.controller.RepositoryViewerControllerBase.archiveRepository$(RepositoryViewerController.scala:1137)
	at gitbucket.core.controller.RepositoryViewerController.archiveRepository(RepositoryViewerController.scala:41)
	at gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$$init$$112(RepositoryViewerController.scala:849)
	at gitbucket.core.util.ReferrerAuthenticator.$anonfun$authenticate$4(Authenticator.scala:95)
	at scala.Option.map(Option.scala:146)

```

- An extra "-" is added to the file name
  The file name downloaded from the link[1] is gitbucket-4.25.0-.zip.
  [1] http://localhost:8080/root/gitbucket/archive/4.25.0.zip

**Comment by takezoe** [comment]
@pazaur Correct download URL for tags is: http://<host>/<user>/<repo>/archive/3.4.0.zip

**Comment by pazaur** [comment]
@takezoe 
Sorry, I wasn't clear enough.

We have a repository that have branches with names like "version/3.4.0" or "feature/foo". When we want to download zip file (via Download ZIP button) from such branch the URL for archive is: http://<host>/<group or user>/<repository>/archive/version/3.4.0/**version/**3.4.0.zip

And that produces a zip file with zero content (zero bytes) inside and NPE in logs like I mentioned in previous comment.

When there's single element in branch name like "master" or "3.4.0" then the URL is like you mention: http://<host>/<group or user>/<repository>/archive/master/master.zip and download of archive works like a charm.

This was in version 4.25 and still occurs after an upgrade to 4.26.

**Comment by RadWolfie** [comment]
@pazaur @takezoe The problem is:
`[host]/[group or user]/[repository]/archive/`**`version/3.4.0/version/3.4.0`**`.zip`
Above URL has branch name repeat twice. Even `/archive/master/master.zip` isn't correct. It should be `/archive/master.zip`.

@pazaur If you look at github's "download" zip carefully. You can see the actual link is suppose to be look like below.
Master: `https://github.com/gitbucket/gitbucket/archive/master.zip`
Maintenance/1.11: `https://github.com/gitbucket/gitbucket/archive/maintenance/1.11.zip`
Maintenance/3.10: `https://github.com/gitbucket/gitbucket/archive/maintenance/3.10.zip`

Can you try again with http://[host]/[group or user]/[repository]**/archive/version/3.4.0.zip** in your web browser's address bar?

**Comment by pazaur** [comment]
@RadWolfie @takezoe

Tried different takes on different URLs via web browser. No luck - empty zip file every time.

Below are the traces:
ERROR g.c.c.RepositoryViewerController - Catch unhandled error in request: Request(GET //[host]/[group or user]/[repository]/archive/version/3.4.0/3.4.0.zip)@91b40d
java.lang.NullPointerException: null
java.lang.IllegalStateException: STREAM
        at org.eclipse.jetty.server.Response.getWriter(Response.java:931)
        at org.scalatra.servlet.RichResponse.writer(RichResponse.scala:80)
        at org.scalatra.ScalatraBase$$anonfun$renderPipeline$1.applyOrElse(ScalatraBase.scala:464)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:224)
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:220)
        at org.scalatra.ScalatraBase.loop$1(ScalatraBase.scala:409)

ERROR g.c.c.RepositoryViewerController - Catch unhandled error in request: Request(GET //[host]/[group or user]/[repository]/archive/version/3.4.0.zip)@89482d
java.lang.NullPointerException: null
java.lang.IllegalStateException: STREAM
        at org.eclipse.jetty.server.Response.getWriter(Response.java:931)
        at org.scalatra.servlet.RichResponse.writer(RichResponse.scala:80)
        at org.scalatra.ScalatraBase$$anonfun$renderPipeline$1.applyOrElse(ScalatraBase.scala:464)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:224)
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:220)
		
The only case in gitbucket where zip file is produced is when the branch name is a single element like "master" "foo" etc. The URL then is: //[host]/[group or user]/[repository]/archive/foo/foo.zip . Even when that works then it's not like in github where it should be //[host]/[group or user]/[repository]/archive/foo.zip or //[host]/[group or user]/[repository]/archive/foo/bar.zip if foo is a branch name.

**Comment by takezoe** [comment]
See #2104
