### ISSUE TITLE
'sbt executable' fails -  Download: https://plugins.gitbucket-community.org... - javax.net.ssl.SSLHandshakeException

### ISSUE THREAD

**Issue by uli-heller** [gitbucket/gitbucket#2085]
## Issue
**Impacted version**: 4.26.0 (trying to build it)

**Deployment mode**: N/A

**Problem description**:
- Checkout version 4.26.0 from gitub
- Run `sbt executable`
- See the error below...
- Probably a certificate error?

```
$ sbt executable
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /XXX/gitbucket/project/project
[info] Loading settings from build.sbt,plugins.sbt ...
[info] Loading project definition from /XXX/gitbucket/project
[info] Loading settings from build.sbt ...
[info] Set current project to gitbucket (in build file:/XXX/gitbucket/)
[info] Generating /XXX/gitbucket/target/scala-2.12/resource_managed/main/rebel.xml.
[info] Packaging /XXX/gitbucket/target/scala-2.12/gitbucket_2.12-4.26.0.jar ...
[info] Done packaging.
[info] Packaging /XXX/gitbucket/target/scala-2.12/gitbucket_2.12-4.26.0.war ...
[info] Done packaging.
[info] building executable webapp in /XXX/gitbucket/target/executable
[info] Download: https://plugins.gitbucket-community.org/releases/gitbucket-notifications-plugin/gitbucket-notifications-plugin-gitbucket_4.26.0-1.6.0.jar
[error] javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
[error] 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1937)
[error] 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
[error] 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
[error] 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478)
[error] 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
[error] 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:969)
[error] 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:904)
[error] 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050)
[error] 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
[error] 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
[error] 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
[error] 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
[error] 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[error] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
[error] 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[error] 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
[error] 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[error] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
[error] 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[error] 	at java.net.URL.openStream(URL.java:1038)
[error] 	at $be4fd1e1b47e03b4ef9d$.$anonfun$$sbtdef$6(/XXX/gitbucket/build.sbt:181)
[error] 	at $be4fd1e1b47e03b4ef9d$.$anonfun$$sbtdef$6$adapted(/XXX/gitbucket/build.sbt:175)
[error] 	at $be4fd1e1b47e03b4ef9d$$$Lambda$5967/1210019544.apply(Unknown Source)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at $be4fd1e1b47e03b4ef9d$.$anonfun$$sbtdef$1(/XXX/gitbucket/build.sbt:175)
[error] 	at $be4fd1e1b47e03b4ef9d$$$Lambda$3856/873156359.apply(Unknown Source)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at scala.Function1$$Lambda$991/864511710.apply(Unknown Source)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.internal.util.$tilde$greater$$Lambda$1813/1198973449.apply(Unknown Source)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] 	at sbt.Execute$$Lambda$1830/2005773627.apply(Unknown Source)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:272)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] 	at sbt.Execute$$Lambda$1821/286169474.apply(Unknown Source)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$1828/327574313.apply(Unknown Source)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
[error] 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
[error] 	at sun.security.validator.Validator.validate(Validator.java:260)
[error] 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
[error] 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
[error] 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
[error] 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1460)
[error] 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
[error] 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:969)
[error] 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:904)
[error] 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050)
[error] 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
[error] 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
[error] 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
[error] 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
[error] 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[error] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
[error] 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[error] 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
[error] 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[error] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
[error] 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[error] 	at java.net.URL.openStream(URL.java:1038)
[error] 	at $be4fd1e1b47e03b4ef9d$.$anonfun$$sbtdef$6(/XXX/gitbucket/build.sbt:181)
[error] 	at $be4fd1e1b47e03b4ef9d$.$anonfun$$sbtdef$6$adapted(/XXX/gitbucket/build.sbt:175)
[error] 	at $be4fd1e1b47e03b4ef9d$$$Lambda$5967/1210019544.apply(Unknown Source)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at $be4fd1e1b47e03b4ef9d$.$anonfun$$sbtdef$1(/XXX/gitbucket/build.sbt:175)
[error] 	at $be4fd1e1b47e03b4ef9d$$$Lambda$3856/873156359.apply(Unknown Source)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at scala.Function1$$Lambda$991/864511710.apply(Unknown Source)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.internal.util.$tilde$greater$$Lambda$1813/1198973449.apply(Unknown Source)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] 	at sbt.Execute$$Lambda$1830/2005773627.apply(Unknown Source)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:272)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] 	at sbt.Execute$$Lambda$1821/286169474.apply(Unknown Source)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$1828/327574313.apply(Unknown Source)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
[error] 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
[error] 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
[error] 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
[error] 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
[error] 	at sun.security.validator.Validator.validate(Validator.java:260)
[error] 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
[error] 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
[error] 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
[error] 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1460)
[error] 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
[error] 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:969)
[error] 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:904)
[error] 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050)
[error] 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
[error] 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
[error] 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
[error] 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
[error] 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[error] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
[error] 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[error] 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
[error] 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[error] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
[error] 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[error] 	at java.net.URL.openStream(URL.java:1038)
[error] 	at $be4fd1e1b47e03b4ef9d$.$anonfun$$sbtdef$6(/XXX/gitbucket/build.sbt:181)
[error] 	at $be4fd1e1b47e03b4ef9d$.$anonfun$$sbtdef$6$adapted(/XXX/gitbucket/build.sbt:175)
[error] 	at $be4fd1e1b47e03b4ef9d$$$Lambda$5967/1210019544.apply(Unknown Source)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at $be4fd1e1b47e03b4ef9d$.$anonfun$$sbtdef$1(/XXX/gitbucket/build.sbt:175)
[error] 	at $be4fd1e1b47e03b4ef9d$$$Lambda$3856/873156359.apply(Unknown Source)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at scala.Function1$$Lambda$991/864511710.apply(Unknown Source)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.internal.util.$tilde$greater$$Lambda$1813/1198973449.apply(Unknown Source)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] 	at sbt.Execute$$Lambda$1830/2005773627.apply(Unknown Source)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:272)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] 	at sbt.Execute$$Lambda$1821/286169474.apply(Unknown Source)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$1828/327574313.apply(Unknown Source)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (executable) javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] Total time: 27 s, completed 30.06.2018 07:26:50
```

**Comment by uli-heller** [comment]
My fault, I used jdk-1.8.0_40 for the build. Newer versions of the JDK don't have this issue.
