### ISSUE TITLE
NoSuchFileException at the comparing view before creating pull request

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#2134]
**Impacted version**: 4.27.0

**Deployment mode**: Any

**Problem description**:
Following stacktrace is output to the console at the comparing view before creating pull request. It seems to be caused by upgrading JGit to `5.0.2.201807311906-r` in #2126. It's not output with JGit `5.0.1.201806211838-r`.

It seems to be not throwing Exception, just output stacktrace to the console. So it works well on the surface. I'm not sure whether we should rolled back JGit to `5.0.1.201806211838-r`.

```
21:45:07.013 [qtp1791741888-14] WARN  o.e.j.i.storage.file.RefDirectory - Unable to remove path /Users/takezoe/.gitbucket/repositories/root/gitbucket.git/logs/refs/remote-temp/user1/gitbucket
java.nio.file.NoSuchFileException: /Users/takezoe/.gitbucket/repositories/root/gitbucket.git/logs/refs/remote-temp/user1/gitbucket
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
        at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
        at java.nio.file.Files.delete(Files.java:1126)
        at org.eclipse.jgit.internal.storage.file.RefDirectory.delete(RefDirectory.java:1289)
        at org.eclipse.jgit.internal.storage.file.RefDirectory.delete(RefDirectory.java:1273)
        at org.eclipse.jgit.internal.storage.file.RefDirectory.delete(RefDirectory.java:694)
        at org.eclipse.jgit.internal.storage.file.RefDirectoryUpdate.doDelete(RefDirectoryUpdate.java:153)
        at org.eclipse.jgit.lib.RefUpdate$2.execute(RefUpdate.java:680)
        at org.eclipse.jgit.lib.RefUpdate.updateImpl(RefUpdate.java:774)
        at org.eclipse.jgit.lib.RefUpdate.delete(RefUpdate.java:677)
        at org.eclipse.jgit.lib.RefUpdate.delete(RefUpdate.java:649)
        at gitbucket.core.service.MergeService.$anonfun$tryMergeRemote$1(MergeService.scala:120)
        at gitbucket.core.util.SyntaxSugars$.using(SyntaxSugars.scala:40)
        at gitbucket.core.service.MergeService.tryMergeRemote(MergeService.scala:94)
        at gitbucket.core.service.MergeService.tryMergeRemote$(MergeService.scala:86)
        at gitbucket.core.controller.PullRequestsController.tryMergeRemote(PullRequestsController.scala:24)
        at gitbucket.core.service.MergeService.checkConflict(MergeService.scala:136)
        at gitbucket.core.service.MergeService.checkConflict$(MergeService.scala:128)
        at gitbucket.core.controller.PullRequestsController.checkConflict(PullRequestsController.scala:24)
        at gitbucket.core.controller.PullRequestsControllerBase.$anonfun$$init$$119(PullRequestsController.scala:706)
        at gitbucket.core.util.LockUtil$.$anonfun$lock$1(LockUtil.scala:30)
        at gitbucket.core.util.SyntaxSugars$.defining(SyntaxSugars.scala:12)
        at gitbucket.core.util.LockUtil$.lock(LockUtil.scala:27)
        at gitbucket.core.controller.PullRequestsControllerBase.$anonfun$$init$$118(PullRequestsController.scala:700)
        at gitbucket.core.util.SyntaxSugars$.using(SyntaxSugars.scala:44)
        at gitbucket.core.controller.PullRequestsControllerBase.$anonfun$$init$$117(PullRequestsController.scala:695)
        at scala.Option.map(Option.scala:146)
        at gitbucket.core.controller.PullRequestsControllerBase.$anonfun$$init$$116(PullRequestsController.scala:691)
        at scala.Option.flatMap(Option.scala:171)
        at gitbucket.core.controller.PullRequestsControllerBase.$anonfun$$init$$112(PullRequestsController.scala:682)
        at gitbucket.core.util.ReadableUsersAuthenticator.$anonfun$authenticate$6(Authenticator.scala:118)
        at scala.Option.map(Option.scala:146)
        at gitbucket.core.util.ReadableUsersAuthenticator.authenticate(Authenticator.scala:115)
        at gitbucket.core.util.ReadableUsersAuthenticator.readableUsersOnly(Authenticator.scala:107)
        at gitbucket.core.util.ReadableUsersAuthenticator.readableUsersOnly$(Authenticator.scala:107)
        at gitbucket.core.controller.PullRequestsController.readableUsersOnly(PullRequestsController.scala:24)
        at gitbucket.core.controller.PullRequestsControllerBase.$anonfun$$init$$111(PullRequestsController.scala:677)
        at gitbucket.core.controller.ControllerBase.$anonfun$ajaxGet$1(ControllerBase.scala:100)
        at org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:280)
        at org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:274)
        at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:183)
        at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:169)
        at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:34)
        at org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:273)
        at org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:272)
        at gitbucket.core.controller.ControllerBase.org$scalatra$json$JsonSupport$$super$invoke(ControllerBase.scala:34)
        at org.scalatra.json.JsonSupport.$anonfun$invoke$1(JsonSupport.scala:90)
        at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:183)
        at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:169)
        at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:34)
        at org.scalatra.json.JsonSupport.invoke(JsonSupport.scala:84)
        at org.scalatra.json.JsonSupport.invoke$(JsonSupport.scala:83)
        at gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:34)
        at org.scalatra.ScalatraBase.$anonfun$runRoutes$3(ScalatraBase.scala:248)
        at scala.Option.flatMap(Option.scala:171)
        at org.scalatra.ScalatraBase.$anonfun$runRoutes$1(ScalatraBase.scala:246)
        at scala.collection.immutable.Stream.flatMap(Stream.scala:490)
        at org.scalatra.ScalatraBase.runRoutes(ScalatraBase.scala:245)
        at org.scalatra.ScalatraBase.runRoutes$(ScalatraBase.scala:243)
        at gitbucket.core.controller.ControllerBase.runRoutes(ControllerBase.scala:34)
        at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:169)
        at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:199)
        at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
        at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
        at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:34)
        at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:79)
        at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:77)
        at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:34)
        at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:59)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
        at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
        at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:34)
        at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:58)
        at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:56)
        at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:34)
        at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
        at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
        at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:34)
        at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:53)
        at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:46)
        at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:34)
        at org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:170)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
        at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
        at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:34)
        at org.scalatra.FlashMapSupport.handle(FlashMap.scala:145)
        at org.scalatra.FlashMapSupport.handle$(FlashMap.scala:144)
        at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:34)
        at org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
        at org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
        at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:72)
        at gitbucket.core.servlet.CompositeScalatraFilter.$anonfun$doFilter$2(CompositeScalatraFilter.scala:52)
        at gitbucket.core.servlet.CompositeScalatraFilter.$anonfun$doFilter$2$adapted(CompositeScalatraFilter.scala:49)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.collection.generic.TraversableForwarder.foreach(TraversableForwarder.scala:35)
        at scala.collection.generic.TraversableForwarder.foreach$(TraversableForwarder.scala:35)
        at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:44)
        at gitbucket.core.servlet.CompositeScalatraFilter.doFilter(CompositeScalatraFilter.scala:49)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at gitbucket.core.servlet.PluginControllerFilter.doFilter(PluginControllerFilter.scala:49)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at org.scalatra.ScalatraFilter.$anonfun$doNotFound$1(ScalatraFilter.scala:79)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at org.scalatra.ScalatraBase.$anonfun$executeRoutes$5(ScalatraBase.scala:172)
        at scala.Option.getOrElse(Option.scala:121)
        at org.scalatra.ScalatraBase.$anonfun$executeRoutes$3(ScalatraBase.scala:172)
        at scala.Option.getOrElse(Option.scala:121)
        at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:172)
        at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:199)
        at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
        at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
        at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:34)
        at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:79)
        at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:77)
        at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:34)
        at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:59)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
        at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
        at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:34)
        at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:58)
        at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:56)
        at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:34)
        at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
        at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
        at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:34)
        at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:53)
        at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:46)
        at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:34)
        at org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:170)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
        at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
        at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:34)
        at org.scalatra.FlashMapSupport.handle(FlashMap.scala:145)
        at org.scalatra.FlashMapSupport.handle$(FlashMap.scala:144)
        at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:34)
        at org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
        at org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
        at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:72)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1(TransactionFilter.scala:39)
        at gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1$adapted(TransactionFilter.scala:30)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
        at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
        at gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:30)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1629)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:564)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
        at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by takezoe** [comment]
https://github.com/eclipse/jgit/commit/5a8ad44208c8b711077b9235839b66cd50803ede

**Comment by takezoe** [comment]
I reverted to JGit 5.0.1.201806211838-r for GitBucket 4.28. We need to fix our code which is pointed by this warning log before upgrading to JGit 5.0.2.201807311906-r.

**Comment by takezoe** [comment]
Cool!

**Comment by uli-heller** [comment]
The bug is gone. Compiling with jgit-5.1.1 produces a couple of deprecation warnings. I'll fix these and create a pull request.
