### ISSUE TITLE
ClassNotFoundException: org.eclipse.jetty.server.Handler when launching from IDE, fixed by removing "jetty-webapp" dependency "provided" tag in build.sbt

### ISSUE THREAD

**Issue by marvinsec** [gitbucket/gitbucket#2154]
Impacted version: reproduced on 4.23.1 but code hasn't changed until latest version

Deployment mode: standalone with embedded jetty using provided JettyLauncher.java

Problem description: 
when launching JettyLauncher.main() from IDE, the following error is produced:

`java.lang.NoClassDefFoundError: org/eclipse/jetty/server/Handler
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.Handler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" 
Process finished with exit code 1
`

I have fixed this error by removing the "provided" tag from jetty-webapp dependency, but I would appreciate assistance about whether this has occurred on other environments, and about possible reasons

**Comment by takezoe** [comment]
JettyLauncher and jetty specific libraries are embedded at the build time to make an executable jar file (gitbucket.war is a war file, but it's also an executable jar file at the same time). It's not intended to use for running from IDE. I usually use `sbt ~jetty:run` to run GitBucket on the command line in development.

**Comment by marvinsec** [comment]
That's kind of what I had in mind. I resorted to running from the IDE because I wanted to turn on debugging and run the code step by step, however, scala's cli debugger sdb ruined my life 😆, Thanks for the quick response.

**Comment by marvinsec** [comment]
That's great, haven't thought about it, so add debug options to "debug in jetty", then ~jetty:debug, correct?

**Comment by takezoe** [comment]
Ah, I found that you can give `-jvm-debug` option in recent versions of sbt as:
```
$ sbt -jvm-debug 5005 ~jetty:start
```

**Comment by marvinsec** [comment]
I didn't know about that, that's great. 
sure, and thanks for the cool tips.
