### ISSUE TITLE
java.lang.IllegalStateException: Multiple (2) registered IoServiceFactoryFactory instances detected

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#2168]
In the current master branch, following exception occurs on startup. Is this caused by MINA upgrade in #2162?
```
java.lang.IllegalStateException: Multiple (2) registered IoServiceFactoryFactory instances detected. Please use -Dorg.apache.sshd.common.io.IoServiceFactoryFactory=...factory class.. to select one or remove the extra providers from the classpath
	at org.apache.sshd.common.io.DefaultIoServiceFactoryFactory.tryLoad(DefaultIoServiceFactoryFactory.java:136)
	at org.apache.sshd.common.io.DefaultIoServiceFactoryFactory.newInstance(DefaultIoServiceFactoryFactory.java:92)
	at org.apache.sshd.common.io.DefaultIoServiceFactoryFactory.getIoServiceProvider(DefaultIoServiceFactoryFactory.java:64)
	at org.apache.sshd.common.io.DefaultIoServiceFactoryFactory.create(DefaultIoServiceFactoryFactory.java:51)
	at org.apache.sshd.common.helpers.AbstractFactoryManager.getIoServiceFactory(AbstractFactoryManager.java:108)
	at org.apache.sshd.server.SshServer.createAcceptor(SshServer.java:389)
	at org.apache.sshd.server.SshServer.start(SshServer.java:292)
	at gitbucket.core.ssh.SshServer$.start(SshServerListener.scala:36)
	at gitbucket.core.ssh.SshServerListener.$anonfun$contextInitialized$2(SshServerListener.scala:69)
	at gitbucket.core.ssh.SshServerListener.$anonfun$contextInitialized$2$adapted(SshServerListener.scala:68)
	at scala.Option.foreach(Option.scala:257)
	at gitbucket.core.ssh.SshServerListener.$anonfun$contextInitialized$1(SshServerListener.scala:68)
	at gitbucket.core.ssh.SshServerListener.$anonfun$contextInitialized$1$adapted(SshServerListener.scala:67)
	at scala.Option.foreach(Option.scala:257)
	at gitbucket.core.ssh.SshServerListener.contextInitialized(SshServerListener.scala:67)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:890)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:853)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1501)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1463)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:167)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:452)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:419)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.runner.Runner.run(Runner.java:518)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:559)
```

**Comment by takezoe** [comment]
@uli-heller Have you got this error after #2162 merged?

**Comment by uli-heller** [comment]
@takezoe I don't remember unfortunately. All tests passed but I didn't check the logs. I'll rebase the pull request to v4.29.0 and double-check... Will probably take just an hour or two.

**Comment by takezoe** [comment]
Thanks. We might have to rolled back #2162.

**Comment by uli-heller** [comment]
I did a test based on 4.29.0. After applying #2162, I can see the exception. So I agree: We'll have to roll back #2162. I'll submit an improved pull request afterwards maybe in a couple of days/weeks. Sorry.
