### ISSUE TITLE
"sbt executable" fails for master: java.io.FileNotFoundException

### ISSUE THREAD

**Issue by uli-heller** [gitbucket/gitbucket#2176]
```
uli@ulinuc:~/git/forked/gitbucket$ sbt.sh executable
[info] Loading settings for project gitbucket-build-build from plugins.sbt ...
[info] Loading project definition from /home/uli/git/forked/gitbucket/project/project
[info] Loading settings for project gitbucket-build from build.sbt,plugins.sbt ...
[info] Loading project definition from /home/uli/git/forked/gitbucket/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to gitbucket (in build file:/home/uli/git/forked/gitbucket/)
[info] Packaging /home/uli/git/forked/gitbucket/target/scala-2.12/gitbucket_2.12-4.30.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Packaging /home/uli/git/forked/gitbucket/target/scala-2.12/gitbucket_2.12-4.30.0-SNAPSHOT.war ...
[info] Done packaging.
[info] building executable webapp in /home/uli/git/forked/gitbucket/target/executable
[info] Download: https://plugins.gitbucket-community.org/releases/gitbucket-notifications-plugin/gitbucket-notifications-plugin-gitbucket_4.30.0-SNAPSHOT-1.6.0.jar
[error] java.io.FileNotFoundException: https://plugins.gitbucket-community.org/releases/gitbucket-notifications-plugin/gitbucket-notifications-plugin-gitbucket_4.30.0-SNAPSHOT-1.6.0.jar
[error] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
[error] 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
[error] 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484)
[error] 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[error] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481)
[error] 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
[error] 	at java.net.URL.openStream(URL.java:1045)
[error] 	at $8195b16581cb29fa27c4$.$anonfun$$sbtdef$6(/home/uli/git/forked/gitbucket/build.sbt:168)
[error] 	at $8195b16581cb29fa27c4$.$anonfun$$sbtdef$6$adapted(/home/uli/git/forked/gitbucket/build.sbt:162)
[error] 	at scala.collection.immutable.List.foreach(List.scala:388)
[error] 	at $8195b16581cb29fa27c4$.$anonfun$$sbtdef$1(/home/uli/git/forked/gitbucket/build.sbt:162)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (executable) java.io.FileNotFoundException: https://plugins.gitbucket-community.org/releases/gitbucket-notifications-plugin/gitbucket-notifications-plugin-gitbucket_4.30.0-SNAPSHOT-1.6.0.jar
[error] Total time: 129 s, completed 31.10.2018 08:27:29
```

**Comment by takezoe** [comment]
This is a current restriction of [the plugin build farm](https://plugins.gitbucket-community.org/). After creating `4.30.0` tag, it will work. If you need to create an executable war at the moment, try to update version in `build.sbt` to `4.29.0` then run `sbt executable`.

**Comment by uli-heller** [comment]
... or temporarily truncate the file src/main/resources/bundle-plugins.txt:

```
uli@ulinuc:~/git/forked/gitbucket$ > src/main/resources/bundle-plugins.txt 
uli@ulinuc:~/git/forked/gitbucket$ sbt.sh executable
[info] Loading settings for project gitbucket-build-build from plugins.sbt ...
[info] Loading project definition from /home/uli/git/forked/gitbucket/project/project
[info] Loading settings for project gitbucket-build from build.sbt,plugins.sbt ...
[info] Loading project definition from /home/uli/git/forked/gitbucket/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to gitbucket (in build file:/home/uli/git/forked/gitbucket/)
[info] Updating root
https://repo1.maven.org/maven2/com/nimbusds/lang-tag/maven-metadata.xml
  No new update since 2018-10-08 20:27:34
https://repo1.maven.org/maven2/com/nimbusds/nimbus-jose-jwt/maven-metadata.xml
  No new update since 2018-10-26 20:53:09
https://repo1.maven.org/maven2/net/minidev/json-smart/maven-metadata.xml
  No new update since 2017-03-26 10:15:35
[info] Resolved root dependencies
[info] Packaging /home/uli/git/forked/gitbucket/target/scala-2.12/gitbucket_2.12-4.30.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Packaging /home/uli/git/forked/gitbucket/target/scala-2.12/gitbucket_2.12-4.30.0-SNAPSHOT.war ...
[info] Done packaging.
[info] building executable webapp in /home/uli/git/forked/gitbucket/target/executable
[info] built executable webapp /home/uli/git/forked/gitbucket/target/executable/gitbucket.war
[success] Total time: 59 s, completed 02.11.2018 09:38:14
```

**Comment by uli-heller** [comment]
@takezoe Any plans on fixing this? Or shall we close the issue or mark it "low prio"?

**Comment by takezoe** [comment]
I don't have good idea for fixing this issue. Actually, this error is temporary during development. Anyway I want to keep this issue because I think that the current default plugin bundling mechanism is not good solution.

**Comment by SIkebe** [comment]
@takezoe Is this issue still relevant? The plugin build farm had been removed a while ago.

**Comment by takezoe** [comment]
Yeah, we can close this.
