### ISSUE TITLE
GitBucket hangs on the PR page created by web API

### ISSUE THREAD

**Issue by SIkebe** [gitbucket/gitbucket#2235]
## Issue
**Impacted version**: 4.30.1

**Deployment mode**: standalone app

**Problem description**:
1. Create new repository with "Initialize this repository with a README".
2. Create develop branch from master.
3. Edit `README.md` on develop.
4. Send POST request via Postman

```
POST /api/v3/repos/root/prtest/pulls HTTP/1.1
Host: localhost:8080
Content-Type: application/json
{
  "title": "Amazing new feature",
  "body": "Please pull this in!",
  "head": "develop",
  "base": "master"
}
```

5. GitBucket hangs on the pull request page. And there is no notification or activity update.
![prtest](https://user-images.githubusercontent.com/17608272/50535022-59b4f500-0b88-11e9-89b7-dad998146292.PNG)

Response
```json
"{\"number\":3,\"state\":\"open\",\"updated_at\":\"2018-12-29T05:41:40Z\",\"created_at\":\"2018-12-29T05:41:40Z\",\"head\":{\"sha\":\"0e57d504c2451f9da3d0df9f3590b137749590c4\",\"ref\":\"develop\",\"repo\":{\"name\":\"prtest\",\"full_name\":\"root/prtest\",\"description\":\"\",\"watchers\":0,\"forks\":0,\"private\":false,\"default_branch\":\"master\",\"owner\":{\"login\":\"root\",\"email\":\"root@localhost\",\"type\":\"User\",\"site_admin\":true,\"created_at\":\"2018-06-03T06:34:06Z\",\"id\":0,\"url\":\"http://localhost:8080/api/v3/users/root\",\"html_url\":\"http://localhost:8080/root\",\"avatar_url\":\"http://localhost:8080/root/_avatar\"},\"id\":0,\"forks_count\":0,\"watchers_count\":0,\"url\":\"http://localhost:8080/api/v3/repos/root/prtest\",\"http_url\":\"http://localhost:8080/git/root/prtest.git\",\"clone_url\":\"http://localhost:8080/git/root/prtest.git\",\"html_url\":\"http://localhost:8080/root/prtest\"},\"label\":\"develop\",\"user\":{\"login\":\"root\",\"email\":\"root@localhost\",\"type\":\"User\",\"site_admin\":true,\"created_at\":\"2018-06-03T06:34:06Z\",\"id\":0,\"url\":\"http://localhost:8080/api/v3/users/root\",\"html_url\":\"http://localhost:8080/root\",\"avatar_url\":\"http://localhost:8080/root/_avatar\"}},\"base\":{\"sha\":\"e3c4bd865ec27bb1eecba39cfc1c25c3d4f1bbd6\",\"ref\":\"master\",\"repo\":{\"name\":\"prtest\",\"full_name\":\"root/prtest\",\"description\":\"\",\"watchers\":0,\"forks\":0,\"private\":false,\"default_branch\":\"master\",\"owner\":{\"login\":\"root\",\"email\":\"root@localhost\",\"type\":\"User\",\"site_admin\":true,\"created_at\":\"2018-06-03T06:34:06Z\",\"id\":0,\"url\":\"http://localhost:8080/api/v3/users/root\",\"html_url\":\"http://localhost:8080/root\",\"avatar_url\":\"http://localhost:8080/root/_avatar\"},\"id\":0,\"forks_count\":0,\"watchers_count\":0,\"url\":\"http://localhost:8080/api/v3/repos/root/prtest\",\"http_url\":\"http://localhost:8080/git/root/prtest.git\",\"clone_url\":\"http://localhost:8080/git/root/prtest.git\",\"html_url\":\"http://localhost:8080/root/prtest\"},\"label\":\"master\",\"user\":{\"login\":\"root\",\"email\":\"root@localhost\",\"type\":\"User\",\"site_admin\":true,\"created_at\":\"2018-06-03T06:34:06Z\",\"id\":0,\"url\":\"http://localhost:8080/api/v3/users/root\",\"html_url\":\"http://localhost:8080/root\",\"avatar_url\":\"http://localhost:8080/root/_avatar\"}},\"merged\":false,\"title\":\"Amazing new feature\",\"body\":\"Please pull this in!\",\"user\":{\"login\":\"root\",\"email\":\"root@localhost\",\"type\":\"User\",\"site_admin\":true,\"created_at\":\"2018-06-03T06:34:06Z\",\"id\":0,\"url\":\"http://localhost:8080/api/v3/users/root\",\"html_url\":\"http://localhost:8080/root\",\"avatar_url\":\"http://localhost:8080/root/_avatar\"},\"labels\":[],\"id\":0,\"html_url\":\"http://localhost:8080/root/prtest/pull/3\",\"url\":\"http://localhost:8080/api/v3/repos/root/prtest/pulls/3\",\"commits_url\":\"http://localhost:8080/api/v3/repos/root/prtest/pulls/3/commits\",\"review_comments_url\":\"http://localhost:8080/api/v3/repos/root/prtest/pulls/3/comments\",\"review_comment_url\":\"http://localhost:8080/api/v3/repos/root/prtest/pulls/comments/{number}\",\"comments_url\":\"http://localhost:8080/api/v3/repos/root/prtest/issues/3/comments\",\"statuses_url\":\"http://localhost:8080/api/v3/repos/root/prtest/statuses/0e57d504c2451f9da3d0df9f3590b137749590c4\"}"
```

Log
```
14:41:49.779 [qtp922872566-19] ERROR g.c.c.PullRequestsController - Catch unhandled error in request: Request(GET //localhost:8080/root/prtest/pull/3/mergeguide?_=1546062109507)@749dccda
java.lang.NullPointerException: null
        at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:138)
        at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:887)
        at org.eclipse.jgit.merge.Merger.merge(Merger.java:250)
        at org.eclipse.jgit.merge.Merger.merge(Merger.java:219)
        at org.eclipse.jgit.merge.ThreeWayMerger.merge(ThreeWayMerger.java:129)
        at gitbucket.core.service.MergeService$MergeCacheInfo.checkConflictForce(MergeService.scala:467)
        at gitbucket.core.service.MergeService$MergeCacheInfo.$anonfun$checkConflict$2(MergeService.scala:461)
        at scala.Option.getOrElse(Option.scala:138)
        at gitbucket.core.service.MergeService$MergeCacheInfo.checkConflict(MergeService.scala:461)
        at gitbucket.core.service.MergeService.$anonfun$checkConflict$1(MergeService.scala:39)
        at gitbucket.core.util.SyntaxSugars$.using(SyntaxSugars.scala:40)
        at gitbucket.core.service.MergeService.checkConflict(MergeService.scala:38)
        at gitbucket.core.service.MergeService.checkConflict$(MergeService.scala:37)
        at gitbucket.core.controller.PullRequestsController.checkConflict(PullRequestsController.scala:24)
        at gitbucket.core.controller.PullRequestsControllerBase.$anonfun$$init$$24(PullRequestsController.scala:215)
        at gitbucket.core.util.LockUtil$.$anonfun$lock$1(LockUtil.scala:30)
        at gitbucket.core.util.SyntaxSugars$.defining(SyntaxSugars.scala:12)
        at gitbucket.core.util.LockUtil$.lock(LockUtil.scala:27)
        at gitbucket.core.controller.PullRequestsControllerBase.$anonfun$$init$$23(PullRequestsController.scala:215)
        at scala.Option.map(Option.scala:163)
        at gitbucket.core.controller.PullRequestsControllerBase.$anonfun$$init$$22(PullRequestsController.scala:212)
        at gitbucket.core.controller.PullRequestsControllerBase.$anonfun$$init$$22$adapted(PullRequestsController.scala:209)
        at scala.Option.flatMap(Option.scala:188)
        at gitbucket.core.controller.PullRequestsControllerBase.$anonfun$$init$$21(PullRequestsController.scala:209)
        at gitbucket.core.util.ReferrerAuthenticator.$anonfun$authenticate$4(Authenticator.scala:95)
        at scala.Option.map(Option.scala:163)
        at gitbucket.core.util.ReferrerAuthenticator.authenticate(Authenticator.scala:93)
        at gitbucket.core.util.ReferrerAuthenticator.referrersOnly(Authenticator.scala:87)
        at gitbucket.core.util.ReferrerAuthenticator.referrersOnly$(Authenticator.scala:87)
        at gitbucket.core.controller.PullRequestsController.referrersOnly(PullRequestsController.scala:24)
        at gitbucket.core.controller.PullRequestsControllerBase.$anonfun$$init$$20(PullRequestsController.scala:207)
        at gitbucket.core.controller.ControllerBase.$anonfun$ajaxGet$1(ControllerBase.scala:100)
        at org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:280)
        at org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:274)
        at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:183)
        at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:169)
        at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:34)
        at org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:273)
        at org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:272)
        at gitbucket.core.controller.ControllerBase.org$scalatra$json$JsonSupport$$super$invoke(ControllerBase.scala:34)
        at org.scalatra.json.JsonSupport.$anonfun$invoke$1(JsonSupport.scala:90)
        at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:183)
        at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:169)
        at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:34)
        at org.scalatra.json.JsonSupport.invoke(JsonSupport.scala:84)
        at org.scalatra.json.JsonSupport.invoke$(JsonSupport.scala:83)
        at gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:34)
        at org.scalatra.ScalatraBase.$anonfun$runRoutes$3(ScalatraBase.scala:248)
        at scala.Option.flatMap(Option.scala:188)
        at org.scalatra.ScalatraBase.$anonfun$runRoutes$1(ScalatraBase.scala:246)
        at scala.collection.immutable.Stream.flatMap(Stream.scala:493)
        at org.scalatra.ScalatraBase.runRoutes(ScalatraBase.scala:245)
        at org.scalatra.ScalatraBase.runRoutes$(ScalatraBase.scala:243)
        at gitbucket.core.controller.ControllerBase.runRoutes(ControllerBase.scala:34)
        at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:169)
        at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:199)
        at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
        at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
        at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:34)
        at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:79)
        at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:77)
        at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:34)
        at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:59)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
        at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
        at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:34)
        at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:58)
        at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:56)
        at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:34)
        at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
        at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
        at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:34)
        at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:53)
        at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:46)
        at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:34)
        at org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:170)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
        at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
        at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:34)
        at org.scalatra.FlashMapSupport.handle(FlashMap.scala:145)
        at org.scalatra.FlashMapSupport.handle$(FlashMap.scala:144)
        at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:34)
        at org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
        at org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
        at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:72)
        at gitbucket.core.servlet.CompositeScalatraFilter.$anonfun$doFilter$2(CompositeScalatraFilter.scala:52)
        at gitbucket.core.servlet.CompositeScalatraFilter.$anonfun$doFilter$2$adapted(CompositeScalatraFilter.scala:49)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.generic.TraversableForwarder.foreach(TraversableForwarder.scala:38)
        at scala.collection.generic.TraversableForwarder.foreach$(TraversableForwarder.scala:38)
        at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:47)
        at gitbucket.core.servlet.CompositeScalatraFilter.doFilter(CompositeScalatraFilter.scala:49)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at gitbucket.core.servlet.PluginControllerFilter.doFilter(PluginControllerFilter.scala:49)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.scalatra.ScalatraFilter.$anonfun$doNotFound$1(ScalatraFilter.scala:79)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.scalatra.ScalatraBase.$anonfun$executeRoutes$5(ScalatraBase.scala:172)
        at scala.Option.getOrElse(Option.scala:138)
        at org.scalatra.ScalatraBase.$anonfun$executeRoutes$3(ScalatraBase.scala:172)
        at scala.Option.getOrElse(Option.scala:138)
        at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:172)
        at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:199)
        at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
        at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
        at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:34)
        at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:79)
        at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:77)
        at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:34)
        at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:59)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
        at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
        at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:34)
        at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:58)
        at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:56)
        at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:34)
        at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
        at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
        at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:34)
        at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:53)
        at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:46)
        at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:34)
        at org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:170)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
        at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
        at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:34)
        at org.scalatra.FlashMapSupport.handle(FlashMap.scala:145)
        at org.scalatra.FlashMapSupport.handle$(FlashMap.scala:144)
        at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:34)
        at org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
        at org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
        at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:72)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1(TransactionFilter.scala:39)
        at gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1$adapted(TransactionFilter.scala:30)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
        at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
        at gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:30)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:502)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by SIkebe** [comment]
I also tried this, but result was the same as above.
```
POST /api/v3/repos/root/prtest/pulls HTTP/1.1
Host: localhost:8080
Content-Type: application/json
{
  "title": "Amazing new feature",
  "body": "Please pull this in!",
  "head": "root:develop",
  "base": "master"
}
```
