### ISSUE TITLE
Exception in creating new file on the browser

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#2283]
### Before submitting an issue to GitBucket I have first:

- [] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [] searched for similar already existing issue
- [] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki) 

*(if you have performed all the above, remove the paragraph and continue describing the issue with template below)*

## Issue
**Impacted version**: 4.31.0

When create new file on the browser, an exception below is thrown:
```
org.postgresql.util.PSQLException: ERROR: insert or update on table "activity" violates foreign key constraint "idx_activity_fk1"
  Detail: Key (activity_user_name)=(GitBucket Admin) is not present in table "account".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.$anonfun$run$11(JdbcActionComponent.scala:509)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:371)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:366)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:433)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:500)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.run(JdbcActionComponent.scala:506)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:29)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:26)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingInsertInvoker.insert(BlockingProfile.scala:125)
	at gitbucket.core.service.ActivityService.recordPushActivity(ActivityService.scala:225)
	at gitbucket.core.service.ActivityService.recordPushActivity$(ActivityService.scala:218)
	at gitbucket.core.controller.RepositoryViewerController.recordPushActivity(RepositoryViewerController.scala:41)
	at gitbucket.core.service.RepositoryCommitFileService.$anonfun$_commitFile$2(RepositoryCommitFileService.scala:172)
	at gitbucket.core.util.SyntaxSugars$.using(SyntaxSugars.scala:40)
	at gitbucket.core.service.RepositoryCommitFileService.$anonfun$_commitFile$1(RepositoryCommitFileService.scala:120)
```

**Comment by takezoe** [comment]
@kounoike Is this error related to #2264?

**Comment by kounoike** [comment]
@takezoe I can't reproduce this issue at.

- current master
- H2 database
- clean .gitbucket directory 

and, I didn't modify activity related files in #2264.

**Comment by kounoike** [comment]
Oops, the default root accounts fullName is "root". So, it through the bug... It's related in #2265. I will write fix PR.
