### ISSUE TITLE
Webhooks with X-Hub-Signature fail on Java 11

### ISSUE THREAD

**Issue by Sherpard** [gitbucket/gitbucket#2289]
### Before submitting an issue to GitBucket I have first:

- [X] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [X] searched for similar already existing issue
- [X] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki) 

*(if you have performed all the above, remove the paragraph and continue describing the issue with template below)*

## Issue
**Impacted version**:  4.31.1 

**Deployment mode**: Docker image from https://github.com/f99aq8ove/docker-gitbucket

**Problem description**:
Using f99aq8ove docker image, relies on the the tag openjdk:jre, that right now targets Java 11.

Everytime a webhook is fired and has a X-Hub-Token the following exception rises on the console

```java 
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
     at fr.brouillard.oss.security.xhub.XHub$XHubConverter$4.convert(XHub.java:68)
     at fr.brouillard.oss.security.xhub.XHub.generateXHubToken(XHub.java:89)
     at fr.brouillard.oss.security.xhub.XHub.generateHeaderXHubToken(XHub.java:76)
     at gitbucket.core.service.WebHookService.$anonfun$callWebHook$2(WebHookService.scala:272)
     at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
     at scala.util.Success.$anonfun$map$1(Try.scala:255)
     at scala.util.Success.map(Try.scala:213)
     at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
     at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
     at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
     at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
     at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
     at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
     at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
     at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
     at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

I've searching around and found out that [Java 9 marked several JavaEE classes for removal](http://openjdk.java.net/jeps/320) that includes javax/xml/bind for the sake of modularization

Java removed such classes at version 11, so a *NoClassDefFoundError* is thrown.

I don't know if there should be a note on the wiki, a workaround for newer JRE versions, or what should be done.

**Comment by McFoggy** [comment]
indeed, you're right that the token feature is not java9/11 compliant.

I have just corrected the [xhub4j](https://github.com/McFoggy/xhub4j) library not to rely on jaxb anymore, I will release a new version today.

But until gitbucket integrates this new version, the only solution is to stay on a JDK 8 if you use this functionnality.
