### ISSUE TITLE
Uploading an SVG results in an uncaught exception

### ISSUE THREAD

**Issue by charles-cooper** [gitbucket/gitbucket#2295]
## Issue
**Impacted version**: 4.31.1

**Deployment mode**: docker (https://hub.docker.com/r/f99aq8ove/gitbucket/) behind an nginx proxy

**Problem description**:
Uploading an SVG for an avatar results in a uncaught exception (propagated as an "Internal Server Error"). From the (truncated) logs,
```
gitbucket_1  | 05:49:12.059 [qtp458209687-16] ERROR g.core.controller.AccountController - Catch unhandled error in request: Request(POST //127.0.0.1:3021/<USER>/_edit)@1fd9c337
gitbucket_1  | net.coobird.thumbnailator.tasks.UnsupportedFormatException: No suitable ImageReader found for /root/.gitbucket/tmp/_upload/node0qpxwpcaw9cmw1kdp939psrct37/15542705276766rZRnMqVmi.
gitbucket_1  | 	at net.coobird.thumbnailator.tasks.io.FileImageSource.read(Unknown Source)
gitbucket_1  | 	at net.coobird.thumbnailator.tasks.SourceSinkThumbnailTask.read(Unknown Source)
gitbucket_1  | 	at net.coobird.thumbnailator.Thumbnailator.createThumbnail(Unknown Source)
gitbucket_1  | 	at net.coobird.thumbnailator.Thumbnails$Builder.toFile(Unknown Source)
gitbucket_1  | 	at gitbucket.core.controller.AccountManagementControllerBase.$anonfun$updateImage$3(ControllerBase.scala:343)
gitbucket_1  | 	at gitbucket.core.controller.AccountManagementControllerBase.$anonfun$updateImage$3$adapted(ControllerBase.scala:334)
gitbucket_1  | 	at scala.Option.foreach(Option.scala:274)
```

This could probably be fixed by catching the exception and returning an error message stating what the accepted image formats are.

**Comment by takezoe** [comment]
Probably, this issue has been fixed in #2318.
