### ISSUE TITLE
HTTP 503 ERROR

### ISSUE THREAD

**Issue by Yukidaruma-dev** [gitbucket/gitbucket#2297]
```
yukidaruma-dev@yuki-server:~$ sudo java -jar /usr/share/gitbucket/gitbucket.war --port=8080 --host=127.0.0.0 --gitbucket.home=/usr/share/gitbucket/
2019-04-06 15:13:13.719:INFO::main: Logging initialized @400ms to org.eclipse.jetty.util.log.StdErrLog
2019-04-06 15:13:13.925:INFO:oejs.Server:main: jetty-9.4.z-SNAPSHOT; built: 2018-11-14T21:20:31.478Z; git: c4550056e785fb5665914545889f21dc136ad9e6; jvm 10.0.2+13-Ubuntu-1ubuntu0.18.04.4
2019-04-06 15:13:16.157:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2019-04-06 15:13:19.383:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2019-04-06 15:13:19.383:INFO:oejs.session:main: No SessionScavenger set, using defaults
2019-04-06 15:13:19.393:INFO:oejs.session:main: node0 Scavenging every 660000ms
15:13:19.750 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
15:13:20.007 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
15:13:20.067 [main] INFO  g.core.servlet.InitializeListener - Check version
15:13:20.068 [main] INFO  g.core.servlet.InitializeListener - Start schema update
2019-04-06 15:13:20.176:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@21f8e55f{/,file:///usr/share/gitbucket/tmp/webapp/,UNAVAILABLE}{file:/usr/share/gitbucket/gitbucket.war}
java.sql.SQLSyntaxErrorException: (conn=18) Table 'VERSIONS' already exists
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:236)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:232)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeUpdate(MariaDbPreparedStatementClient.java:194)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at io.github.gitbucket.solidbase.migration.MigrationUtils.updateDatabase(MigrationUtils.java:20)
        at io.github.gitbucket.solidbase.manager.JDBCVersionManager.initialize(JDBCVersionManager.java:24)
        at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:33)
        at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:29)
        at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1(InitializeListener.scala:69)
        at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1$adapted(InitializeListener.scala:59)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
        at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
        at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:59)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:957)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:552)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:922)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:364)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:852)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:256)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.server.Server.start(Server.java:415)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:382)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at JettyLauncher.main(JettyLauncher.java:127)
Caused by: 
java.sql.SQLException: Table 'VERSIONS' already exists|Query is: CREATE TABLE VERSIONS (MODULE_ID VARCHAR(100) NOT NULL, VERSION VARCHAR(100) NOT NULL)|java thread: main
        at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:163)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:280)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:223)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeUpdate(MariaDbPreparedStatementClient.java:194)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at io.github.gitbucket.solidbase.migration.MigrationUtils.updateDatabase(MigrationUtils.java:20)
        at io.github.gitbucket.solidbase.manager.JDBCVersionManager.initialize(JDBCVersionManager.java:24)
        at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:33)
        at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:29)
        at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1(InitializeListener.scala:69)
        at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1$adapted(InitializeListener.scala:59)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
        at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
        at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:59)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:957)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:552)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:922)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:364)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:852)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:256)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.server.Server.start(Server.java:415)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:382)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at JettyLauncher.main(JettyLauncher.java:127)
2019-04-06 15:13:20.230:INFO:oejs.AbstractConnector:main: Started ServerConnector@7aead3af{HTTP/1.1,[http/1.1]}{127.0.0.0:8080}
2019-04-06 15:13:20.232:INFO:oejs.Server:main: Started @6960ms
```

I am using MySQL 8.0.x.
OS is Ubuntu 18.04.
The Java version is 11.
I do reverse proxy with Nginx.

MySQL 8.0.xを使用しています。
OSはUbuntu18.04です。
Javaバージョンは11です。
Nginxでリバースプロキシをしています。

**Comment by Yukidaruma-dev** [comment]
Sorry...
I was successful!
But I can not `git clone.`

**Comment by Yukidaruma-dev** [comment]
Sorry.
I was successful too.
Thanks.

**Comment by michal5520pl** [comment]
How did you resolve the issue? I have the same problem
