### ISSUE TITLE
GitBucket crash after update from 4.31.1 to 4.31.2

### ISSUE THREAD

**Issue by anfer1** [gitbucket/gitbucket#2298]
Cannot update from 4.31.1 to 4.31.2 version.
In log I getting this error:

    08:59:20.392 [localhost-startStop-1] ERROR gitbucket.core.plugin.PluginRegistry - Error during plugin initialization: gitbucket-ci-plugin-assembly-1.6.0.jar
    java.sql.SQLSyntaxErrorException: (conn=13563) Duplicate column name 'BUILD_TYPE'
            at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:236)
            at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)
            at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)
            at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:232)
            at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)
            at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeUpdate(MariaDbPreparedStatementClient.java:194)
            at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
            at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
            at io.github.gitbucket.solidbase.migration.MigrationUtils.updateDatabase(MigrationUtils.java:20)
            at io.github.gitbucket.solidbase.migration.LiquibaseMigration.migrate(LiquibaseMigration.java:93)
            at io.github.gitbucket.solidbase.migration.LiquibaseMigration.migrate(LiquibaseMigration.java:54)
            at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:45)
            at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:29)
            at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3(PluginRegistry.scala:344)
            at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3$adapted(PluginRegistry.scala:319)
            at scala.collection.immutable.List.foreach(List.scala:392)
            at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistry.scala:319)
            at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1(InitializeListener.scala:91)
            at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1$adapted(InitializeListener.scala:59)
            at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
            at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
            at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
            at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
            at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
            at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:59)
            at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4776)
            at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5240)
            at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
            at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
            at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
            at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
            at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:985)
            at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1856)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at java.lang.Thread.run(Thread.java:748)
    Caused by: java.sql.SQLException: Duplicate column name 'BUILD_TYPE'
    Query is: ALTER TABLE gitbucket.CI_CONFIG ADD BUILD_TYPE VARCHAR(200) NULL
    java thread: localhost-startStop-1
            at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:163)
            at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:280)
            at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:223)
            ... 34 common frames omitted

How i can update Gitbucket?

**Comment by takezoe** [comment]
This is gitbucket-ci-plugin's issue. The easiest way to upgrade is uninstalling gitbucket-ci-plugin.

To identify the root cause, I would like to ask you following things:

- What version of gitbucket-ci-plugin do you use?
- What is the content of `PLUGIN` table? You can see it using "Database Viewer" in the administration console.
