### ISSUE TITLE
Broken since 4.31.0

### ISSUE THREAD

**Issue by mmaenz** [gitbucket/gitbucket#2342]
### Before submitting an issue to GitBucket I have first:

- [ ] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [ ] searched for similar already existing issue
- [ ] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki)

*(if you have performed all the above, remove the paragraph and continue describing the issue with template below)*

## Issue
**Impacted version**: since 4.31.0, 4.30.0 seems fine!

**Deployment mode**: standalone with caddy as reverse proxy in front

**Problem description**:
No git action work anymore. Can't pull, push or do something else. On git-client I get:
POST git-receive-pack (9705 bytes) error: remote unpack failed: error no such file or directory. (in german: "Datei oder Verzeichnis nicht gefunden")

Exception:
`16:01:20.134 [qtp1108411398-13] INFO  o.c.core.Cache2kCoreProviderImpl - cache2k starting. version=1.2.0.Final
16:01:20.146 [qtp1108411398-13] WARN  o.c.e.a.WarnAboutCache2kAllUsage - Usage of the artifact cache2k-all is deprecated, please update your dependencies. See: https://cache2k.org/docs/latest/user-guide.html#getting-started
16:01:29.665 [qtp1108411398-13] INFO  g.core.service.AccountService - Failed to authenticate: mmaenz
2019-07-09 16:01:37.688:WARN:oejshC.ROOT:qtp1108411398-15: Internal error during receive-pack to /home/gitbucket/.gitbucket/repositories/mmaenz/fwr-backend
java.io.IOException: Datei oder Verzeichnis nicht gefunden
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2024)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryPackParser.parse(ObjectDirectoryPackParser.java:192)
	at org.eclipse.jgit.transport.BaseReceivePack.receivePack(BaseReceivePack.java:1494)
	at org.eclipse.jgit.transport.BaseReceivePack.receivePackAndCheckConnectivity(BaseReceivePack.java:1195)
	at org.eclipse.jgit.transport.ReceivePack.service(ReceivePack.java:266)
	at org.eclipse.jgit.transport.ReceivePack.receive(ReceivePack.java:221)
	at org.eclipse.jgit.http.server.ReceivePackServlet.doPost(ReceivePackServlet.java:185)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:244)
	at org.eclipse.jgit.http.server.ReceivePackServlet$Factory.doFilter(ReceivePackServlet.java:147)
	at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:242)
	at org.eclipse.jgit.http.server.RepositoryFilter.doFilter(RepositoryFilter.java:145)
	at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:242)
	at org.eclipse.jgit.http.server.NoCacheFilter.doFilter(NoCacheFilter.java:86)
	at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:242)
	at org.eclipse.jgit.http.server.glue.UrlPipeline.service(UrlPipeline.java:221)
	at org.eclipse.jgit.http.server.glue.SuffixPipeline.service(SuffixPipeline.java:103)
	at org.eclipse.jgit.http.server.glue.MetaFilter.doFilter(MetaFilter.java:183)
	at org.eclipse.jgit.http.server.glue.MetaServlet.service(MetaServlet.java:143)
	at gitbucket.core.servlet.GitRepositoryServlet.super$service(GitRepositoryServlet.scala:64)
	at gitbucket.core.servlet.GitRepositoryServlet.$anonfun$service$2(GitRepositoryServlet.scala:64)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at gitbucket.core.util.LockUtil$.$anonfun$lock$1(LockUtil.scala:30)
	at gitbucket.core.util.SyntaxSugars$.defining(SyntaxSugars.scala:12)
	at gitbucket.core.util.LockUtil$.lock(LockUtil.scala:27)
	at gitbucket.core.servlet.GitRepositoryServlet.withLockRepository(GitRepositoryServlet.scala:72)
	at gitbucket.core.servlet.GitRepositoryServlet.service(GitRepositoryServlet.scala:64)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at gitbucket.core.servlet.ControllerFilter.doFilter(CompositeScalatraFilter.scala:31)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at gitbucket.core.servlet.ControllerFilter.doFilter(CompositeScalatraFilter.scala:31)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:69)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at gitbucket.core.servlet.GitAuthenticationFilter.$anonfun$defaultRepository$5(GitAuthenticationFilter.scala:122)
	at gitbucket.core.servlet.GitAuthenticationFilter.defaultRepository(GitAuthenticationFilter.scala:143)
	at gitbucket.core.servlet.GitAuthenticationFilter.$anonfun$doFilter$2(GitAuthenticationFilter.scala:50)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.Option.getOrElse(Option.scala:138)
	at gitbucket.core.servlet.GitAuthenticationFilter.doFilter(GitAuthenticationFilter.scala:50)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:28)`

- Authentication seems not work. Doesn't fetch all remote branches/tags.
- gitbucket is running as system.service on ubuntu using OpenJDK8 under user gitbucket. All permissions are set for gitbucket-user. I only start with `java -jar gitbucket.war --port=8085`
- Sorry no logs. Had lot of trouble to reverse database to use older version without messing up my projects.

**Comment by jisqyv** [comment]
@mmaenz I ran into this as well on a fresh installation of 4.31.2. I was pushing via http to:

  http://localhost:8080/root/tweb

However if I added ".git" to the end, then this error did not happen.

  http://localhost:8080/root/tweb.git

See if that helps you (or anyone else!)

**Comment by mmaenz** [comment]
I can confirm that!

Test-run on macOS with gitbucket 4.31.2.
Did local run on [](http://localhost:8080/root/test) and got error mentioned before.
Changing project origin to [](http://localhost:8080/root/test.git) seems to solve this problem.

Is this behaviour intentional or is it a bug?

Expected behaviour would be without `.git` as GitHub and GitLab work the same way.

**Comment by mmaenz** [comment]
@takezoe 
From 4.30.0 to 4.31.2 there is no significant change in `GitRepositoryServlet.service` where the error is coming from. The eclipse developer seem to have something changed in jgit!
I compared the source of 4.30.0 with 4.31.2 and there is only new locking of repo which doesn't seem to cause this problem. 
As seen in build.sbt, GitBucket moved from **jgit 5.1.3** to **jgit 5.2.0** - seems without testing.

GitBucket can't be blamed for changes in jgit but should have tested that before release and handle this change in jgit to work properly?

**Comment by takezoe** [comment]
I think that JGit version doesn't matter.

If the base URL of your GitBucket is `http://localhost:8080/` and your repository is `root/test`, `http://localhost:8080/git/root/test.git` should be a proper URL of Git repository.

The URL box placed at the top page of each repository should show this URL.

<img width="993" alt="Screen Shot 2019-08-02 at 0 55 11" src="https://user-images.githubusercontent.com/1094760/62308428-483a1f80-b4c0-11e9-9324-5fb8d8b1b8d8.png">

**Comment by jisqyv** [comment]
@takezoe I still claim that this is a bug. If a missing ".git" suffix is not supposed to work, then a rational message, like no such repo, or something should be given. What happens today is the clone hangs an an error is thrown on the server.

**Comment by mmaenz** [comment]
For convenience a proper exception or error message should be thrown as `error: remote unpack failed: error No such file or directory` is saying nothing and sounds more like a broken repo instead of a missing `.git` in url.

I think it should be fixed as a lot of users could encounter the same problem and in the end toss GitBucket away. 

I'm not that much into Scala but simply checking the URL in `GitRepositoryServlet.service` and in case of no `.git` at the end it could add it. That would be a simple fix.

**Comment by takezoe** [comment]
So could you update the subject of this issue? (e.g. Improve handling of wrong Git repository URLs)

> I'm not that much into Scala but simply checking the URL in GitRepositoryServlet.service and in case of no .git at the end it could add it. That would be a simple fix.

Even though it's written in Scala, `GitRepositoryServlet` is almost normal Java servlet. If you think it would be a simple fix, it might be a good opportunity to try Scala. Pull request is welcome! 😉
