### ISSUE TITLE
Logger Timeout

### ISSUE THREAD

**Issue by codeling** [gitbucket/gitbucket#2404]
**Impacted version**: 4.32.0

**Deployment mode**: gitbucket.war deployed on Tomcat 9.0.29, running under Windows Server 2008 R2 (Virtual Machine, 1GB RAM), behind apache2 proxy

**Problem description**:
When starting up Tomcat, most of the time, gitbucket doesn't start, but instead reports this:
```
03-Dec-2019 13:24:20.347 SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Error configuring application listener of class [gitbucket.core.servlet.InitializeListener]
	akka.ConfigurationException: Could not start logger due to [akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.Logging$DefaultLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log1-Logging$DefaultLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]]
		at akka.event.LoggingBus.startDefaultLoggers(Logging.scala:162)
		at akka.event.LoggingBus.startDefaultLoggers$(Logging.scala:105)
		at akka.event.EventStream.startDefaultLoggers(EventStream.scala:25)
		at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:678)
		at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:912)
		at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:908)
		at akka.actor.ActorSystemImpl._start(ActorSystem.scala:908)
		at akka.actor.ActorSystemImpl.start(ActorSystem.scala:930)
		at akka.actor.ActorSystem$.apply(ActorSystem.scala:258)
		at akka.actor.ActorSystem$.apply(ActorSystem.scala:302)
		at akka.actor.ActorSystem$.apply(ActorSystem.scala:276)
		at gitbucket.core.servlet.InitializeListener.<init>(InitializeListener.scala:41)
```
The main problem is probably the feeble system performance, but I unfortunately can't change this; the problem happens much more since the upgrade to Tomcat 9.0.29, but occasionally this happened with older versions too.
I have found other reports of such behavior, e.g. https://stackoverflow.com/questions/16176654/akka-timeouts-starting-event-handlers or https://github.com/yahoo/kafka-manager/issues/428, and they mention setting `akka.logger-startup-timeout` to some higher value in some config file, but I can't figure out where i should put this - is there a config file in gitbucket where I can put this setting?

**Comment by takezoe** [comment]
Currently, Akka configuration is hardcoded here:

https://github.com/gitbucket/gitbucket/blob/a943a5985da8c7aef2d09143629bee126c70019c/src/main/scala/gitbucket/core/servlet/InitializeListener.scala#L39-L54

You might have to add configuration here or create `src/main/resources/application.conf`, and build GitBucket from source code.

**Comment by takezoe** [comment]
Closing old questions.
