### ISSUE TITLE
Failure on generating thumbnail of profile picture

### ISSUE THREAD

**Issue by alwibrm** [gitbucket/gitbucket#2434]
## Issue
**Impacted version**: 4.32.0

**Deployment mode**: standalone on AWS EC2 instance

**Problem description**:

1. As logged in user go to profile settings
2. Choose edit profile
3. Upload one of this image: https://de.wikipedia.org/wiki/TeamCity#/media/Datei:Teamcity_Logo.png
4. An internal server error occurs with the following exception:
`Mar 17 14:12:48 java: at #011at java.lang.Thread.run(Thread.java:748)
java.lang.NoClassDefFoundError: Could not initialize class java.awt.Dimension
	at net.coobird.thumbnailator.Thumbnails$Builder.makeParam(Unknown Source)
	at net.coobird.thumbnailator.Thumbnails$Builder.toFile(Unknown Source)
	at gitbucket.core.controller.AccountManagementControllerBase.$anonfun$updateImage$3(ControllerBase.scala:347)
	at gitbucket.core.controller.AccountManagementControllerBase.$anonfun$updateImage$3$adapted(ControllerBase.scala:338)
	at scala.Option.foreach(Option.scala:438)
	at gitbucket.core.controller.AccountManagementControllerBase.updateImage(ControllerBase.scala:338)
	at gitbucket.core.controller.AccountManagementControllerBase.updateImage$(ControllerBase.scala:330)
	at gitbucket.core.controller.AccountController.updateImage(AccountController.scala:20)
	at gitbucket.core.controller.AccountControllerBase.$anonfun$$init$$22(AccountController.scala:347)
	at scala.Option.map(Option.scala:243)
	at gitbucket.core.controller.AccountControllerBase.$anonfun$$init$$21(AccountController.scala:336)
	at gitbucket.core.util.OneselfAuthenticator.$anonfun$oneselfOnly$2(Authenticator.scala:15)
	at gitbucket.core.util.OneselfAuthenticator.authenticate(Authenticator.scala:20)
	at gitbucket.core.util.OneselfAuthenticator.$anonfun$oneselfOnly$1(Authenticator.scala:15)
	at gitbucket.core.controller.ValidationSupport.$anonfun$post$3(ValidationSupport.scala:25)
	at org.scalatra.forms.FormSupport.validate(FormSupport.scala:14)
	at org.scalatra.forms.FormSupport.validate$(FormSupport.scala:8)
	at gitbucket.core.controller.ControllerBase.validate(ControllerBase.scala:35)
	at gitbucket.core.controller.ValidationSupport.$anonfun$post$1(ValidationSupport.scala:25)
	at org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:282)
	at org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:276)
	at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:185)
	at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:171)
	at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:35)
	at org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:275)
	at org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:274)
	at gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:35)
	at org.scalatra.ScalatraBase.$anonfun$runRoutes$3(ScalatraBase.scala:250)
	at scala.Option.flatMap(Option.scala:284)
	at org.scalatra.ScalatraBase.$anonfun$runRoutes$1(ScalatraBase.scala:248)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:199)
	at org.scalatra.ScalatraBase.runRoutes(ScalatraBase.scala:247)
	at org.scalatra.ScalatraBase.runRoutes$(ScalatraBase.scala:245)
	at gitbucket.core.controller.ControllerBase.runRoutes(ControllerBase.scala:35)
	at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:169)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:201)
	at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
	at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:35)
	at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:61)
	at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:75)
	at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:73)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:35)
	at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:55)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:61)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
	at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:54)
	at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:52)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:35)
	at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
	at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:35)
	at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:42)
	at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:35)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:35)
	at org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:197)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:61)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
	at org.scalatra.FlashMapSupport.handle(FlashMap.scala:172)
	at org.scalatra.FlashMapSupport.handle$(FlashMap.scala:171)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:35)
	at org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:61)
	at org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
	at org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:73)
	at gitbucket.core.servlet.CompositeScalatraFilter.$anonfun$process$2(CompositeScalatraFilter.scala:67)
	at gitbucket.core.servlet.CompositeScalatraFilter.$anonfun$process$2$adapted(CompositeScalatraFilter.scala:64)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:904)
	at gitbucket.core.servlet.CompositeScalatraFilter.process(CompositeScalatraFilter.scala:64)
	at gitbucket.core.servlet.ControllerFilter.doFilter(CompositeScalatraFilter.scala:25)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at gitbucket.core.servlet.ControllerFilter.doFilter(CompositeScalatraFilter.scala:31)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.scalatra.ScalatraFilter.$anonfun$doNotFound$1(ScalatraFilter.scala:79)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$5(ScalatraBase.scala:172)
	at scala.Option.getOrElse(Option.scala:202)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$3(ScalatraBase.scala:172)
	at scala.Option.getOrElse(Option.scala:202)
	at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:172)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:201)
	at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
	at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:35)
	at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:61)
	at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:75)
	at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:73)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:35)
	at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:55)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:61)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
	at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:54)
	at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:52)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:35)
	at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
	at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:35)
	at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:42)
	at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:35)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:35)
	at org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:197)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:61)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
	at org.scalatra.FlashMapSupport.handle(FlashMap.scala:172)
	at org.scalatra.FlashMapSupport.handle$(FlashMap.scala:171)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:35)
	at org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:61)
	at org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
	at org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1(TransactionFilter.scala:39)
	at gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1$adapted(TransactionFilter.scala:30)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
	at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
	at gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by takezoe** [comment]
I guess you run GitBucket on the environment where GUI isn't available. In this case, you need to run JVM as headless mode by specifying a system property `-Djava.awt.headless=true`.

**Comment by takezoe** [comment]
@alwibrm Did my answer help you? For now, I close this issue. If you have further question, please post it to our gitter room: https://gitter.im/gitbucket/gitbucket
