### ISSUE TITLE
"sbt executable" fails under proxy environment

### ISSUE THREAD

**Issue by SIkebe** [gitbucket/gitbucket#2440]
## Issue
**Impacted version**: v4.33.0
**Problem description**:
If your environment requires proxy authentication, `sbt executable` fails to download plugins.
```
[info] building executable webapp in C:\gitbucket\target\executable
[info] Download: https://github.com/gitbucket/gitbucket-notifications-plugin/releases/download/1.8.0/gitbucket-notifications-plugin-1.8.0.jar
[error] java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
[error]         at java.base/sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2172)
[error]         at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
[error]         at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
[error]         at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1507)
[error]         at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1505)
[error]         at java.base/java.security.AccessController.doPrivileged(Native Method)
[error]         at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:795)
[error]         at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1504)
[error]         at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[error]         at java.base/java.net.URL.openStream(URL.java:1140)
[error]         at $1c06179b831e90481009$.$anonfun$$sbtdef$6(C:\gitbucket\build.sbt:170)
[error]         at $1c06179b831e90481009$.$anonfun$$sbtdef$6$adapted(C:\gitbucket\build.sbt:164)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at $1c06179b831e90481009$.$anonfun$$sbtdef$1(C:\gitbucket\build.sbt:164)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (executable) java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
```

**Comment by SIkebe** [comment]
workaround: Comment out these lines and configure plugins manually.
https://github.com/gitbucket/gitbucket/blob/9ef366237cd197e3a390b6f522b72425c8026643/build.sbt#L163-L173

**Comment by takezoe** [comment]
Specifying system properties might be effective.
https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html

By the way, how do you configure proxy for sbt itself?

**Comment by SIkebe** [comment]
>how do you configure proxy for sbt itself?

I configure `C:\Program Files (x86)\sbt\conf\sbt.config` like below.
```
-Dsbt.gigahorse=false

-Djdk.http.auth.tunneling.disabledSchemes=""

-Dhttp.proxyHost=<proxy-url>
-Dhttp.proxyPort=<proxy-port>
-Dhttp.proxyUser=<proxy-user>
-Dhttp.proxyPassword=<proxy-password>

-Dhttps.proxyHost=<proxy-url>
-Dhttps.proxyPort=<proxy-port>
-Dhttps.proxyUser=<proxy-user>
-Dhttps.proxyPassword=<proxy-password>
```

**Comment by takezoe** [comment]
Hmm... Why aren't these system properties applied to `URLConnection`? 🤔

**Comment by SIkebe** [comment]
Yeah, I wonder too...
