### ISSUE TITLE
SQL error and corrupted H2 DB when tranfering a repo

### ISSUE THREAD

**Issue by btlogy** [gitbucket/gitbucket#2479]
### Before submitting an issue to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki)

## Issue
**Impacted version**: 4.33.0

**Deployment mode**: standalone app behind httpd (2.4.6-93.el7.centos.x86_64)

**Problem description**:
I'm getting an HTTP 500 and SQL error (+stack trace) when I'm trying to transfer a repo from a user (johndoe) to a group (DEV):
```
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "johndoe"
```

**Reproduction**:
1. Create a new repo assign to the current user (i.e.: johndoe/testrepo)
2. Go to Settings > Danger Zone and transfer to a group (i.e.: DEV)

Expected behaviour: transfer succeed
Observed behaviour: server error!

**Data corruption**:
From that point, it seems like the DB is corrupted because I get server error when I'm trying to access the page of the targeted group (DEV):
```
org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /var/lib/gitbucket/repositories/DEV/testrepo.git
```

**Logs**:
```
ERROR g.c.c.RepositorySettingsController - Catch unhandled error in request: Request(POST //code.example.com/johndoe/testrepo/settings/transfer)@1b4f50d7
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "johndoe"; SQL statement:
delete from "REPOSITORY" where ("REPOSITORY"."USER_NAME" = ?) and ("REPOSITORY"."REPOSITORY_NAME" = ?) [
22018-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:455)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.value.Value.convertTo(Value.java:829)
        at org.h2.value.Value.convertTo(Value.java:723)
        at org.h2.value.Value.compareTo(Value.java:1422)
        at org.h2.mvstore.db.ValueDataType.compareValues(ValueDataType.java:177)
        at org.h2.mvstore.db.ValueDataType.compare(ValueDataType.java:153)
        at org.h2.mvstore.MVMap.compare(MVMap.java:526)
        at org.h2.mvstore.Page.binarySearch(Page.java:481)
        at org.h2.mvstore.Cursor.traverseDown(Cursor.java:159)
        at org.h2.mvstore.Cursor.<init>(Cursor.java:31)
        at org.h2.mvstore.tx.TransactionMap$TMIterator.<init>(TransactionMap.java:701)
        at org.h2.mvstore.tx.TransactionMap$KeyIterator.<init>(TransactionMap.java:652)
        at org.h2.mvstore.tx.TransactionMap.keyIterator(TransactionMap.java:575)
        at org.h2.mvstore.db.MVSecondaryIndex.find(MVSecondaryIndex.java:273)
        at org.h2.mvstore.db.MVSecondaryIndex.find(MVSecondaryIndex.java:266)
        at org.h2.index.BaseIndex.find(BaseIndex.java:132)
        at org.h2.index.IndexCursor.find(IndexCursor.java:163)
        at org.h2.table.TableFilter.next(TableFilter.java:475)
        at org.h2.command.dml.Delete.update(Delete.java:89)
        at org.h2.constraint.ConstraintReferential.updateWithSkipCheck(ConstraintReferential.java:424)
        at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:395)
        at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:265)
        at org.h2.table.Table.fireConstraints(Table.java:1020)
        at org.h2.table.Table.fireAfterRow(Table.java:1038)
        at org.h2.command.dml.Delete.update(Delete.java:129)
        at org.h2.command.CommandContainer.update(CommandContainer.java:133)
        at org.h2.command.Command.executeUpdate(Command.java:267)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:200)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:154)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at slick.jdbc.JdbcActionComponent$DeleteActionExtensionMethodsImpl$$anon$4.$anonfun$run$3(JdbcActionComponent.scala:269)
        at slick.jdbc.JdbcActionComponent$DeleteActionExtensionMethodsImpl$$anon$4.$anonfun$run$3$adapted(JdbcActionComponent.scala:267)
        at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
        at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
        at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
        at slick.jdbc.JdbcActionComponent$DeleteActionExtensionMethodsImpl$$anon$4.run(JdbcActionComponent.scala:267)
        at slick.jdbc.JdbcActionComponent$DeleteActionExtensionMethodsImpl$$anon$4.run(JdbcActionComponent.scala:266)
        at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
        at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDeleteInvoker.delete(BlockingProfile.scala:98)
        at gitbucket.core.service.RepositoryService.deleteRepositoryOnModel(RepositoryService.scala:323)
        at gitbucket.core.service.RepositoryService.$anonfun$renameRepository$4(RepositoryService.scala:131)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at gitbucket.core.util.LockUtil$.$anonfun$lock$1(LockUtil.scala:30)
        at gitbucket.core.util.SyntaxSugars$.defining(SyntaxSugars.scala:12)
        at gitbucket.core.util.LockUtil$.lock(LockUtil.scala:27)
        at gitbucket.core.service.RepositoryService.$anonfun$renameRepository$3(RepositoryService.scala:81)
        at gitbucket.core.service.RepositoryService.$anonfun$renameRepository$3$adapted(RepositoryService.scala:80)
        at scala.Option.foreach(Option.scala:437)
        at gitbucket.core.service.RepositoryService.$anonfun$renameRepository$1(RepositoryService.scala:80)
        at gitbucket.core.service.RepositoryService.$anonfun$renameRepository$1$adapted(RepositoryService.scala:77)
        at scala.Option.foreach(Option.scala:437)
        at gitbucket.core.service.RepositoryService.renameRepository(RepositoryService.scala:77)
        at gitbucket.core.service.RepositoryService.renameRepository$(RepositoryService.scala:74)
        at gitbucket.core.controller.RepositorySettingsController.renameRepository(RepositorySettingsController.scala:24)
        at gitbucket.core.controller.RepositorySettingsControllerBase.$anonfun$$init$$48(RepositorySettingsController.scala:373)
        at gitbucket.core.util.OwnerAuthenticator.$anonfun$ownerOnly$2(Authenticator.scala:31)
        at gitbucket.core.util.OwnerAuthenticator.$anonfun$authenticate$1(Authenticator.scala:38)
        at scala.Option.map(Option.scala:242)
        at gitbucket.core.util.OwnerAuthenticator.authenticate(Authenticator.scala:36)
        at gitbucket.core.util.OwnerAuthenticator.$anonfun$ownerOnly$1(Authenticator.scala:31)
        at gitbucket.core.controller.ValidationSupport.$anonfun$post$3(ValidationSupport.scala:25)
        at org.scalatra.forms.FormSupport.validate(FormSupport.scala:14)
        at org.scalatra.forms.FormSupport.validate$(FormSupport.scala:8)
        at gitbucket.core.controller.ControllerBase.validate(ControllerBase.scala:35)
        at gitbucket.core.controller.ValidationSupport.$anonfun$post$1(ValidationSupport.scala:25)
        at org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:282)
        at org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:276)
        at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:185)
        at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:171)
        at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:35)
        at org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:275)
        at org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:274)
        at gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:35)
        at org.scalatra.ScalatraBase.$anonfun$runRoutes$3(ScalatraBase.scala:250)
        at scala.Option.flatMap(Option.scala:283)
        at org.scalatra.ScalatraBase.$anonfun$runRoutes$1(ScalatraBase.scala:248)
        at scala.collection.immutable.Stream.flatMap(Stream.scala:206)
        at org.scalatra.ScalatraBase.runRoutes(ScalatraBase.scala:247)
        at org.scalatra.ScalatraBase.runRoutes$(ScalatraBase.scala:245)
        at gitbucket.core.controller.ControllerBase.runRoutes(ControllerBase.scala:35)
        at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:169)
        at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:201)
        at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
        at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
        at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:35)
        at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:75)
        at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:73)
        at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:35)
        at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:55)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
        at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
        at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
        at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:54)
        at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:52)
        at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:35)
        at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
        at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
        at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:35)
        at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:42)
        at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:35)
        at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:35)
        at org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:197)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
        at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
        at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
        at org.scalatra.FlashMapSupport.handle(FlashMap.scala:172)
        at org.scalatra.FlashMapSupport.handle$(FlashMap.scala:171)
        at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:35)
        at org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
        at org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
        at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:73)
        at gitbucket.core.servlet.CompositeScalatraFilter.$anonfun$process$2(CompositeScalatraFilter.scala:67)
        at gitbucket.core.servlet.CompositeScalatraFilter.$anonfun$process$2$adapted(CompositeScalatraFi
lter.scala:64)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
        at gitbucket.core.servlet.CompositeScalatraFilter.process(CompositeScalatraFilter.scala:64)
        at gitbucket.core.servlet.ControllerFilter.doFilter(CompositeScalatraFilter.scala:25)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at gitbucket.core.servlet.ControllerFilter.doFilter(CompositeScalatraFilter.scala:31)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at org.scalatra.ScalatraFilter.$anonfun$doNotFound$1(ScalatraFilter.scala:79)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at org.scalatra.ScalatraBase.$anonfun$executeRoutes$5(ScalatraBase.scala:172)
        at scala.Option.getOrElse(Option.scala:201)
        at org.scalatra.ScalatraBase.$anonfun$executeRoutes$3(ScalatraBase.scala:172)
        at scala.Option.getOrElse(Option.scala:201)
        at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:172)
        at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:201)
        at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
        at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
        at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:35)
        at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:75)
        at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:73)
        at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:35)
        at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:55)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
        at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
        at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
        at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:54)
        at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:52)
        at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:35)
        at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
        at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
        at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:35)
        at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:42)
        at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:35)
        at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:35)
        at org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:197)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
        at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
        at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
        at org.scalatra.FlashMapSupport.handle(FlashMap.scala:172)
        at org.scalatra.FlashMapSupport.handle$(FlashMap.scala:171)
        at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:35)
        at org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
        at org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
        at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:73)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1(TransactionFilter.scala:39)
        at gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1$adapted(TransactionFilter.scala:30)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
        at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)  
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
        at gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:30)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1596)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:500)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NumberFormatException: For input string: "johndoe"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at org.h2.value.Value.convertToInt(Value.java:936)
        at org.h2.value.Value.convertTo(Value.java:764)
        ... 222 common frames omitted
```

**Comment by btlogy** [comment]
I could not reproduce this on 4.31.2.
But it seems t have been introduced in 4.32.0.
Though, the error looks slightly different in the logs:
```
ERROR g.c.c.RepositorySettingsController - Catch unhandled error in request: Request(POST //code.example.com/johndoe/testrepo/settings/transfer)@48a006a3
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "DEV"; SQL statement:
insert into "REPOSITORY" ("USER_NAME","REPOSITORY_NAME","PRIVATE","DESCRIPTION","DEFAULT_BRANCH","REGISTERED_DATE","UPDATED_DATE","LAST_ACTIVITY_DATE","ORIGIN_USER_NAME","ORIGIN_REPOSITORY_NAME","PARENT_USER_NAME","PARENT_REPOSITORY_NAME","ISSUES_OPTION","EXTERNAL_ISSUES_URL","WIKI_OPTION","EXTERNAL_WIKI_URL","ALLOW_FORK","MERGE_OPTIONS","DEFAULT_MERGE_OPTION")  values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) [22018-199]
...
Caused by: java.lang.NumberFormatException: For input string: "DEV"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at org.h2.value.Value.convertToInt(Value.java:936)
        at org.h2.value.Value.convertTo(Value.java:764)
        ... 210 common frames omitted
```

**Comment by btlogy** [comment]
I guess I'm going to look at this line for 4.33.0:
```
gitbucket.core.service.RepositoryService.deleteRepositoryOnModel(RepositoryService.scala:323)
```
And this one for version 4.32.0:
```
gitbucket.core.service.RepositoryService.$anonfun$renameRepository$4(RepositoryService.scala:82)
```

**Comment by btlogy** [comment]
I've looked a bit at the history, my first guess is it has to be in one of those files:
```
src/main/scala/gitbucket/core/controller/RepositorySettingsController.scala
src/main/scala/gitbucket/core/service/RepositoryService.scala
src/main/scala/gitbucket/core/servlet/GitRepositoryServlet.scala
src/main/scala/gitbucket/core/util/JDBCUtil.scala
src/main/scala/gitbucket/core/util/JGitUtil.scala
```

**Comment by takezoe** [comment]
@btlogy I cannot reproduce this on a fresh installation of GitBuclet 4.33.0. Could you provide the simplest procedure to reproduce from scratch?

**Comment by btlogy** [comment]
@takezoe, this is likely a good news: somehow, not many people should be affected then.
Thanks for your time making Gitbucket and checking on this btw. Much appreciated.

Meanwhile, I've tried to track the culprit on Friday, and it occurred to me this issue might be related to:
* the JVM we are using which is still openjdk-1.8.0(-252.b09-2.el7_8)
* and/or the use of LDAP authentication

And this last one makes it harder to provide a simple procedure :-/

Nevertheless, the best way to reproduce this issue might be to use Docker.
Now I've found [this](https://www.github.com/gitbucket/gitbucket-docker), I'll try to test more and come back with something here later.

**Comment by btlogy** [comment]
More testing done yesterday and today.
I can not reproduce this issue in a clean environment.
I've build a docker container matching our own environment (CentOS 7.8 + OpenJDK 1.8.0 252) and Gitbucket 4.33.0 with LDAP auth.
But the sequence I've described above is working as expected.
I've also duplicated our own environment and get rid of the data to start from scratch with version 4.32.0: still working fine.
Then I've tried to go back in time, creating data with 4.27.0 and upgrading to 4.32.0: still working as expected!

It seems like something is wrong in the database we are using, because I can reproduce this issue all the time with this content as soon as I upgrade to 4.32.0.
We've been using Gitbucket for quite some time. I'm not sure if I'll be able to reproduce the problem at all from scratch.

Thus, I'll now try to strip the database we have to the minimum to reproduce the issue with 'real' data.
Hopefully, I'll be able to submit a Docker file and some data here soon...

**Comment by btlogy** [comment]
More testing done today.
I've scripted the deletion of all repos and scrub email and ssh keys from the (H2) DB and I could still reproduce the SQL error.
Then I've tried to squeeze the data.mv.db file (40Mb) by exporting and re-importing the data, the problem is gone!
I can now reproduce this issue at will with a 12Mb tar.gz data file mounted with the official Gitbucket docker container.
But since this file holds some sensitive journalized transactions, I would rather avoid to share it publicly.

Bottom line: it has to do with the history of the H2 DB itself.
I've noticed Gitbucket changed the h2 dependency from 1.4.197 to 1.4.199 between version 4.31.2 and 4.33.0.
So, I've repacked gitbucket.war of 4.33.0 with h2-1.4.197.jar, and bingo: I can no longer reproduce the SQL error!
The root cause might be something introduced in h2-1.4.198 or h2-1.4.199, like PR [#1349](https://github.com/h2database/h2database/pull/1349)...
But I feel like I'll spend to much time digging into this if I have to document an issue in H2 [repo](https://github.com/h2database/h2database/issues).

Meanwhile, the best workaround for the rare users who would bump into this SQL error is to:
1. restore you last backup
2. export the DB into an sql file via the GUI (/admin/data)
3. stop the service, delete the data.mv.db and start the service once again
4. login in as root:root and import the sql file into the DB via the GUI (same page as above)
This has worked for us. The DB file has shrank about 60% and the SAL error can no longer be reproduced.

@takezoe, as H2 is not a setup anyone should use for critical data, I guess this issue could be closed (wontfix).

**Comment by btlogy** [comment]
I remember giving a try to the recovery tool w/o being able to fix anything in regard to this issue.
But I'm not sure I've used the tool efficiently.
