### ISSUE TITLE
error Object too large

### ISSUE THREAD

**Issue by okuc** [gitbucket/gitbucket#2515]
version: 4.30.1
issue: run 'git push xxxxx' error:
```
error: remote unpack failed: error Object too large (2,577,619,487 bytes), rejecting the pack. Max object size limit is 2,147,483,639 bytes.
```
how to do，think you！

**Comment by SIkebe** [comment]
@okuc GitBucket uses jgit for git operation. This error seems to be a limitation of jgit.
https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/transport/PackParser.java#L718-L720
```java
if (size > Integer.MAX_VALUE - 8) {
	throw new TooLargeObjectInPackException(size, Integer.MAX_VALUE - 8);
}
```

You might want to use Git LFS for such a giant file.

![image](https://user-images.githubusercontent.com/17608272/90405884-58c73300-e0df-11ea-9fc3-fb91f4bb93d4.png)

-----

StackTrace
```
2020-08-17 23:21:20.264:WARN:oejshC.ROOT:qtp1146743572-12: Internal error during receive-pack to C:\Users\<user name>\.gitbucket\repositories\root\test1.git
org.eclipse.jgit.errors.TooLargeObjectInPackException: Object too large (3,062,286,152 bytes), rejecting the pack. Max object size limit is 2,147,483,639 bytes.
        at org.eclipse.jgit.transport.PackParser.checkIfTooLarge(PackParser.java:719)
        at org.eclipse.jgit.transport.PackParser.indexOneObject(PackParser.java:970)
        at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:535)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectoryPackParser.parse(ObjectDirectoryPackParser.java:168)
        at org.eclipse.jgit.transport.ReceivePack.receivePack(ReceivePack.java:1493)
        at org.eclipse.jgit.transport.ReceivePack.receivePackAndCheckConnectivity(ReceivePack.java:1212)
        at org.eclipse.jgit.transport.ReceivePack.service(ReceivePack.java:2189)
        at org.eclipse.jgit.transport.ReceivePack.receive(ReceivePack.java:2120)
        at org.eclipse.jgit.http.server.ReceivePackServlet.doPost(ReceivePackServlet.java:167)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:211)
        at org.eclipse.jgit.http.server.ReceivePackServlet$Factory.doFilter(ReceivePackServlet.java:115)
        at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:209)
        at org.eclipse.jgit.http.server.RepositoryFilter.doFilter(RepositoryFilter.java:112)
        at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:209)
        at org.eclipse.jgit.http.server.NoCacheFilter.doFilter(NoCacheFilter.java:53)
        at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:209)
        at org.eclipse.jgit.http.server.glue.UrlPipeline.service(UrlPipeline.java:188)
        at org.eclipse.jgit.http.server.glue.SuffixPipeline.service(SuffixPipeline.java:70)
        at org.eclipse.jgit.http.server.glue.MetaFilter.doFilter(MetaFilter.java:150)
        at org.eclipse.jgit.http.server.glue.MetaServlet.service(MetaServlet.java:109)
        at gitbucket.core.servlet.GitRepositoryServlet.super$service(GitRepositoryServlet.scala:70)
        at gitbucket.core.servlet.GitRepositoryServlet.$anonfun$service$2(GitRepositoryServlet.scala:70)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at gitbucket.core.util.LockUtil$.$anonfun$lock$1(LockUtil.scala:30)
        at gitbucket.core.util.SyntaxSugars$.defining(SyntaxSugars.scala:12)
        at gitbucket.core.util.LockUtil$.lock(LockUtil.scala:27)
        at gitbucket.core.servlet.GitRepositoryServlet.withLockRepository(GitRepositoryServlet.scala:78)
        at gitbucket.core.servlet.GitRepositoryServlet.service(GitRepositoryServlet.scala:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at gitbucket.core.servlet.ControllerFilter.doFilter(CompositeScalatraFilter.scala:31)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
        at gitbucket.core.servlet.ControllerFilter.doFilter(CompositeScalatraFilter.scala:31)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
        at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:70)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
        at gitbucket.core.servlet.GitAuthenticationFilter.$anonfun$defaultRepository$5(GitAuthenticationFilter.scala:126)
        at gitbucket.core.servlet.GitAuthenticationFilter.defaultRepository(GitAuthenticationFilter.scala:147)
        at gitbucket.core.servlet.GitAuthenticationFilter.$anonfun$doFilter$2(GitAuthenticationFilter.scala:54)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.Option.getOrElse(Option.scala:201)
        at gitbucket.core.servlet.GitAuthenticationFilter.doFilter(GitAuthenticationFilter.scala:54)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
        at gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:28)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1583)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:494)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by okuc** [comment]
Means, gitbucket can't solve this problem?

**Comment by SIkebe** [comment]
> Means, gitbucket can't solve this problem?

Yes. It's not totally impossible, however, it will require a lot of work to do as the condition is hard-coded in jgit itself.
Git is not designed to handle a large file or binary. If you want to, then you should use Git LFS.

**Comment by okuc** [comment]
Ok, got it, thanks
