### ISSUE TITLE
war file deployment failing with "Negative time" message

### ISSUE THREAD

**Issue by codeling** [gitbucket/gitbucket#2620]
**Impacted version**: 4.35.x (tried with 4.35.0 and 4.35.2)

**Deployment mode**: Tomcat (9.0.31) with Apache Reverse Proxy for https (2.4.41)

**Problem description**:
- Stopped Tomcat
- Deployed gitbucket.war from [releases page](https://github.com/gitbucket/gitbucket/releases), to update from 4.34, i.e. copied it to /var/lib/tomcat9/webapps folder on my Ubuntu 20.04 LTS machine
- Started Tomcat
- gitbucket was not available anymore (404 error), and the tomcat logs showed the following errors:
```
Error deploying web application archive [/var/lib/tomcat9/webapps/gitbucket.war]
java.lang.IllegalStateException: Error starting child
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:720)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1849)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
    at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
    at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
    at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
    at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
    at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
    at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
    at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
    at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
    at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
    at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
    at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
    at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
    at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
    at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
    at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localho>
    at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
    ... 37 more
Caused by: java.lang.IllegalArgumentException: Negative time
    at java.base/java.io.File.setLastModified(File.java:1441)
    at org.apache.catalina.startup.ExpandWar.expand(ExpandWar.java:169)
    at org.apache.catalina.startup.ContextConfig.fixDocBase(ContextConfig.java:615)
    at org.apache.catalina.startup.ContextConfig.beforeStart(ContextConfig.java:747)
    at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:303)
    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
    at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:182)
    ... 38 more
```

**Workaround:**
- Unpack gitbucket.war
- Remove gitbucket.war
- Re-pack with `jar -cf gitbucket.war *`
- Deploy the new gitbucket.war
- Works!

There is probably some file with invalid file date included in the .war files? I have seen references to some bug in maven (https://stackoverflow.com/questions/8583853/negative-time-from-jsp-compiler), maybe this is causing my problems?

**Comment by takezoe** [comment]
Looks like a sbt issue: https://github.com/sbt/sbt/pull/5344

**Comment by codeling** [comment]
Thanks for looking into this so quickly!
I'm a bit confused as to the exact reasons behind - seems this was a "feature" to make the build more reproducible; so it might actually be considered a Tomcat bug?

**Comment by takezoe** [comment]
Actually, I'm not sure. Looks like sbt set `0` in this case, but Tomcat has a guard for `0`: https://github.com/apache/tomcat/blob/9.0.31/java/org/apache/catalina/startup/ExpandWar.java#L168

**Comment by takezoe** [comment]
I took a closer look and I found there is a case that sbt sets a negative value as timestamp to ZipEntry depending on the timezone. I sent a pull request to sbt to prevent it: https://github.com/sbt/sbt/pull/6254
