### ISSUE TITLE
Error when uploading file to release page

### ISSUE THREAD

**Issue by Nunocky** [gitbucket/gitbucket#2673]
## Issue

* Impacted version: 4.34.0
* database : PostgreSQL 9.2.24
* Deployment mode: apache tomcat

I run gitbucket with PostgreSQL as the backend.

When I create a release page in a project and try to upload a file in edit, it sometimes fails.

The file is about 400KB in size. Uploads don't always fail, they can succeed.

I attached GitBucket_error.txt.
[GitBucket_error.txt](https://github.com/gitbucket/gitbucket/files/5955378/GitBucket_error.txt)

**Comment by SIkebe** [comment]
>Caused by: org.postgresql.util.PSQLException: ERROR: 重複キーが一意性制約"release_asset_release_asset_id_key"に違反しています
  詳細: キー (release_asset_id)=(34) はすでに存在します
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2211)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:309)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.$anonfun$run$15(JdbcActionComponent.scala:520)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.run(JdbcActionComponent.scala:517)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingInsertInvoker.insert(BlockingProfile.scala:125)
	at gitbucket.core.service.ReleaseService.createReleaseAsset(ReleaseService.scala:22)

@Nunocky It seems that you have a unique constraint violation in `release_asset_release_asset_id_key`.
You might have missed the configuration for the sequence when you migrated from H2.

![image](https://user-images.githubusercontent.com/17608272/107518613-8e625a00-6bf2-11eb-8f68-d5c2ba474346.png)

**Comment by SIkebe** [comment]
Ah, missing instruction here. I'll add one, thanks!
https://github.com/gitbucket/gitbucket/wiki/External-database-configuration#postgresql

**Comment by takezoe** [comment]
@SIkebe Thanks!!

**Comment by Nunocky** [comment]
Unfortunately, it didn't work.

<img width="793" alt="スクリーンショット 2021-02-15 7 25 53" src="https://user-images.githubusercontent.com/750091/107891154-31530500-6f60-11eb-9151-63363311c3b3.png">

> org.postgresql.util.PSQLException: ERROR: "release_asset_release_asset_id_key" is not a sequence.

Is this a typo of "release_asset_release_asset_id_seq"?

<img width="799" alt="スクリーンショット 2021-02-15 7 45 13" src="https://user-images.githubusercontent.com/750091/107891423-e934e200-6f61-11eb-8615-36125155726e.png">

**Comment by takezoe** [comment]
> Is this a typo of "release_asset_release_asset_id_seq"?

Ah, I believe so. Updated the WIki page.

**Comment by Nunocky** [comment]
I tried it and found that it didn't cause any problems.
Thank you so much! 😃

**Comment by takezoe** [comment]
Good to hear that! Then I would close this. Thank you.
