### ISSUE TITLE
Unable to migrate the application to Tomcat 7.0.108, Fails with 404 error.

### ISSUE THREAD

**Issue by sahil-sardana** [gitbucket/gitbucket#2700]
### Before submitting an issue to GitBucket I have first:

- [ ] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [ ] searched for similar already existing issue
- [ ] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki)

*(if you have performed all the above, remove the paragraph and continue describing the issue with template below)*

## Issue
**Impacted version**: xxxx

**Deployment mode**: *explain here how you use GitBucket : standalone app, under webcontainer (which one), with an http frontend (nginx, httpd, ...)*

**Problem description**:
- *be as explicit as you can*
- *describe the problem and its symptoms*
- *explain how to reproduce*
- *attach whatever information that can help understanding the context (screen capture, log files)*

**Comment by takezoe** [comment]
@sahil-sardana Could you show us the error log you got when you failed to start with restored data.

**Comment by sahil-sardana** [comment]
Although I have configured the ldap, with same config as old gitbucket.conf but still it is failing to authenticate. When I try to login I get below message in logs:

08:15:23.810 [http-bio-8080-exec-3] INFO  gitbucket.core.util.LDAPUtil$ - LDAPException: Reader thread terminated (91) Connect Error
javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
08:15:23.810 [http-bio-8080-exec-3] INFO  g.core.service.AccountService - LDAP error: System LDAP authentication failed.
08:15:23.832 [http-bio-8080-exec-3] INFO  g.core.service.AccountService - Failed to authenticate: sahil.sardana


I have created an AMI of the existing server and upgrading tomcat & gitbucket on the new server. So ideally the keys and certs should be present on the new server as well.

**Comment by takezoe** [comment]
Is that actually migration issue? Please make sure that a fresh installation works first.

**Comment by sahil-sardana** [comment]
I have not migrated anything, I just added the gitbucket.conf file and it started throwing this error.

**Comment by takezoe** [comment]
Then, that would be a LDAP configuration issue...

**Comment by sahil-sardana** [comment]
Hello .. Thanks for your response.. same ldap config works fine on old version of gitbucket.

**Comment by takezoe** [comment]
I see, that means some changes in GitBucket affected.

Actually,  I don't have much experience about LDAP, and LDAP related changes in GitBucket in the history are very few:
https://github.com/gitbucket/gitbucket/commits/master/src/main/scala/gitbucket/core/util/LDAPUtil.scala

I think I cannot help you, you may be able to get help from someone by asking on Gitter.

**Comment by sahil-sardana** [comment]
Hello @takezoe  I was able to fix the issue with LDAP but the issue is migrating repositories. 

Can you please confirm how can I migrate the repositories/data to the new instance ? 

I have below files in .gitbucket directory:

total 651344
-rw-r--r--  1 tomcat tomcat      2199 Aug 24  2016 gitbucket.ser
-rwxrwxr-x  1 tomcat tomcat   4129541 Aug 25  2016 data.trace.db_3.14
-rwxrwxr-x  1 tomcat tomcat        83 Aug 30  2016 database.conf
-rwxrwxr-x  1 tomcat tomcat    716800 Aug 30  2016 data.mv.db_3.14
drwxr-xr-x  3 tomcat tomcat        20 Apr 19  2019 tmp
drwxrwxr-x 18 tomcat tomcat      4096 Apr 16  2020 data
drwxrwxr-x  3 tomcat tomcat        25 Jun 26  2020 gist
drwxrwxr-x 68 tomcat tomcat      4096 Sep 23 04:57 repositories
-rwxrwxr-x  1 tomcat tomcat         0 Mar  3 08:09 activity.log
-rwxrwxr-x  1 tomcat tomcat      1399 Mar  3 14:30 gitbucket.conf.ansible.bkp
-rwxrwxr-x  1 tomcat tomcat      1195 Mar  5 05:34 gitbucket.conf
drwxrwxr-x 11 tomcat tomcat      4096 Mar  5 08:36 ..
-rwxrwxr-x  1 tomcat tomcat   5747468 Mar  5 09:45 data.trace.db_backupu
drwxr-xr-x  4 tomcat tomcat      4096 Mar  5 09:58 plugins
-rwxrwxr-x  1 tomcat tomcat     69632 Mar  5 10:01 data.mv.db_working
drwxrwxr-x  7 tomcat tomcat      4096 Mar  5 10:02 .
-rw-r-----  1 tomcat tomcat      3639 Mar  5 10:02 data.trace.db
-rwxrwxr-x  1 tomcat tomcat 656257024 Mar  5 10:02 data.mv.db

As soon as I restored the original data.mv.db it started failing with below error:

[localhost-startStop-1] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "COMMIT_COMMENT" not found; SQL statement:
ALTER TABLE PUBLIC.COMMIT_COMMENT ADD CONSTRAINT PUBLIC.IDX_COMMIT_COMMENT_PK PRIMARY KEY(COMMENT_ID) INDEX PUBLIC.PRIMARY_KEY_699 [42102-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
        at org.h2.message.DbException.get(DbException.java:205)
        at org.h2.message.DbException.get(DbException.java:181)
        at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:108)
        at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
        at org.h2.engine.MetaRecord.execute(MetaRecord.java:60)
        at org.h2.engine.Database.open(Database.java:842)
