### ISSUE TITLE
ZIP package generated misses files when repo containing submoudle

### ISSUE THREAD

**Issue by suikabreaker** [gitbucket/gitbucket#2787]
## Issue
**Impacted version**: not sure, i have no admin privilege to check it. but likely the latest.

**Deployment mode**: standalone app

**Problem description**:
After added a submodule to my repo, it fails to generate correct zip package for "Download ZIP" button, with a lot of file missing.
It looks like everything come after the submodule folder in dictionary order is not packed.

**Comment by gemmaro** [comment]
Maybe it is related to #2393.

**Comment by takezoe** [comment]
I confirmed that this error is reproducible.
```
org.eclipse.jgit.errors.MissingObjectException: Missing unknown 8497b6d74177fcfee2e11c6f74fdeb3907f5afec
        at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:135)
        at org.eclipse.jgit.lib.ObjectDatabase.open(ObjectDatabase.java:143)
        at org.eclipse.jgit.lib.ObjectDatabase.open(ObjectDatabase.java:113)
        at org.eclipse.jgit.lib.Repository.open(Repository.java:331)
        at gitbucket.core.util.JGitUtil$.openFile(JGitUtil.scala:1306)
        at gitbucket.core.util.JGitUtil$.$anonfun$openFile$3(JGitUtil.scala:1329)
        at scala.util.Using$.resource(Using.scala:261)
        at gitbucket.core.util.JGitUtil$.openFile(JGitUtil.scala:1328)
        at gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$archiveRepository$2(RepositoryViewerController.scala:1233)
        at gitbucket.core.controller.RepositoryViewerControllerBase.$anonfun$archiveRepository$2$adapted(RepositoryViewerController.scala:1218)
        ...
```

**Comment by takezoe** [comment]
We will just ignore submodules when creating a repository archive.
