### ISSUE TITLE
Upgrade issue - Old server 3.10

### ISSUE THREAD

**Issue by gabafjego** [gitbucket/gitbucket#2861]
## Issue
**Impacted version**: 3.10.1 and all above

**Deployment mode**: 
- Tomcat 7.0.65
- Nginx 1.18.0
- H2 1.4.190 (2015-10-11)

**Problem description**:
I did duplicate the environment on a test VM. And everything is running well in the same version, 3.10.

Trying to upgrade, replacing the WAR file, looks like the upgrade process, Gitbucket is updated.
_Versions tried: 3.10.1 / 3.11 / 3.12 / 3.13 / 3.14 / 4.0 (one by one, also straight to 3.14)_

After checking the website, everything looks good.
But when I go to Repository > Branches from the menu, a blank page is displayed.
Although, all branches are ok to be accessible via the switch button (repository > Files).

I could catch this error on catalina log:

```
server[76045]: org.h2.jdbc.JdbcSQLException: Table "PROTECTED_BRANCH" not found; SQL statement:
server[76045]: select x2."BRANCH" from "PROTECTED_BRANCH" x2 where (x2."USER_NAME" = ?) and (x2."REPOSITORY_NAME" = ?) [42102-192]
```
I used the backup and restore tools :
java -cp lib/h2-1.4.190.jar org.h2.tools.Script
java -cp lib/h2-1.4.190.jar org.h2.tools.RunScript
Issue for RunScript:
```
Exception in thread "main" org.h2.jdbc.JdbcSQLException: Table "ISSUE_COMMENT" already exists; SQL statement:

CREATE CACHED TABLE PUBLIC.ISSUE_COMMENT(
    USER_NAME VARCHAR(100) NOT NULL SELECTIVITY 1,
    REPOSITORY_NAME VARCHAR(100) NOT NULL SELECTIVITY 1,
    ISSUE_ID INT NOT NULL SELECTIVITY 24,
    COMMENT_ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_7ADD5B54_60D2_4A26_BC5D_B9CAECC05108) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_7ADD5B54_60D2_4A26_BC5D_B9CAECC05108 SELECTIVITY 100,
    ACTION VARCHAR(20) NOT NULL SELECTIVITY 1,
    COMMENTED_USER_NAME VARCHAR(100) NOT NULL SELECTIVITY 1,
    CONTENT TEXT NOT NULL,
    REGISTERED_DATE TIMESTAMP NOT NULL SELECTIVITY 91,
    UPDATED_DATE TIMESTAMP NOT NULL SELECTIVITY 91
) [42101-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:115)
	at org.h2.command.dml.RunScriptCommand.execute(RunScriptCommand.java:78)
	at org.h2.command.dml.RunScriptCommand.update(RunScriptCommand.java:57)
	at org.h2.command.CommandContainer.update(CommandContainer.java:78)
	at org.h2.command.Command.executeUpdate(Command.java:253)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.tools.RunScript.processRunscript(RunScript.java:282)
	at org.h2.tools.RunScript.runTool(RunScript.java:139)
	at org.h2.tools.RunScript.main(RunScript.java:68)
```

java -cp lib/h2-1.4.190.jar org.h2.tools.Backup
java -cp lib/h2-1.4.190.jar org.h2.tools.Restore 

Strange thing is I can not see this TABLE "PROTECTED_BRANCH" anywhere, even in the working Gitbucket running on 3.10 (duplicate) as well as the production one under 3.10.

The goal is to migrate everything to a new server, in the last version 4.36.2 with Postgres.

Could you point out the issue ?

Thank you

**Comment by gabafjego** [comment]
Managed to upgrade a duplicate of the production server to 4.0.
Migrated DB and data to the test server under Postgres13, Gitbucket 4.0.

(Migration from in place 3.10 to test server 3.10 still fail, although it's not an issue anymore)
