### ISSUE TITLE
org.scalatra.servlet.SizeConstraintExceededException: Too large request or file

### ISSUE THREAD

**Issue by rysyd** [gitbucket/gitbucket#3074]
Version:
Both GitBucket are 4.8

I export the SQL file of size 15M from another Gitbucket,
I get this error when I import:
```
org.scalatra.servlet.SizeConstraintExceededException: Too large request or file
	at org.scalatra.servlet.FileUploadSupport$class.getParts(FileUploadSupport.scala:134)
	at org.scalatra.servlet.FileUploadSupport$class.extractMultipartParams(FileUploadSupport.scala:111)
	at org.scalatra.servlet.FileUploadSupport$class.handle(FileUploadSupport.scala:82)
	at gitbucket.core.controller.FileUploadController.handle(FileUploadController.scala:23)
	at org.scalatra.ScalatraServlet$class.service(ScalatraServlet.scala:60)
	at gitbucket.core.controller.FileUploadController.service(FileUploadController.scala:23)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply$mcV$sp(ScalatraFilter.scala:74)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:74)
	at org.scalatra.ScalatraFilter$$anonfun$1.apply(ScalatraFilter.scala:74)
	at org.scalatra.ScalatraBase$$anonfun$2$$anonfun$apply$4.apply(ScalatraBase.scala:178)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalatra.ScalatraBase$$anonfun$2.apply(ScalatraBase.scala:178)
        ......
```

**Comment by takezoe** [comment]
If you run GitBucket in the standalone mode (`java -jar gitbucket.war`), you can specify `--max_file_size` option to increase the upper limit of upload file size. See more details at: https://github.com/gitbucket/gitbucket/wiki/Basic-configurations
