### ISSUE TITLE
tags API appears to be missing?

### ISSUE THREAD

**Issue by jbalonso** [gitbucket/gitbucket#3091]
## Issue
**Impacted version**: 4.37.2

**Deployment mode**: docker container with traefik proxy (ACME https + ssh-passthrough)

**Problem description**:
- High-level: Jenkins can discover tags (contrasts with #2506) but cannot retrieve commits by tag.
- Low-level: `/api/v3/repos/OWNER_NAME/REPO_NAME/git/ref/tags/TAG_NAME` appears to return a valid structure, but `.object.url` within that structure comes back with `{"message":"Not Found"}`

**Sanitized Jenkins log**
This comes from manually triggering a build on a tag:
```
Started by user [Jason B. Alonso](https://JENKINS.FQDN/user/jalonso)
11:31:03 Connecting to https://GITBUCKET.FQDN/api/v3 using gitbucket
java.io.FileNotFoundException: https://GITBUCKET.FQDN/api/v3/repos/ORG_NAME/REPO_NAME/git/tags/2c950780ca32951f705889455afcd81f5b2de3c7
	at org.kohsuke.github.GitHubConnectorResponseErrorHandler$1.onError(GitHubConnectorResponseErrorHandler.java:54)
	at org.kohsuke.github.GitHubClient.detectKnownErrors(GitHubClient.java:424)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:386)
Caused: org.kohsuke.github.GHFileNotFoundException: https://GITBUCKET.FQDN/api/v3/repos/ORG_NAME/REPO_NAME/git/tags/2c950780ca32951f705889455afcd81f5b2de3c7 {"message":"Not Found"}
	at org.kohsuke.github.GitHubClient.interpretApiError(GitHubClient.java:540)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:401)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:355)
	at org.kohsuke.github.Requester.fetch(Requester.java:76)
	at org.kohsuke.github.GHRepository.getTagObject(GHRepository.java:1826)
	at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.retrieve(GitHubSCMSource.java:1704)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:582)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:101)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:311)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
Finished: FAILURE
```

**Sanitized response to git-ref retrieval (from browser)**
From `https://GITBUCKET.FQDN/api/v3/repos/ORG_NAME/REPO_NAME/git/ref/tags/v0.1.0`, I get (after `jq`):
```
{
  "ref": "refs/tags/v0.1.0",
  "node_id": "",
  "url": "https://GITBUCKET.FQDN/api/v3/repos/ORG_NAME/REPO_NAME/git/refs/tags/v0.1.0",
  "object": {
    "sha": "2c950780ca32951f705889455afcd81f5b2de3c7",
    "type": "tag",
    "url": "https://GITBUCKET.FQDN/api/v3/repos/ORG_NAME/REPO_NAME/git/tags/2c950780ca32951f705889455afcd81f5b2de3c7"
  }
}
```
NOTE: the `.object.url` response above is identical to the failed GET from the Jenkins log.

**Response to tag retrieval (from browser)**
From `https://GITBUCKET.FQDN/api/v3/repos/ORG_NAME/REPO_NAME/git/tags/2c950780ca32951f705889455afcd81f5b2de3c7`:

```
{"message":"Not Found"}
```

**Comment by takezoe** [comment]
You reported that `object.url` in response is:
```
https://GITBUCKET.FQDN/api/v3/repos/ORG_NAME/REPO_NAME/git/tags/2c950780ca32951f705889455afcd81f5b2de3c7
```
but it actually should be:
```
https://GITBUCKET.FQDN/api/v3/repos/ORG_NAME/REPO_NAME/git/commits2c950780ca32951f705889455afcd81f5b2de3c7
```
https://github.com/gitbucket/gitbucket/blob/56df833b4aa8bf1b0101b67fee8236c99c3d1f0a/src/main/scala/gitbucket/core/api/ApiRef.scala#L51
