### ISSUE TITLE
new repository NoClassDefFoundError: gitbucket/core/model/ActivityComponent

### ISSUE THREAD

**Issue by wencyGit** [gitbucket/gitbucket#3099]
- Run sbt executable. The release war file
- run  java -jar gitbucket.war
- login new repository，the following error is reported
```
19:33:10.502 [scala-execution-context-global-44] INFO  o.c.core.Cache2kCoreProviderImpl - cache2k starting. version=1.6.0.Final
19:33:10.565 [scala-execution-context-global-44] WARN  o.c.e.a.WarnAboutCache2kAllUsage - Usage of the artifact cache2k-all is deprecated, please update your dependencies. See: https://cache2k.org/docs/latest/user-guide.html#getting-started
java.lang.NoClassDefFoundError: gitbucket/core/model/ActivityComponent
        at gitbucket.plugin.service.PagesService.registerPageOptions(PagesService.scala:16)
        at gitbucket.plugin.service.PagesService.registerPageOptions$(PagesService.scala:15)
        at gitbucket.plugin.pages.PagesHook.registerPageOptions(PagesHook.scala:8)
        at gitbucket.plugin.pages.PagesHookBase.created(PagesHook.scala:14)
        at gitbucket.plugin.pages.PagesHookBase.created$(PagesHook.scala:13)
        at gitbucket.plugin.pages.PagesHook.created(PagesHook.scala:8)
        at gitbucket.core.service.RepositoryCreationService.$anonfun$createRepository$7(RepositoryCreationService.scala:172)
        at gitbucket.core.service.RepositoryCreationService.$anonfun$createRepository$7$adapted(RepositoryCreationService.scala:172)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at gitbucket.core.service.RepositoryCreationService.$anonfun$createRepository$2(RepositoryCreationService.scala:172)
        at gitbucket.core.service.RepositoryCreationService.$anonfun$createRepository$2$adapted(RepositoryCreationService.scala:83)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
        at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
        at gitbucket.core.service.RepositoryCreationService.$anonfun$createRepository$1(RepositoryCreationService.scala:83)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassNotFoundException: gitbucket.core.model.ActivityComponent
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        ... 26 more

```

**Comment by takezoe** [comment]
The bundled plugins are needed to rebuild for the latest version of GitBucket.
