### ISSUE TITLE
ArrayIndexOutOfBoundsException  with MariaDB JDBC driver 3.0.7/3.0.8

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#3188]
### Before submitting an issue to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki)

*(if you have performed all the above, remove the paragraph and continue describing the issue with template below)*

## Issue
**Impacted version**: 4.38.0 - 4.38.3

**Problem description**:
- The following exception was reported in https://github.com/gitbucket/gitbucket/issues/3183
```
java.sql.SQLException: Wrong index position. Is 2 but must be in 1-1 range
	at org.mariadb.jdbc.codec.RowDecoder.checkIndexAndSetPosition(RowDecoder.java:90)
	at org.mariadb.jdbc.codec.RowDecoder.getValue(RowDecoder.java:109)
	at org.mariadb.jdbc.client.result.Result.getString(Result.java:379)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getString(HikariProxyResultSet.java)
	at slick.jdbc.JdbcTypesComponent$JdbcTypes$StringJdbcType.getValue(JdbcTypesComponent.scala:405)
	at slick.jdbc.JdbcTypesComponent$JdbcTypes$StringJdbcType.getValue(JdbcTypesComponent.scala:402)
	at slick.jdbc.SpecializedJdbcResultConverter$$anon$1.read(SpecializedJdbcResultConverters.scala:26)
	at slick.jdbc.SpecializedJdbcResultConverter$$anon$1.read(SpecializedJdbcResultConverters.scala:24)
	at slick.relational.ProductResultConverter.read(ResultConverter.scala:54)
	at slick.relational.ProductResultConverter.read(ResultConverter.scala:44)
	at slick.relational.TypeMappingResultConverter.read(ResultConverter.scala:134)
	at slick.jdbc.JdbcInvokerComponent$QueryInvokerImpl.extractValue(JdbcInvokerComponent.scala:36)
	at slick.jdbc.StatementInvoker$$anon$2.extractValue(StatementInvoker.scala:67)
	at slick.jdbc.PositionedResultIterator.fetchNext(PositionedResult.scala:176)
	at slick.util.ReadAheadIterator.update(ReadAheadIterator.scala:28)
	at slick.util.ReadAheadIterator.hasNext(ReadAheadIterator.scala:34)
	at slick.util.ReadAheadIterator.hasNext$(ReadAheadIterator.scala:33)
	at slick.jdbc.PositionedResultIterator.hasNext(PositionedResult.scala:167)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
	at slick.jdbc.PositionedResultIterator.foreach(PositionedResult.scala:167)
	at slick.jdbc.Invoker.foreach(Invoker.scala:48)
	at slick.jdbc.Invoker.foreach$(Invoker.scala:46)
	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
	at slick.jdbc.Invoker.firstOption(Invoker.scala:23)
	at slick.jdbc.Invoker.firstOption$(Invoker.scala:21)
	at slick.jdbc.StatementInvoker.firstOption(StatementInvoker.scala:16)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingQueryInvoker.firstOption(BlockingProfile.scala:87)
	at gitbucket.core.service.AccountService.getAccountByUserName(AccountService.scala:113)
	at gitbucket.core.service.AccountService.getAccountByUserName$(AccountService.scala:112)
	...
```

**Comment by takezoe** [comment]
I tested a fresh installation with MariaDB 10.9.3 but these errors didn't occur. There should be some specific factors to reproduce the errors.

**Comment by pluk77** [comment]
We are using AD authentication. Not sure if that is related? Also, could
the java 'flavour' and version have anything to do with it? What info can I
provide to help?

**Comment by takezoe** [comment]
I have tried both with Java 8 and Java 11 but didn't reproduce errors.

MariaDB version you are using might be helpful to reproduce. Or it would be a great help if you can show a procedure to reproduce the error on a fresh installation.

**Comment by pluk77** [comment]
MariaDB version 10.5.12.

Trying a fresh install now. I can run it with the build-in DB, but when I setup the DB connection to a new MariaDB database and restart GitBucket, I get these errors:

```
06:54:03.147 [main] INFO  g.core.servlet.InitializeListener - Check version
06:54:03.147 [main] INFO  g.core.servlet.InitializeListener - Start schema update
06:54:03.217 [main] WARN  o.m.jdbc.message.server.ErrorPacket - Error: 1146-42S02: Table 'gitbucket_221107.VERSIONS' doesn't exist
```

Before doing this, I have exported the DB from data export/import, but the resulting sql file does not contain the schema, only delete and insert statements. What am I doing wrong?

After creating an empty VERSIONS table based on the original schema, GitBucket started and created the rest of the tables and populated them.

It is running as expected now on version 4.38.3

After stopping and adding my old configuration, I can login using our AD accounts without error but there are no repositories listed. No errors either.

I could create a new Repo without errors.

Comparing the schema of the new and old DB shows no differences. Starting to think the problem is very specific to the existing data.

**Comment by takezoe** [comment]
Thank you for confirmation!

> Starting to think the problem is very specific to the existing data.

Yeah... It's really tough to identify the root cause in that case.

> Before doing this, I have exported the DB from data export/import, but the resulting sql file does not contain the schema, only delete and insert statements.

This is expected because all tables have been created by GitBucket automatically when you import that file on the admin console.

> After creating an empty VERSIONS table based on the original schema

Hmm, `VERSIONS` should be created automatically when launching GitBucket for the first time.
