### ISSUE TITLE
Installing on custom port

### ISSUE THREAD

**Issue by FuckingToasters** [gitbucket/gitbucket#3342]
## Issue
**Impacted version**: 4.39.0

**Deployment mode** : standalone app (java -jar gitbucket.war)
**Problem description**:
1. It try to use port 8080 which is already used by the apache2 service.

2. I have multiple sites running via apache2 and changing the port from 8080 to something else causes the sites to not being rendered correctly so this isn't a good solution.

3. I have tried to specify an custom port when running the install command (java -Djetty.port=8081 -jar gitbucket.war) which however caused the same error (it still seem to try using 8080)

4. Error Log
```java
Exception in thread "main" java.io.IOException: Failed to bind to /0.0.0.0:8080
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.server.Server.doStart(Server.java:401)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at JettyLauncher.main(JettyLauncher.java:246)
Caused by: java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:459)
        at java.base/sun.nio.ch.Net.bind(Net.java:448)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344)
        ... 7 more
```

**Comment by takezoe** [comment]
You can use `--port` option to specify the port number:
https://github.com/gitbucket/gitbucket/wiki/Basic-configurations

**Comment by takezoe** [comment]
Looks like you have already found the solution: https://github.com/gitbucket/gitbucket/issues/3358
