### ISSUE TITLE
Can't download large raw file(LFS)

### ISSUE THREAD

**Issue by eighttails** [gitbucket/gitbucket#3573]
### Before submitting an issue to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki)

## Issue
**Impacted version**: 4.41.0

**Deployment mode**: using gitbucket.war in Debian testing x64.

**Problem description**:
- *describe the problem and its symptoms*
  - I'm trying to manage machine learning models with git LFS(like HuggingFace).
  - I can commit, push, clone large files with gitbucket.
  - But I can't download single model file in web browser, curl, wget etc.
- *How to reproduce*
  - Create repository `git init`
  - Create file larger than 4GB
  - Commit and push to new gitbucket repository
  - Open gitbucket repository in browser.
  - Click "View Raw" link.
  - Nothing happens. and can't download file.
- The log says `java.lang.NumberFormatException: For input string: "4411406624"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:668)`
[gitbucket.log](https://github.com/user-attachments/files/16529368/gitbucket.log)
- Probably because ParseInt can't handle file sizes larger than 4GB.("4411406624" is length of the file.)

- "View Raw" link and "Raw" button on the right side do not work either.
![image](https://github.com/user-attachments/assets/ddabec41-c53e-4c36-aa60-c3ae5e845ce9)

**Comment by eighttails** [comment]
this may help.
https://takao0616.hatenablog.com/entry/2019/02/20/220133
