### ISSUE TITLE
Using [raw] button: very slow or timeout

### ISSUE THREAD

**Issue by 3-O** [gitbucket/gitbucket#738]
Upon attempting to display a 124kB svg file raw, I invariabily get a "Bad gateway" error (behind proxy) and the file is never displayed raw.
Similarly, displaying a text file raw is incredibly slow.
Is this the reason why github is serving such files from a different server?
https://raw.githubusercontent.com/takezoe/gitbucket/3732963d4baecc0f0ee790fa11d64c939083ea58/etc/icons.svg

Bug?

**Comment by 3-O** [comment]
java.lang.IllegalStateException: STREAM
        at org.eclipse.jetty.server.Response.getWriter(Response.java:693)
        at org.scalatra.ScalatraBase$class.renderUncaughtException(ScalatraBase.scala:214)
        at gitbucket.core.controller.ControllerBase.renderUncaughtException(ControllerBase.scala:27)
        at org.scalatra.ScalatraBase$$anonfun$executeRoutes$2$$anonfun$apply$5.apply(ScalatraBase.scala:182)
        at org.scalatra.ScalatraBase$$anonfun$executeRoutes$2$$anonfun$apply$5.apply(ScalatraBase.scala:179)
        at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:206)
        at org.scalatra.ScalatraBase$$anonfun$executeRoutes$2.apply(ScalatraBase.scala:176)
        at org.scalatra.ScalatraBase$$anonfun$executeRoutes$2.apply(ScalatraBase.scala:175)
        at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:206)
        at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175)
        at gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:27)
        at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113)
        at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
        at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80)
        at gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:27)
        at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
        at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
        at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59)
        at gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:27)
        at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111)
        at gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:27)
        at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43)
        at gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:27)
        at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply$mcV$sp(flashMap.scala:162)
        at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
        at org.scalatra.FlashMapSupport$$anonfun$handle$1.apply(flashMap.scala:136)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
        at gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:27)
        at org.scalatra.FlashMapSupport$class.handle(flashMap.scala:136)
        at gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:27)
        at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply$mcV$sp(ScalatraFilter.scala:33)
        at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
        at org.scalatra.ScalatraFilter$$anonfun$doFilter$1.apply(ScalatraFilter.scala:33)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.ScalatraFilter$class.doFilter(ScalatraFilter.scala:32)
        at gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:64)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)
        at gitbucket.core.servlet.TransactionFilter$$anonfun$doFilter$1.apply(TransactionFilter.scala:37)
        at gitbucket.core.servlet.TransactionFilter$$anonfun$doFilter$1.apply(TransactionFilter.scala:28)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:54)
        at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
        at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54)
        at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withTransaction(JdbcBackend.scala:46)
        at gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:28)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:370)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:745)

**Comment by takezoe** [comment]
I couldn't get such an Exception in my environment.
Could you try at the demo site on Heroku?
https://gitbucket.herokuapp.com/

However, as you say, retrieving raw file is slow in GitBucket certainly.
I will try to improve it.

**Comment by 3-O** [comment]
I did try at the demo site. I get the error as soon as I click the raw button for both svg (see root/test and pouic.svg and redblacktrees.svg that are both CC attributed to http://www.nojhan.net/).

The error (same occured twice):
![error](https://cloud.githubusercontent.com/assets/12143150/7488249/d080ea90-f3c7-11e4-9dde-d95eec4718b4.png)

**Comment by takezoe** [comment]
Thanks, I will try again.

**Comment by takezoe** [comment]
@3-O Could you provide a url to download SVG file that you tested?
I tried again but I couldn't reproduce an exception by some SVG files (almost 100-200KB).

**Comment by 3-O** [comment]
Sure. For the test repository, I used:
http://www.nojhan.net/art/public/pouics_vector_1.svg
http://www.nojhan.net/art/public/vagues.svg

But I believe the svg itself does not matter so much. I used three different ones and always it generated an error. (The error is triggered upon clicking on the raw button.)

**Comment by takezoe** [comment]
This problem is caused by automatic charset detection in Scalatra for text files.
I will send pull request to Scalatra to fix this problem, but as temporary fix, I will set "application/octet-stream" as Content-Type in GitBucket 3.3. The browser will downloads the raw file instead of rendering it in the window. But response will be quickly.

Thanks for your feedback!

**Comment by takezoe** [comment]
I sent a pull request to Scalatra: https://github.com/scalatra/scalatra/pull/500
